'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
Dim rackid, store, itemtype
store = Trim(Request("store"))
rackid = Trim(Request("rack-id"))
If UCase(store) = "S20" Then
    itemtype = "Item"
Else
    itemtype = "Drug"
End If
Load
Sub Load()
    response.Clear
    response.write vbCrLf & "<html lang=""en"">"
    response.write vbCrLf & "<head>"
    response.write vbCrLf & "    <meta charset=""UTF-8"">"
    response.write vbCrLf & "    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
    response.write vbCrLf & "    <title>Document</title>"
    response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.googleapis.com"">"
    response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.gstatic.com"" crossorigin>"
    response.write vbCrLf & "    <link href=""https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"" rel=""stylesheet"">"
    response.write vbCrLf & "    <style>"
    response.write vbCrLf & "        body{"
    response.write vbCrLf & "            background-color: whitesmoke;"
    response.write vbCrLf & "            padding: 0;"
    response.write vbCrLf & "            margin: 0;"
    response.write vbCrLf & "            font-size: 14px;"
    response.write vbCrLf & "            font-family: 'Nunito',sans-serif;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .top-bar{"
    response.write vbCrLf & "            background-color: white;"
    response.write vbCrLf & "            padding: 10px 4rem 0 4rem;"
    response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            justify-content: space-between;"
    response.write vbCrLf & "            align-items: center;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .branch select{"
    response.write vbCrLf & "            font-family: inherit;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .dynamic-content{"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        button{"
    response.write vbCrLf & "            padding: 3px 15px;"
    response.write vbCrLf & "            height: fit-content;"
    response.write vbCrLf & "            color: white;"
    response.write vbCrLf & "            border: none;"
    response.write vbCrLf & "            font-family: inherit;"
    response.write vbCrLf & "            font-size: 13px;"
    response.write vbCrLf & "            border-radius: 5px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .nav-link{"
    response.write vbCrLf & "            list-style: none;"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            padding: 0;"
    response.write vbCrLf & "            margin: 0;"
    response.write vbCrLf & "            cursor: pointer;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .nav-link li{"
    response.write vbCrLf & "            padding:10px 10px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .nav-link-active{"
    response.write vbCrLf & "            background-color: rgba(220, 220, 220,0.3);"
    response.write vbCrLf & "            border-bottom: 3px solid #0078D4;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .dynamic-content{"
    response.write vbCrLf & "            padding: 10px 4rem;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .h2{"
    response.write vbCrLf & "            padding: 10px 12px;"
    response.write vbCrLf & "            border: 1px solid gainsboro;"
    response.write vbCrLf & "            background-color: white;"
    response.write vbCrLf & "            border-radius: 10px;"
    response.write vbCrLf & "            box-shadow: 0px 0px 5px 0px gainsboro;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .h2-h3{"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            justify-content: space-between;"
    response.write vbCrLf & "            align-items: center;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .rack-table{"
    response.write vbCrLf & "            background-color: whitesmoke;"
    response.write vbCrLf & "            border-collapse: collapse;"
    response.write vbCrLf & "            border-spacing: 0;"
    response.write vbCrLf & "            border-radius: 3px;"
    response.write vbCrLf & "            contain: paint;"
    response.write vbCrLf & "            border: 1px solid grey;"
    response.write vbCrLf & "            font-size: 13px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .rack-table thead{"
    response.write vbCrLf & "            background-color: #accadd;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .rack-table tbody>:nth-child(even){"
    response.write vbCrLf & "            background-color: rgb(235, 234, 234);"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .rack-table th,.rack-table td{"
    response.write vbCrLf & "            padding: 8px 10px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .rack-table td{"
    response.write vbCrLf & "            text-align: center;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .status{"
    response.write vbCrLf & "            padding: 4px 10px;"
    response.write vbCrLf & "            border-radius: 10px;"
    response.write vbCrLf & "            background-color: forestgreen;"
    response.write vbCrLf & "            color: white;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .action-cs{"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            place-items: center;"
    response.write vbCrLf & "            place-content: center;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .action-cs label{"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            place-items: center;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .dialog-container{"
    response.write vbCrLf & "            position: fixed;"
    response.write vbCrLf & "            top: 0;"
    response.write vbCrLf & "            left: 0;"
    response.write vbCrLf & "            right: 0;"
    response.write vbCrLf & "            bottom: 0;"
    response.write vbCrLf & "            width: 100%;"
    response.write vbCrLf & "            height: 100vh;"
    response.write vbCrLf & "            z-index: 1000;"
    response.write vbCrLf & "            display: none;"
    response.write vbCrLf & "            background-color: rgba(55, 55, 55,0.8);"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .flex{"
    response.write vbCrLf & "            display: flex !important;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .dialog{"
    response.write vbCrLf & "            margin: 10vh auto 0 auto;"
    response.write vbCrLf & "            border: none;"
    response.write vbCrLf & "            width: 500px;"
    response.write vbCrLf & "            min-height: 100px;"
    response.write vbCrLf & "            border-radius: 5px;"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            flex-direction: column;"
    response.write vbCrLf & "            box-shadow: 0 0 10px 1px gray;"
    response.write vbCrLf & "            padding: 0;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .dialog-head{"
    response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
    response.write vbCrLf & "            padding: 10px 15px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .dialog-action{"
    response.write vbCrLf & "            display: flex;"
    response.write vbCrLf & "            justify-content: flex-end;"
    response.write vbCrLf & "            gap: 5px;"
    response.write vbCrLf & "            padding: 7px 15px;"
    response.write vbCrLf & "            border-top: 1px solid gainsboro;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .content{"
    response.write vbCrLf & "            flex: 1;"
    response.write vbCrLf & "            display: grid;"
    response.write vbCrLf & "            padding: 10px 15px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .spinner-container{"
    response.write vbCrLf & "            position: fixed;"
    response.write vbCrLf & "            top: 0;"
    response.write vbCrLf & "            left: 0;"
    response.write vbCrLf & "            right: 0;"
    response.write vbCrLf & "            bottom: 0;"
    response.write vbCrLf & "            width: 100%;"
    response.write vbCrLf & "            background-color: rgba(55, 55, 55,0.8);"
    response.write vbCrLf & "            display: none;"
    response.write vbCrLf & "            align-items: center;"
    response.write vbCrLf & "            z-index:1000000;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .spinner{"
    response.write vbCrLf & "            width: 60px;"
    response.write vbCrLf & "            height: 60px;"
    response.write vbCrLf & "            background-color: transparent;"
    response.write vbCrLf & "            border: 7px solid grey;"
    response.write vbCrLf & "            border-top: 7px solid whitesmoke;"
    response.write vbCrLf & "            border-radius: 50%;"
    response.write vbCrLf & "            margin: 0 auto;"
    response.write vbCrLf & "            animation: spin 0.9s ease infinite;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .search-box{"
    response.write vbCrLf & "            position: relative;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .search-box ul{"
    response.write vbCrLf & "            position: absolute;"
    response.write vbCrLf & "            list-style: none;"
    response.write vbCrLf & "            padding: 0;"
    response.write vbCrLf & "            left: 0;"
    response.write vbCrLf & "            right: 0;"
    response.write vbCrLf & "            bottom: -100%;"
    response.write vbCrLf & "            transform: translateY(90%);"
    response.write vbCrLf & "            background-color: whitesmoke;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .search-box li{"
    response.write vbCrLf & "            padding: 5px 10px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        .search-box li:hover{"
    response.write vbCrLf & "            background-color: rgba(0, 120, 212,0.3);"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        #count{"
    response.write vbCrLf & "            background-color: burlywood;"
    response.write vbCrLf & "            padding: 3px 8px;"
    response.write vbCrLf & "            border-radius: 4px;"
    response.write vbCrLf & "            margin-left: 20px;"
    response.write vbCrLf & "            margin-right: 5px;"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        @keyframes spin {"
    response.write vbCrLf & "            to{"
    response.write vbCrLf & "                rotate: 360deg;"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "    </style>"
    response.write vbCrLf & "</head>"
    response.write vbCrLf & "<body>"
    response.write vbCrLf & "    <template id=""tableTemplate"">"
    response.write vbCrLf & "        <tr>"
    response.write vbCrLf & "            <td colspan=""1"" style=""text-align: left;"">{drug-id}</td>"
    response.write vbCrLf & "            <td colspan=""3"" style=""text-align: left;"">{drug-name}</td>"
    response.write vbCrLf & "            <td ></td>"
    response.write vbCrLf & "            <td ></td>"
    response.write vbCrLf & "            <td colspan=""1"">"
    response.write vbCrLf & "                <div class=""action-cs"">"
    response.write vbCrLf & "                    <button style=""background-color: #FF5739;"" id=""edit"">Delete</button>"
    response.write vbCrLf & "                </div>"
    response.write vbCrLf & "            </td>"
    response.write vbCrLf & "        </tr>"
    response.write vbCrLf & "    </template>"
    response.write vbCrLf & "    <main>"
    response.write vbCrLf & "        <div class=""top-bar"">"
    response.write vbCrLf & "            <h3>Add " & itemtype & " to Rack</h3>"
    response.write vbCrLf & "            <label class=""rack"">"
    response.write vbCrLf & "                Rack:"
    LoadRacks
    response.write vbCrLf & "            </label>"
    response.write vbCrLf & "        </div>"
    response.write vbCrLf & "        <div class=""dynamic-content"" id=""dynamic-content"">"
    response.write vbCrLf & "            <div class=""h2"">"
    response.write vbCrLf & "                <div class=""h2-h3"">"
    response.write vbCrLf & "                    <h4 style=""margin: 10px 0;""><span>" & itemtype & " In Rack " & GetComboName("PerformVar22", rackid) & "</span> <span id=""count"">0</span>Items</h4>"
    response.write vbCrLf & "                    <button style=""background-color: forestgreen;"" onclick=""addDrug(null)"">Add</button>"
    response.write vbCrLf & "                </div>"
    response.write vbCrLf & "                <table width=""100%"" class=""rack-table"">"
    response.write vbCrLf & "                    <thead>"
    response.write vbCrLf & "                        <tr>"
    response.write vbCrLf & "                            <th colspan=""1"" align='left'>" & itemtype & " ID</th>"
    response.write vbCrLf & "                            <th colspan=""3"" align='left'>" & itemtype & " Name</th>"
    response.write vbCrLf & "                            <th></th>"
    response.write vbCrLf & "                            <th></th>"
    response.write vbCrLf & "                            <th colspan=""1"">Action</th>"
    response.write vbCrLf & "                        </tr>"
    response.write vbCrLf & "                    </thead>"
    response.write vbCrLf & "                    <tbody id=""rack-list"">"
    response.write vbCrLf & "                    </tbody>"
    response.write vbCrLf & "                </table>"
    response.write vbCrLf & "            </div>"
    response.write vbCrLf & "        </div>"
    response.write vbCrLf & "    </main>"
    response.write vbCrLf & "    <template id=""searchElementTemplate"">"
    response.write vbCrLf & "        <li>{drug-id} [{drug-name}]</li>"
    response.write vbCrLf & "    </template>"
    response.write vbCrLf & "    <div class=""dialog-container"" id=""dialog-container"" >"
    response.write vbCrLf & "        <dialog class=""dialog"">"
    response.write vbCrLf & "            <div class=""dialog-head"">"
    response.write vbCrLf & "                <span>{dialog-name}</span>"
    response.write vbCrLf & "            </div>"
    response.write vbCrLf & "            <form id=""content"" class=""content"" onsubmit=""submitDrug(event)"">"
    response.write vbCrLf & "            </form>"
    response.write vbCrLf & "            <div class=""dialog-action"">"
    response.write vbCrLf & "                <button style=""background-color: #FF5739;"" onclick=""closeDialog()"">cancel</button>"
    response.write vbCrLf & "                <button style=""background-color: forestgreen;"" onclick=""proceed()"">proceed</button>"
    response.write vbCrLf & "            </div>"
    response.write vbCrLf & "        </dialog>"
    response.write vbCrLf & "    </div>"
    response.write vbCrLf & "    <script>"
    response.write vbCrLf & "        let controller = new AbortController();"
    response.write vbCrLf & "        const rackId = (new URL(window.location.href))?.searchParams?.get('rack-id')??'';"
    response.write vbCrLf & "        const store = (new URL(window.location.href))?.searchParams?.get('store')??'';"
    response.write vbCrLf & "        const tbl = (new URL(window.location.href))?.searchParams?.get('tbl')??'';"
    response.write vbCrLf & "        window.addEventListener('load',function(){"
    response.write vbCrLf & "            const rackSelect = document.getElementById('rack');"
    response.write vbCrLf & "            if(rackId!==''){"
    response.write vbCrLf & "                rackSelect.value = rackId;"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "            if(rackSelect){"
    response.write vbCrLf & "                rackSelect.onchange = function(){"
    response.write vbCrLf & "                    const url = new URL(window.location.href);"
    response.write vbCrLf & "                    if(rackSelect.value!==''){"
    response.write vbCrLf & "                        url.searchParams.set('rack-id',rackSelect.value)"
    response.write vbCrLf & "                    }else{"
    response.write vbCrLf & "                        url.searchParams.delete('rack-id');"
    response.write vbCrLf & "                    }"
    response.write vbCrLf & "                    window.location.href = url;"
    response.write vbCrLf & "                }"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "            loadStaff();"
    response.write vbCrLf & "        })"
    response.write vbCrLf & "        window.addEventListener('click',function(e){"
    response.write vbCrLf & "            const searchBox = document.querySelector('.search-box');"
    response.write vbCrLf & "            const searchList = document.querySelector('.search-box>ul');"
    response.write vbCrLf & "            if(searchBox){"
    response.write vbCrLf & "                if(!searchBox.contains(e.target)){"
    response.write vbCrLf & "                    searchList.innerHTML = '';"
    response.write vbCrLf & "                }"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "        })"
    response.write vbCrLf & "        function loadStaff(){"
    response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=Rack&operation=LOADDRUG&rack-id=' + rackId;"
    response.write vbCrLf & "            endpoint += '&store=' + store;"
    response.write vbCrLf & "            endpoint += '&tbl=' + tbl;"
    response.write vbCrLf & "            showLoader(true)"
    response.write vbCrLf & "            fetch(endpoint).then(res=>{"
    response.write vbCrLf & "                showLoader(false)"
    response.write vbCrLf & "                return res.json()"
    response.write vbCrLf & "            }).then(data=>{"
    response.write vbCrLf & "                const drugList = document.getElementById('rack-list');"
    response.write vbCrLf & "                const count = document.getElementById('count');"
    response.write vbCrLf & "                drugList.innerHTML = '';"
    response.write vbCrLf & "                count.textContent = data.length??0;"
    response.write vbCrLf & "                if(data.length>0){"
    response.write vbCrLf & "                    for(const obj of data){"
    response.write vbCrLf & "                        const itemContainer = tableTemplate.content.cloneNode(true).querySelector('tr');"
    response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{drug-id}"",obj['drugid'])"
    response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{drug-name}"",obj['drugname']);"
    response.write vbCrLf & "                        const editBtn = itemContainer.querySelector('#edit');"
    response.write vbCrLf & "                        editBtn.onclick = function edit(){"
    response.write vbCrLf & "                            deleteDrug(obj['drugid'])"
    response.write vbCrLf & "                        }"
    response.write vbCrLf & "                        drugList.appendChild(itemContainer);"
    response.write vbCrLf & "                    }"
    response.write vbCrLf & "                }else{"
    response.write vbCrLf & "                    drugList.innerHTML = '<tr><td colspan=""100"">No " & itemtype & " Added</td></tr>'"
    response.write vbCrLf & "                }"
    response.write vbCrLf & "            }).catch(e=>console.log(e))"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function searchDrug(el){"
    response.write vbCrLf & "            const sn = el.value;"
    response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=Rack&operation=SEARCHDRUG&rack-id=' + rackId;"
    response.write vbCrLf & "            endpoint += '&store=' + store;"
    response.write vbCrLf & "            endpoint += '&tbl=' + tbl;"
    response.write vbCrLf & "            if(sn.length>2){"
    response.write vbCrLf & "                endpoint += '&sn=' + sn;"
    response.write vbCrLf & "                controller.abort();"
    response.write vbCrLf & "                controller = new AbortController();"
    response.write vbCrLf & "                const signal = controller.signal;"
    response.write vbCrLf & "                const searchList = document.querySelector('.search-box>ul')"
    response.write vbCrLf & "                fetch(endpoint,{signal}).then(res=>res.json()).then(data=>{"
    response.write vbCrLf & "                    searchList.innerHTML = '';"
    response.write vbCrLf & "                    if(data.length>0){"
    response.write vbCrLf & "                        for(const obj of data){"
    response.write vbCrLf & "                            const li = searchElementTemplate.content.cloneNode(true).querySelector('li');"
    response.write vbCrLf & "                            li.innerHTML = li.innerHTML.replace('{drug-name}',obj['drugname'])"
    response.write vbCrLf & "                            li.innerHTML = li.innerHTML.replace('{drug-id}',obj['drugid'])"
    response.write vbCrLf & "                            li.onclick = function(){"
    response.write vbCrLf & "                                const DrugID = document.getElementById('drugIDInp');"
    response.write vbCrLf & "                                if(DrugID) DrugID.value = obj['drugid'];"
    response.write vbCrLf & "                                const DrugName = document.getElementById('drugNameInp');"
    response.write vbCrLf & "                                if(DrugName) DrugName.value = obj['drugname'];"
    response.write vbCrLf & "                                searchList.innerHTML = ''"
    response.write vbCrLf & "                            }"
    response.write vbCrLf & "                            searchList.appendChild(li);"
    response.write vbCrLf & "                        }"
    response.write vbCrLf & "                    }else{"
    response.write vbCrLf & "                        searchList.innerHTML = '<li>No Result Found</li>'"
    response.write vbCrLf & "                    }"
    response.write vbCrLf & "                }).catch(e=>console.log(e))"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function addDrug(obj){"
    response.write vbCrLf & "            const dialogContainer = document.getElementById('dialog-container');"
    response.write vbCrLf & "            content.innerHTML = `<div id=""json-generatable"">"
    response.write vbCrLf & "                                    <label>"
    response.write vbCrLf & "                                        " & itemtype & " ID:"
    response.write vbCrLf & "                                        <input id=""drugIDInp"" style=""width: 100%;font-family: inherit;"" required disabled>"
    response.write vbCrLf & "                                        " & itemtype & " Name:"
    response.write vbCrLf & "                                        <div class=""search-box"">"
    response.write vbCrLf & "                                            <input oninput=""searchDrug(this)"" id=""drugNameInp"" style=""width: 100%;font-family: inherit;"">"
    response.write vbCrLf & "                                            <ul>"
    response.write vbCrLf & "                                            </ul>"
    response.write vbCrLf & "                                        </div>"
    response.write vbCrLf & "                                    </label>"
    response.write vbCrLf & "                                    <input type=""hidden"" id=""rack-id""/>"
    response.write vbCrLf & "                                </div>`;"
    response.write vbCrLf & "            dialogContainer.innerHTML = dialogContainer.innerHTML.replace('{dialog-name}',`Add " & itemtype & " To Rack`);"
    response.write vbCrLf & "            dialogContainer.classList.add('flex');"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function closeDialog(){"
    response.write vbCrLf & "            const dialogContainer = document.getElementById('dialog-container');"
    response.write vbCrLf & "            dialogContainer.classList.remove('flex')"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function deleteDrug(drugId){"
    response.write vbCrLf & "            let endpoint = ""wpgXMLHTTP.asp?procedurename=Rack&operation=DELETEDRUG&rack-id="" + rackId;"
    response.write vbCrLf & "            endpoint += '&store=' + store;"
    response.write vbCrLf & "            endpoint += '&tbl=' + tbl;"
    response.write vbCrLf & "            const ok = confirm(""delete " & itemtype & " from rack?"");"
    response.write vbCrLf & "            if(ok){"
    response.write vbCrLf & "                if(drugId == null || drugId == """"){"
    response.write vbCrLf & "                    return alert(""drug id can't be null"");"
    response.write vbCrLf & "                }"
    response.write vbCrLf & "                endpoint += '&drugid=' + drugId"
    response.write vbCrLf & "                showLoader(true)"
    response.write vbCrLf & "                fetch(endpoint).then(res=>{"
    response.write vbCrLf & "                    showLoader(false)"
    response.write vbCrLf & "                    return res.json();"
    response.write vbCrLf & "                }).then(data=>{"
    response.write vbCrLf & "                    if(data.success){"
    response.write vbCrLf & "                        closeDialog();"
    response.write vbCrLf & "                        alert(data.message);"
    response.write vbCrLf & "                        loadStaff();"
    response.write vbCrLf & "                        return;"
    response.write vbCrLf & "                    }"
    response.write vbCrLf & "                    alert(data.message);"
    response.write vbCrLf & "                }).catch(e=>{"
    response.write vbCrLf & "                    console.error(e);"
    response.write vbCrLf & "                })"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function submitDrug(e){"
    response.write vbCrLf & "            e.preventDefault();"
    response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=Rack&operation=ADDDRUG&rack-id=' + rackId;"
    response.write vbCrLf & "            endpoint += '&store=' + store;"
    response.write vbCrLf & "            endpoint += '&tbl=' + tbl;"
    response.write vbCrLf & "            const drugId = document.getElementById('drugIDInp')?.value;"
    response.write vbCrLf & "            if(drugId == null || drugId == '') return alert(""Drug Id not set!"");"
    response.write vbCrLf & "            endpoint += '&drugid=' + drugId;"
    response.write vbCrLf & "            showLoader(true)"
    response.write vbCrLf & "            fetch(endpoint).then(res=>{"
    response.write vbCrLf & "                showLoader(false)"
    response.write vbCrLf & "                return res.json();"
    response.write vbCrLf & "            }).then(data=>{"
    response.write vbCrLf & "                if(data.success){"
    response.write vbCrLf & "                    closeDialog();"
    response.write vbCrLf & "                    alert(data.message);"
    response.write vbCrLf & "                    loadStaff();"
    response.write vbCrLf & "                    return;"
    response.write vbCrLf & "                }"
    response.write vbCrLf & "                alert(data.message);"
    response.write vbCrLf & "            }).catch(e=>{"
    response.write vbCrLf & "                console.error(e);"
    response.write vbCrLf & "            })"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function proceed(){"
    response.write vbCrLf & "            const form = document.getElementById('content');"
    response.write vbCrLf & "            form.requestSubmit();"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "        function showLoader(bool){"
    response.write vbCrLf & "            const spinner = document.querySelector('.spinner-container');"
    response.write vbCrLf & "            if(bool){"
    response.write vbCrLf & "                spinner.classList.add('flex')"
    response.write vbCrLf & "            }else{"
    response.write vbCrLf & "                spinner.classList.remove('flex')"
    response.write vbCrLf & "            }"
    response.write vbCrLf & "        }"
    response.write vbCrLf & "    </script>"
    response.write vbCrLf & "    <div class=""spinner-container"">"
    response.write vbCrLf & "        <div class=""spinner"">"
    response.write vbCrLf & "        </div>"
    response.write vbCrLf & "    </div>"
    response.write vbCrLf & "</body>"
    response.write vbCrLf & "</html>"
    response.write vbCrLf & ""
    response.write vbCrLf & ""

End Sub
Sub LoadRacks()
    Dim rst
    Set rst = CreateObject("ADODB.RecordSet")
    sql = "SELECT * FROM Performvar22 WHERE KeyPrefix = '" & Trim(Request("store")) & "'"
    rst.open qryPro.FltQry(sql), conn, 3, 4

    response.write vbCrLf & "                <select id=""rack"">"
    response.write vbCrLf & "                    <option value></option>"
    If rst.recordCount > 0 Then
        rst.MoveFirst
        Do While Not rst.EOF
            response.write vbCrLf & "                    <option value='" & rst.fields("Performvar22ID") & "'>" & rst.fields("Performvar22Name") & "</option>"
            rst.MoveNext
        Loop
    End If
    response.write vbCrLf & "                </select>"
    rst.Close
    Set rst = Nothing
End Sub

Function indexOf(arr, searchElement)
    For i = 0 To UBound(arr)
        If arr(i) = searchElement Then
            indexOf = i
            Exit Function
        End If
    Next
    indexOf = -1
End Function


'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
