'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
response.Clear
response.write vbCrLf & "<html lang=""en"">"
response.write vbCrLf & "<head>"
response.write vbCrLf & "    <meta charset=""UTF-8"">"
response.write vbCrLf & "    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
response.write vbCrLf & "    <title>Document</title>"
response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.googleapis.com"">"
response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.gstatic.com"" crossorigin>"
response.write vbCrLf & "    <link href=""https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"" rel=""stylesheet"">"
response.write vbCrLf & "    <style>"
response.write vbCrLf & "        body{"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            padding: 0;"
response.write vbCrLf & "            margin: 0;"
response.write vbCrLf & "            font-size: 14px;"
response.write vbCrLf & "            font-family: 'Nunito',sans-serif;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .top-bar{"
response.write vbCrLf & "            background-color: white;"
response.write vbCrLf & "            padding: 10px 4rem 0 4rem;"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dynamic-content{"
response.write vbCrLf & "        }"
response.write vbCrLf & "        button{"
response.write vbCrLf & "            padding: 3px 15px;"
response.write vbCrLf & "            height: fit-content;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "            border: none;"
response.write vbCrLf & "            font-family: inherit;"
response.write vbCrLf & "            font-size: 13px;"
response.write vbCrLf & "            border-radius: 5px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .nav-link{"
response.write vbCrLf & "            list-style: none;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            padding: 0;"
response.write vbCrLf & "            margin: 0;"
response.write vbCrLf & "            cursor:pointer"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .nav-link li{"
response.write vbCrLf & "            padding:10px 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .nav-link-active{"
response.write vbCrLf & "            background-color: rgba(220, 220, 220,0.3);"
response.write vbCrLf & "            border-bottom: 3px solid #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dynamic-content{"
response.write vbCrLf & "            padding: 10px 4rem;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .h2{"
response.write vbCrLf & "            padding: 10px 12px;"
response.write vbCrLf & "            border: 1px solid gainsboro;"
response.write vbCrLf & "            background-color: white;"
response.write vbCrLf & "            border-radius: 10px;"
response.write vbCrLf & "            box-shadow: 0px 0px 5px 0px gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .h2-h3{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            justify-content: space-between;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .rack-table{"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            border-collapse: collapse;"
response.write vbCrLf & "            border-spacing: 0;"
response.write vbCrLf & "            border-radius: 3px;"
response.write vbCrLf & "            contain: paint;"
response.write vbCrLf & "            border: 1px solid grey;"
response.write vbCrLf & "            font-size: 13px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .rack-table thead{"
response.write vbCrLf & "            background-color: #accadd;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .rack-table tbody>:nth-child(even){"
response.write vbCrLf & "            background-color: rgb(235, 234, 234);"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .rack-table th,.rack-table td{"
response.write vbCrLf & "            padding: 8px 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .rack-table td{"
response.write vbCrLf & "            text-align: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .status{"
response.write vbCrLf & "            padding: 4px 10px;"
response.write vbCrLf & "            border-radius: 10px;"
response.write vbCrLf & "            background-color: forestgreen;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .action-cs{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            place-items: center;"
response.write vbCrLf & "            place-content: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .action-cs label{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            place-items: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dialog-container{"
response.write vbCrLf & "            position: fixed;"
response.write vbCrLf & "            top: 0;"
response.write vbCrLf & "            left: 0;"
response.write vbCrLf & "            right: 0;"
response.write vbCrLf & "            bottom: 0;"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            height: 100vh;"
response.write vbCrLf & "            z-index: 1000;"
response.write vbCrLf & "            display: none;"
response.write vbCrLf & "            background-color: rgba(55, 55, 55,0.8);"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .flex{"
response.write vbCrLf & "            display: flex !important;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dialog{"
response.write vbCrLf & "            margin: 10vh auto 0 auto;"
response.write vbCrLf & "            border: none;"
response.write vbCrLf & "            width: 500px;"
response.write vbCrLf & "            min-height: 100px;"
response.write vbCrLf & "            border-radius: 5px;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            flex-direction: column;"
response.write vbCrLf & "            box-shadow: 0 0 10px 1px gray;"
response.write vbCrLf & "            padding: 0;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dialog-head{"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "            padding: 10px 15px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dialog-action{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            justify-content: flex-end;"
response.write vbCrLf & "            gap: 5px;"
response.write vbCrLf & "            padding: 7px 15px;"
response.write vbCrLf & "            border-top: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .content{"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            padding: 10px 15px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .spinner-container{"
response.write vbCrLf & "            position: fixed;"
response.write vbCrLf & "            top: 0;"
response.write vbCrLf & "            left: 0;"
response.write vbCrLf & "            right: 0;"
response.write vbCrLf & "            bottom: 0;"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            background-color: rgba(55, 55, 55,0.8);"
response.write vbCrLf & "            display: none;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "            z-index: 100000000;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .view{"
response.write vbCrLf & "            padding: 5px;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "            background-color: burlywood;"
response.write vbCrLf & "            border-radius: 2px;"
response.write vbCrLf & "            text-decoration: none;"
response.write vbCrLf & "            margin-left: 7px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .spinner{"
response.write vbCrLf & "            width: 60px;"
response.write vbCrLf & "            height: 60px;"
response.write vbCrLf & "            background-color: transparent;"
response.write vbCrLf & "            border: 7px solid grey;"
response.write vbCrLf & "            border-top: 7px solid whitesmoke;"
response.write vbCrLf & "            border-radius: 50%;"
response.write vbCrLf & "            margin: 0 auto;"
response.write vbCrLf & "            animation: spin 0.9s ease infinite;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        @keyframes spin {"
response.write vbCrLf & "            to{"
response.write vbCrLf & "                rotate: 360deg;"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "    </style>"
response.write vbCrLf & "</head>"
response.write vbCrLf & "<body>"
response.write vbCrLf & "    <template id=""tableTemplate"">"
response.write vbCrLf & "        <tr>"
response.write vbCrLf & "            <td colspan=""3"" style=""text-align: left;"">{rack-name}</td>"
response.write vbCrLf & "            <td colspan=""1""><span class=""status"">{rack-status}</span></td>"
response.write vbCrLf & "            <td colspan=""1"">"
response.write vbCrLf & "                <div class=""action-cs"">"
response.write vbCrLf & "                    <button style=""background-color: #0078D4;"" id=""edit"">Edit</button>"
response.write vbCrLf & "                    <label>"
response.write vbCrLf & "                        <input type=""checkbox"" class=""disablebtn""/>"
response.write vbCrLf & "                        <span>disable</span>"
response.write vbCrLf & "                    </label>"
response.write vbCrLf & "                    <a class='view' href='wpgPrtPrintLayoutAll.asp?PrintLayoutName=RackValue&PositionForTableName=WorkingDay&WorkingDayID=&store={store}&tbl={tbl}&rack-id={rack-id}'>Add Item to Rck</a>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </td>"
response.write vbCrLf & "        </tr>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""dynamicContentTemplate"">"
response.write vbCrLf & "        <div class=""h2"">"
response.write vbCrLf & "            <input type=""hidden"" id=""content-name"" value=""{content-name}""/>"
response.write vbCrLf & "            <div class=""h2-h3"">"
response.write vbCrLf & "                <h4 style=""margin: 10px 0;"">Rack Location</h4>"
response.write vbCrLf & "                <button style=""background-color: forestgreen;"" onclick=""addRack()"">Add</button>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <table width=""100%"" class=""rack-table"">"
response.write vbCrLf & "                <thead>"
response.write vbCrLf & "                    <tr>"
response.write vbCrLf & "                        <th colspan=""3"" align=""left"">Rack Name</th>"
response.write vbCrLf & "                        <th colspan=""1"">Status</th>"
response.write vbCrLf & "                        <th colspan=""1"">Action</th>"
response.write vbCrLf & "                    </tr>"
response.write vbCrLf & "                </thead>"
response.write vbCrLf & "                <tbody id=""rack-list"">"
response.write vbCrLf & "                </tbody>"
response.write vbCrLf & "            </table>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <main>"
response.write vbCrLf & "        <div class=""top-bar"">"
response.write vbCrLf & "            <h3>Rack Management</h3>"
response.write vbCrLf & "            <ul class=""nav-link"">"
response.write vbCrLf & "                <li class=""nav-link-active"" data-tab-name=""S20"">General Stores</li>"
response.write vbCrLf & "                <li data-tab-name=""S21"">Medical Stores</li>"
response.write vbCrLf & "                <li data-tab-name=""S22A"">IPD Pharmacy Store</li>"
response.write vbCrLf & "                <li data-tab-name=""S22"">OPD Pharmacy Store</li>"
response.write vbCrLf & "            </ul>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "        <div class=""dynamic-content"" id=""dynamic-content"">"
response.write vbCrLf & "            "
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </main>"
response.write vbCrLf & "    <template id=""dialogContent"">"
response.write vbCrLf & "        <div id=""json-generatable"">"
response.write vbCrLf & "            <label>"
response.write vbCrLf & "                Shelf:"
response.write vbCrLf & "                <input style=""width: 100%;"" type=""text"" data-field-name=""name"" id=""nameInp"" required/>"
response.write vbCrLf & "            </label>"
response.write vbCrLf & "            <label>"
response.write vbCrLf & "                Rack:"
response.write vbCrLf & "                <input style=""width: 100%;"" type=""text"" data-field-name=""name"" id=""parentInp"" required/>"
response.write vbCrLf & "            </label>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <div class=""dialog-container"" id=""dialog-container"">"
response.write vbCrLf & "        <dialog class=""dialog"">"
response.write vbCrLf & "            <div class=""dialog-head"">"
response.write vbCrLf & "                <span>{dialog-name}</span>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <form id=""content"" class=""content"" onsubmit=""submitRack(event)"">"
response.write vbCrLf & "            </form>"
response.write vbCrLf & "            <div class=""dialog-action"">"
response.write vbCrLf & "                <button style=""background-color: #FF5739;"" onclick=""closeDialog()"">cancel</button>"
response.write vbCrLf & "                <button style=""background-color: forestgreen;"" onclick=""proceed()"">proceed</button>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "        </dialog>"
response.write vbCrLf & "    </div>"
response.write vbCrLf & "    <script>"
response.write vbCrLf & "        window.addEventListener('load',function(){"
response.write vbCrLf & "            const links  = document.querySelectorAll('.nav-link>li');"
response.write vbCrLf & "            const active = document.querySelector('.nav-link-active');"
response.write vbCrLf & "            links.forEach(el=>{"
response.write vbCrLf & "                if(el.dataset.tabName){"
response.write vbCrLf & "                    el.onclick = function click(){"
response.write vbCrLf & "                        const active = document.querySelector('.nav-link-active');"
response.write vbCrLf & "                        if(active) active.classList.remove('nav-link-active');"
response.write vbCrLf & "                        loadStoreRacks(el.dataset.tabName);"
response.write vbCrLf & "                        el.classList.add('nav-link-active')"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "            })"
response.write vbCrLf & "            active.dispatchEvent(new Event('click'))"
response.write vbCrLf & "        })"
response.write vbCrLf & "        function loadStoreRacks(mode){"
response.write vbCrLf & "            const contentLoader = document.getElementById('dynamic-content');"
response.write vbCrLf & "            contentLoader.innerHTML = '';"
response.write vbCrLf & "            const templateContent = dynamicContentTemplate.content.cloneNode(true).querySelector('.h2');"
response.write vbCrLf & "            templateContent.innerHTML = templateContent.innerHTML.replace('{content-name}',mode)"
response.write vbCrLf & "            contentLoader.appendChild(templateContent);"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=Rack&operation=LOADRACKS&store=' + mode;"
response.write vbCrLf & "            showLoader(true)"
response.write vbCrLf & "            fetch(endpoint).then(res=>{"
response.write vbCrLf & "                showLoader(false)"
response.write vbCrLf & "                return res.json()"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                const rackList = document.getElementById('rack-list');"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    for(const obj of data){"
response.write vbCrLf & "                        const itemContainer = tableTemplate.content.cloneNode(true).querySelector('tr');"
response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{rack-name}"",obj['rackname'])"
response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{rack-status}"",obj['rackstatus']);"
response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{store}"",mode);"
response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{tbl}"",mode);"
response.write vbCrLf & "                        itemContainer.innerHTML = itemContainer.innerHTML.replace(""{rack-id}"",obj['rackid']);"
response.write vbCrLf & "                        const editBtn = itemContainer.querySelector('#edit');"
response.write vbCrLf & "                        const checkbtn = itemContainer.querySelector('.disablebtn');"
response.write vbCrLf & "                        const statusSpan = itemContainer.querySelector('.status');"
response.write vbCrLf & "                        if(obj['rackstatus']?.toUpperCase() === ""DISABLED""){"
response.write vbCrLf & "                            statusSpan.style.backgroundColor = '#FF5739';"
response.write vbCrLf & "                            checkbtn.checked = true;"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        checkbtn.onchange = function disable(){"
response.write vbCrLf & "                            let endpoint = 'wpgXMLHTTP.asp?procedurename=Rack&operation=CHANGESTATUS'"
response.write vbCrLf & "                            endpoint += '&rack-id=' + obj.rackid;"
response.write vbCrLf & "                            endpoint += '&store=' + mode;"
response.write vbCrLf & "                            endpoint += '&status=' + (checkbtn.checked?'disabled':'active');"
response.write vbCrLf & "                            fetch(endpoint).then(res=>{"
response.write vbCrLf & "                                return res.json()"
response.write vbCrLf & "                            }).then(data=>{"
response.write vbCrLf & "                                if(data.success){"
response.write vbCrLf & "                                    alert(data.message)"
response.write vbCrLf & "                                    const active = document.querySelector('.nav-link-active');"
response.write vbCrLf & "                                    active.dispatchEvent(new Event('click'));"
response.write vbCrLf & "                                }"
response.write vbCrLf & "                            }).catch(e=>console.error(e))"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        editBtn.onclick = function edit(){"
response.write vbCrLf & "                            addRack(obj.rackid)"
response.write vbCrLf & "                            const nameInp = document.getElementById('nameInp');"
response.write vbCrLf & "                            nameInp.value = obj.rackname;"
response.write vbCrLf & "                            parentInp.value = obj.parent ?? '';"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        rackList.appendChild(itemContainer);"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    rackList.innerHTML = '<tr><td colspan=""100"">No Rack Found</td></tr>'"
response.write vbCrLf & "                }"
response.write vbCrLf & "            })"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function addRack(id){"
response.write vbCrLf & "            const contentName = document.getElementById('content-name')?.value;"
response.write vbCrLf & "            const dialogContainer = document.getElementById('dialog-container');"
response.write vbCrLf & "            const rackId = document.getElementById('rack-id');"
response.write vbCrLf & "            if(contentName){"
response.write vbCrLf & "                const templateContent = dialogContent.content.cloneNode(true).querySelector('#json-generatable');"
response.write vbCrLf & "                if(id){"
response.write vbCrLf & "                    const input = document.createElement('input');"
response.write vbCrLf & "                    input.type = 'hidden';"
response.write vbCrLf & "                    input.id = 'rack-id';"
response.write vbCrLf & "                    input.value = id;"
response.write vbCrLf & "                    templateContent.appendChild(input);"
response.write vbCrLf & "                }"
response.write vbCrLf & "                content.innerHTML = '';"
response.write vbCrLf & "                content.appendChild(templateContent);"
response.write vbCrLf & "                if(contentName?.toUpperCase()===""S21""){"
response.write vbCrLf & "                    dialogContainer.innerHTML = dialogContainer.innerHTML.replace('{dialog-name}','Add Rack to Medical Store');"
response.write vbCrLf & "                } else if(contentName?.toUpperCase()===""S20""){"
response.write vbCrLf & "                    dialogContainer.innerHTML = dialogContainer.innerHTML.replace('{dialog-name}','Add Rack to General Store');"
response.write vbCrLf & "                } else if(contentName?.toUpperCase()===""S22A""){"
response.write vbCrLf & "                    dialogContainer.innerHTML = dialogContainer.innerHTML.replace('{dialog-name}','Add Rack to IPD Pharmacy Store');"
response.write vbCrLf & "                } else if(contentName?.toUpperCase()===""S22""){"
response.write vbCrLf & "                    dialogContainer.innerHTML = dialogContainer.innerHTML.replace('{dialog-name}','Add Rack to OPD Pharmacy Store');"
response.write vbCrLf & "                } "
response.write vbCrLf & "                dialogContainer.classList.add('flex');"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function closeDialog(){"
response.write vbCrLf & "            const dialogContainer = document.getElementById('dialog-container');"
response.write vbCrLf & "            dialogContainer.classList.remove('flex')"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function buildJSON(){"
response.write vbCrLf & "            const json = {}"
response.write vbCrLf & "            const name = document.getElementById('nameInp')?.value;"
response.write vbCrLf & "            if(name) json.rackname = name;"
response.write vbCrLf & "            const parent = document.getElementById('parentInp')?.value;"
response.write vbCrLf & "            if(parent) json.parent = parent;"
response.write vbCrLf & "            const id = document.getElementById('rack-id')?.value;"
response.write vbCrLf & "            if(id) json.rackid = id;"
response.write vbCrLf & "            const contentName = document.getElementById('content-name')?.value;"
response.write vbCrLf & "            if(contentName) json.store = contentName;"
response.write vbCrLf & "            return json;"
response.write vbCrLf & ""
response.write vbCrLf & "        }"
response.write vbCrLf & "        function submitRack(e){"
response.write vbCrLf & "            e.preventDefault();"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=Rack&operation=ADDRACK'"
response.write vbCrLf & "            const json = buildJSON();"
response.write vbCrLf & "            if(json){"
response.write vbCrLf & "                showLoader(true)"
response.write vbCrLf & "                fetch(endpoint,{"
response.write vbCrLf & "                    method:'POST',"
response.write vbCrLf & "                    body:JSON.stringify(json)"
response.write vbCrLf & "                }).then(res=>{"
response.write vbCrLf & "                    showLoader(false)"
response.write vbCrLf & "                    return res.json();"
response.write vbCrLf & "                }).then(data=>{"
response.write vbCrLf & "                    if(data.success){"
response.write vbCrLf & "                        closeDialog();"
response.write vbCrLf & "                        alert(data.message);"
response.write vbCrLf & "                        const active = document.querySelector('.nav-link-active');"
response.write vbCrLf & "                        active.dispatchEvent(new Event('click'));"
response.write vbCrLf & "                        return;"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                    alert(data.message);"
response.write vbCrLf & "                }).catch(e=>{"
response.write vbCrLf & "                    console.error(e);"
response.write vbCrLf & "                })"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function proceed(){"
response.write vbCrLf & "            const form = document.getElementById('content');"
response.write vbCrLf & "            form.requestSubmit();"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function showLoader(bool){"
response.write vbCrLf & "            const spinner = document.querySelector('.spinner-container');"
response.write vbCrLf & "            if(bool){"
response.write vbCrLf & "                spinner.classList.add('flex')"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                spinner.classList.remove('flex')"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "    </script>"
response.write vbCrLf & "    <div class=""spinner-container"">"
response.write vbCrLf & "        <div class=""spinner"">"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </div>"
response.write vbCrLf & "</body>"
response.write vbCrLf & "</html>"









'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
