'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>

If Trim(UCase(jSchd)) = "M0601" Or Trim(UCase(jSchd)) = "M0602" Or Trim(UCase(jSchd)) = "M0603" Then
    jSchd = "S22"
ElseIf Trim(UCase(jSchd)) = "M0601A" Or Trim(UCase(jSchd)) = "M0602A" Or Trim(UCase(jSchd)) = "M0603A" Then
    jSchd = "S22A"
End If

JobSchedule = Trim(jSchd)
response.write "<link rel='preconnect' href='https://fonts.googleapis.com'>"
response.write "<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>"
response.write "<link href='https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap' rel='stylesheet'>"

Dim rst, expiryDate
Set rst = CreateObject("ADODB.Recordset")
sqlItem = "SELECT distinct ds.ItemID,ds.AvailableQty FROM ItemStockLevel as ds FULL JOIN IncomingStockItems AS di ON ds.ItemID = di.ItemID "
sqlItem = sqlItem & "WHERE ds.itemstoreid = '" & JobSchedule & "' AND ds.AvailableQty > 0 "

sqlDrug = "SELECT distinct ds.DrugID,ds.AvailableQty FROM DrugStockLevel as ds FULL JOIN IncomingDrugItems AS di ON ds.DrugID = di.DrugID "
sqlDrug = sqlDrug & "WHERE ds.drugstoreid = '" & JobSchedule & "' AND ds.AvailableQty > 0 "


css = "<style>"
css = css & ".consumption {"
css = css & "position: relative;"
css = css & "width: fit-content;"
css = css & "min-width:900px;"
css = css & "}"
css = css & ".expiry-table {"
css = css & "font-family: 'Manrope', sans-serif;"
css = css & "width: auto;"
css = css & "position: relative;"
css = css & "contain: paint;"
css = css & "border-collapse: collapse;"
css = css & "}"
css = css & ".expiry-table th, .expiry-table td {"
css = css & "padding: 10px 20px;"
css = css & "text-align: center;"
css = css & "border: 1px solid gainsboro;"
css = css & "}"
css = css & ".expiry-table thead {"
css = css & "position: sticky;"
css = css & "top: 0;"
css = css & "background-color: #CED5DF;"
css = css & "}"
css = css & ".expiry-table tbody>:nth-child(odd) {"
css = css & "background-color: #F8F9FB;"
css = css & "}"
css = css & ".expiry-table tbody>:nth-child(even) {"
css = css & "background-color: #F1F4FD;"
css = css & "}"
css = css & ".dialog-container {"
css = css & "font-family: 'Manrope', sans-serif;"
css = css & "position: fixed;"
css = css & "top: 0;"
css = css & "left: 0;"
css = css & "bottom: 0;"
css = css & "right: 0;"
css = css & "display: none;"
css = css & "justify-content: center;"
css = css & "align-items: center;"
css = css & "background-color: rgba(0,0,0,0.6);"
css = css & "z-index: 10000;"
css = css & "}"
css = css & ".dialog {"
css = css & "background-color: white;"
css = css & "padding: 0 15px 20px 15px;"
css = css & "border: 1px solid gainsboro;"
css = css & "border-radius: 10px;"
css = css & "display: grid;"
css = css & "gap: 5px;"
css = css & "animation: open 0.5s ease;"
css = css & "}"
css = css & ".svg {"
css = css & "position: absolute;"
css = css & "padding: 10px;"
css = css & "border-radius: 50%;"
css = css & "top: 30px;"
css = css & "background-color: rgba(255,255,255,0.5);"
css = css & "}"
css = css & ".dialog input {"
css = css & "font-family: 'Manrope', sans-serif;"
css = css & "border: 2px solid gray;"
css = css & "}"
css = css & "#general, #drug {"
css = css & "position: absolute;"
css = css & "top: 0;"
css = css & "left: 0;"
css = css & "width: fit-content;"
css = css & "transition: all 0.7s ease;"
css = css & "font-family: 'Manrope', sans-serif;"
css = css & "display: grid;"
css = css & "max-width: 1000px;"
css = css & "}"
css = css & "#general-child,#drug-child{"
css = css & "border-radius: 10px;"
css = css & "background-color: #0078D4;"
css = css & "contain: paint;"
css = css & "display: grid;"
css = css & "border: 2px solid gainsboro;"
css = css & "}"
css = css & ".active {"
css = css & "z-index:1000;"
css = css & "}"
css = css & ".not-active {"
css = css & "transform: translate(100px, 80px);"
css = css & "z-index: 100;"
css = css & "opacity:0.2;"
css = css & "}"
css = css & "@keyframes show {"
css = css & "from {"
css = css & "width: 0;"
css = css & "}"
css = css & "}"
css = css & "@keyframes open {"
css = css & "from {"
css = css & "transform: translateY(50px);"
css = css & "opacity: 0.6;"
css = css & "}"
css = css & "}"
css = css & "</style>"

response.write css
response.write "<div class='dialog-container'></div>"
response.write "<div class='consumption'>"
response.write "<div onclick='makeDrugActive()' id='drug'>"
response.write "<div style='width: 100%;display: flex; justify-content: end'><button style='background-color: forestgreen; color: white; border: none; border-radius: 10px; padding: 10px 20px;  font-size: 0.9rem; margin:30px 0' onclick=""multipush()"">Consume Multiple Items</button></div>"
response.write "<div id='drug-child' >"
response.write "<span style='text-align: center;color: white;padding: 10px;font-size: 1.2rem;font-weight: bold'>DRUGSTORE STOCK</span>"

response.write "<table class='expiry-table'>"
response.write "<thead>"
response.write "<tr>"
response.write "<th>DRUG ID</th>"
response.write "<th>DRUG NAME</th>"
response.write "<th>AVAILABLE QUANTITY</th>"

response.write "<th>ADJUSTMENT</th>"
response.write "<th>ACTION</th>"
response.write "</tr>"
response.write "</thead>"
response.write "<tbody>"
rst.open qryPro.FltQry(sqlDrug), conn, 3, 4
If rst.recordCount > 0 Then
    rst.movefirst
    Do While Not rst.EOF
        response.write "<tr>"
        response.write "<td>" & rst.fields("DrugID") & "</td>"
        response.write "<td id='DRG-NAME-" & rst.fields("DrugID") & "'>" & GetComboName("Drug", rst.fields("DrugID")) & "</td>"
        response.write "<td id='DRG-QTY-" & rst.fields("DrugID") & "'>" & rst.fields("AvailableQty") & "</td>"

        response.write "<td><input id='ADJUST-VALUE-DRG-" & rst.fields("DrugID") & "' style='width: 100px; height: 25px; padding: 0; text-align: center; font-size: 0.9rem; border-radius: 10px' type='number' min='1'></td>"
        response.write "<td><button onclick='change(event)' id='" & rst.fields("DrugID") & "' style='background-color: forestgreen; color: white; border: none; border-radius: 10px; padding: 0px 20px; height: 30px; font-size: 0.9rem'>Consume</button></td>"
        response.write "</tr>"
        response.Flush
        rst.MoveNext
    Loop
End If
rst.Close
response.write "</tbody>"
response.write "</table>"
response.write "</div>"
response.write "</div>"

response.write "<div onclick='makeGeneralActive()' id='general'>"
response.write "<div style='width: 100%;display: flex; justify-content: end'><button style='background-color: #d9534f; color: white; border: none; border-radius: 10px; padding: 10px 20px;  font-size: 0.9rem; margin:30px 0' onclick=""multipushitem()"">Consume Multiple Items</button></div>"
response.write "<div id='general-child' >"
response.write "<span style='text-align: center;color: white;padding: 10px;font-size: 1.2rem;font-weight: bold'>GENERAL STORES STOCK</span>"
response.write "<table class='expiry-table'>"
response.write "<thead>"
response.write "<tr>"
response.write "<th>ITEM ID</th>"
response.write "<th>ITEM NAME</th>"
response.write "<th>AVAILABLE QUANTITY</th>"
response.write "<th>ADJUSTMENT</th>"
response.write "<th>ACTION</th>"
response.write "</tr>"
response.write "</thead>"
response.write "<tbody>"
rst.open qryPro.FltQry(sqlItem), conn, 3, 4
If rst.recordCount > 0 Then
    rst.movefirst
    Do While Not rst.EOF
        response.write "<tr>"
        response.write "<td>" & rst.fields("ItemID") & "</td>"
        response.write "<td id='ITM-NAME-" & rst.fields("ItemID") & "'>" & GetComboName("Items", rst.fields("ItemID")) & "</td>"
        response.write "<td id='ITM-QTY-" & rst.fields("itemID") & "'>" & rst.fields("AvailableQty") & "</td>"

        response.write "<td><input id='ADJUST-VALUE-ITM-" & rst.fields("ItemID") & "' style='width: 100px; height: 25px; padding: 0; text-align: center; font-size: 0.9rem; border-radius: 10px' type='number' min='1'></td>"
        response.write "<td><button onclick='changeItem(event)' id='" & rst.fields("ItemID") & "' style='background-color: #d9534f; color: white; border: none; border-radius: 10px; padding: 0px 20px; height: 30px; font-size: 0.9rem'>Consume</button></td>"
        response.write "</tr>"
        response.Flush
        rst.MoveNext
    Loop
End If
rst.Close
response.write "</tbody>"
response.write "</table>"

response.write "</div>"
response.write "</div>"
response.write "</div>"

response.write "<script>"
response.write "const drugAdjustment = {};"
response.write "const drugContainer = document.querySelector('#drug'); "
response.write "const generalContainer = document.querySelector('#general'); "
response.write "if(drugContainer.getBoundingClientRect().width>generalContainer.getBoundingClientRect().width){ "
response.write "generalContainer.style.width = `${drugContainer.getBoundingClientRect().width}px`; "
response.write "}else{ "
response.write "drugContainer.style.width = `${generalContainer.getBoundingClientRect().width}px`; "
response.write "}; "
response.write "drugContainer.classList.add('active'); "
response.write "generalContainer.classList.add('not-active'); "
response.write "generalContainer.querySelector('.expiry-table').style.pointerEvents = 'none'; "
response.write "function makeGeneralActive() { "
response.write "drugContainer.querySelector('.expiry-table').style.pointerEvents = 'none'; "
response.write "generalContainer.querySelector('.expiry-table').style.pointerEvents = ''; "
response.write "generalContainer.querySelector('.expiry-table thead').style.position = 'sticky'; "
response.write "drugContainer.querySelector('.expiry-table thead').style.position = 'unset'; "
response.write "drugContainer.classList.remove('active'); "
response.write "drugContainer.classList.add('not-active'); "
response.write "generalContainer.classList.remove('not-active'); "
response.write "generalContainer.classList.add('active'); "
response.write "}; "
response.write "function multipush() {"

response.write "document.querySelectorAll('input[id^=""ADJUST-VALUE-DRG-""]').forEach(input => {"
response.write "const inputedValue = input.value;"
response.write "if(inputedValue && inputedValue !== '') {"
response.write "const id = input.id.slice('ADJUST-VALUE-DRG-'.length);"
response.write "drugAdjustment[id] = {"
response.write "adjustQty: parseFloat(inputedValue),"
response.write "availableQty: parseFloat(document.querySelector('#DRG-QTY-' + id).innerText)"
response.write "};"
response.write "}"
response.write "});"
response.write "const container = document.querySelector('.dialog-container');"
response.write "container.style.display = 'flex';"
response.write "container.innerHTML = `<div class='svg' onclick='closeDiv()'>"
response.write "<svg style='display: block; text-align: center' width='30px' height='30px' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'>"
response.write "<g id='Menu / Close_MD'>"
response.write "<path id='Vector' d='M18 18L12 12M12 12L6 6M12 12L18 6M12 12L6 18' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/>"
response.write "</g></svg></div>"
response.write "<div class='dialog'>"
response.write "<h3>Confirmation</h3>"
response.write "<p style='font-size: 1rem'>You are about to reduce the stock level of the following </p>"
response.write "<table style='width:100%;max-height:200px;overflow-y:scroll;'>"
response.write "${Object.keys(drugAdjustment).map(value => `<tr><td>${value}</td><td>${document.querySelector('#DRG-NAME-' + value).innerText}</td><td>${drugAdjustment[value].adjustQty}</td></tr>`).join("" "")}"
response.write "</table>"
response.write "<button onclick=""confirmQuantityMultiple(drugAdjustment)"" style='justify-self:right; background-color: #ff4400;width: fit-content;padding: 7px 10px;color: white; border: none; border-radius: 6px;font-size: 0.9rem; font-family: Manrope, sans-serif;margin-top: 10px'>Confirm</button>"
response.write "</div>`;"
response.write "};"
response.write "function multipushitem() {"
response.write "document.querySelectorAll('input[id^=""ADJUST-VALUE-ITM-""]').forEach(input => {"
response.write "const inputedValue = input.value;"
response.write "if(inputedValue && inputedValue !== '') {"
response.write "const id = input.id.slice('ADJUST-VALUE-ITM-'.length);"
response.write "drugAdjustment[id] = {"
response.write "adjustQty: parseFloat(inputedValue),"
response.write "availableQty: parseFloat(document.querySelector('#ITM-QTY-' + id).innerText)"
response.write "};"
response.write "}"
response.write "});"
response.write "const container = document.querySelector('.dialog-container');"
response.write "container.style.display = 'flex';"
response.write "container.innerHTML = `<div class='svg' onclick='closeDiv()'>"
response.write "<svg style='display: block; text-align: center' width='30px' height='30px' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'>"
response.write "<g id='Menu / Close_MD'>"
response.write "<path id='Vector' d='M18 18L12 12M12 12L6 6M12 12L18 6M12 12L6 18' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/>"
response.write "</g></svg></div>"
response.write "<div class='dialog'>"
response.write "<h3>Confirmation</h3>"
response.write "<p style='font-size: 1rem'>You are about to reduce the stock level of the following </p>"
response.write "<table style='width:100%;max-height:200px;overflow-y:scroll;'>"
response.write "${Object.keys(drugAdjustment).map(value => `<tr><td>${value}</td><td>${document.querySelector('#ITM-NAME-' + value).innerText}</td><td>${drugAdjustment[value].adjustQty}</td></tr>`).join("" "")}"
response.write "</table>"
response.write "<button onclick=""confirmQuantityMultipleItem(drugAdjustment)"" style='justify-self:right; background-color: #ff4400;width: fit-content;padding: 7px 10px;color: white; border: none; border-radius: 6px;font-size: 0.9rem; font-family: Manrope, sans-serif;margin-top: 10px'>Confirm</button>"
response.write "</div>`;"
response.write "};"
response.write "function confirmQuantityMultiple(data) {"
response.write "console.log('here'); "
response.write "Object.keys(drugAdjustment).forEach(value => {"
response.write "const drugID = value;"
response.write "let url = 'wpgXMLHttp.asp?ProcedureName=adjustExpiredStock&drugid=' + drugID + '&storeid=" & JobSchedule & "' + '&qty=' + (parseFloat(drugAdjustment[value].availableQty) - parseFloat(drugAdjustment[value].adjustQty || 0)) + '&newStock=';"
response.write "console.log(url); "
response.write "fetch(url)"
response.write ".then(response => response.json())"
response.write ".then(data => {closeDiv();location.reload();})"
response.write ".catch(err => console.log(err));"
response.write "})"
response.write "};"
response.write "function confirmQuantityMultipleItem(data) {"
response.write "console.log('here'); "
response.write "console.log(data); "
response.write "Object.keys(drugAdjustment).forEach(value => {"
response.write "const drugID = value;"
response.write "let url = 'wpgXMLHttp.asp?ProcedureName=AddItemAdjustment&itemid=' + drugID + '&storeid=" & JobSchedule & "' + '&newqty=' + (parseFloat(drugAdjustment[value].availableQty) - parseFloat(drugAdjustment[value].adjustQty || 0)) + '&newStock=';"
response.write "console.log(url); "
response.write "fetch(url)"
response.write ".then(response => response.json())"
response.write ".then(data => {closeDiv();location.reload();})"
response.write ".catch(err => console.log(err));"
response.write "})"
response.write "};"
response.write "function makeDrugActive() { "
response.write "drugContainer.querySelector('.expiry-table').style.pointerEvents = ''; "
response.write "generalContainer.querySelector('.expiry-table').style.pointerEvents = 'none'; "
response.write "generalContainer.querySelector('.expiry-table thead').style.position = 'unset'; "
response.write "drugContainer.querySelector('.expiry-table thead').style.position = 'sticky'; "
response.write "generalContainer.classList.remove('active'); "
response.write "generalContainer.classList.add('not-active'); "
response.write "drugContainer.classList.remove('not-active'); "
response.write "drugContainer.classList.add('active'); "
response.write "}; "
response.write "function change(e) {"
response.write "const drugID = e.target.id; "
response.write "const container = document.querySelector('.dialog-container'); "
response.write "const adjustValue = e.target.parentNode.parentNode.querySelector(`#ADJUST-VALUE-DRG-${drugID}`).value; "
response.write "const drugName = e.target.parentNode.parentNode.querySelector(`#DRG-NAME-${drugID}`).innerText.trim(); "
response.write "const availQty = e.target.parentNode.parentNode.querySelector(`#DRG-QTY-${drugID}`).innerText.trim(); "
response.write "container.style.display = 'flex'; "
response.write "container.innerHTML = `<div class='svg' onclick='closeDiv()'>"
response.write "<svg  style='display: block; text-align: center' width='30px' height='30px' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'>"
response.write "<g id='Menu / Close_MD'>"
response.write "<path id='Vector' d='M18 18L12 12M12 12L6 6M12 12L18 6M12 12L6 18' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/>"
response.write "</g></svg></div>"
response.write "<div class='dialog'>"
response.write "<h3>Confirmation</h3>"
response.write "<h3 id=""AVQ-${drugID}"" style='display:none'>${availQty}</h3>"
response.write "<p style='font-size: 1rem'>You are about to reduce the stock level of <b id=""NAME-${drugID}"">${drugName}</b> by </p>"
response.write "<span style='font-size: 4rem;'><span id=""QTY-${drugID}"" style='color: #ff4400;font-weight: bold'>${adjustValue||0}</span></span>"
response.write "<button onclick='confirmQuantityChange(""${drugID}"")' style='justify-self:right; background-color: #ff4400;width: fit-content;padding: 7px 10px;color: white; border: none; border-radius: 6px;font-size: 0.9rem; font-family: Manrope, sans-serif;margin-top: 10px'>Confirm</button>"
response.write "</div>`;"
response.write "};  "
response.write "function changeItem(e) {"
response.write "const drugID = e.target.id; "
response.write "const container = document.querySelector('.dialog-container'); "
response.write "const adjustValue = e.target.parentNode.parentNode.querySelector(`#ADJUST-VALUE-ITM-${drugID}`).value; "
response.write "const drugName = e.target.parentNode.parentNode.querySelector(`#ITM-NAME-${drugID}`).innerText.trim(); "
response.write "const availQty = e.target.parentNode.parentNode.querySelector(`#ITM-QTY-${drugID}`).innerText.trim(); "
response.write "container.style.display = 'flex'; "
response.write "container.innerHTML = `<div class='svg' onclick='closeDiv()'>"
response.write "<svg  style='display: block; text-align: center' width='30px' height='30px' viewBox='0 0 24 24' fill='none' xmlns='http://www.w3.org/2000/svg'>"
response.write "<g id='Menu / Close_MD'>"
response.write "<path id='Vector' d='M18 18L12 12M12 12L6 6M12 12L18 6M12 12L6 18' stroke='white' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'/>"
response.write "</g></svg></div>"
response.write "<div class='dialog'>"
response.write "<h3>Confirmation</h3>"
response.write "<h3 id=""AVQ-${drugID}"" style='display:none'>${availQty}</h3>"
response.write "<p style='font-size: 1rem'>You are about to reduce the stock level of <b id=""NAME-${drugID}"" >${drugName}</b> by </p>"
response.write "<span style='font-size: 4rem;'><span id=""QTY-${drugID}"" style='color: #ff4400;font-weight: bold'>${adjustValue||0}</span></span>"
response.write "<button onclick='confirmQuantityChangeItem(""${drugID}"")' style='justify-self:right; background-color: #ff4400;width: fit-content;padding: 7px 10px;color: white; border: none; border-radius: 6px;font-size: 0.9rem; font-family: Manrope, sans-serif;margin-top: 10px'>Confirm</button>"
response.write "</div>`;"
response.write "};  "
response.write "function closeDiv() {"
response.write "const container = document.querySelector('.dialog-container');"
response.write "container.style.display = 'none';"
response.write "container.innerHTML = '';"
response.write "}; "
response.write "function confirmQuantityChange(drugID) {"
response.write "const adjustValue = document.querySelector('#QTY-' + drugID).innerText;"
response.write "const availableQuantity = document.querySelector('#AVQ-' + drugID).innerText;"

response.write "let url = 'wpgXMLHttp.asp?ProcedureName=adjustExpiredStock&drugid=' + drugID + '&storeid=" & JobSchedule & "' + '&qty=' + (parseFloat(availableQuantity) - parseFloat(adjustValue||0)) + '&newStock=';"
response.write "console.log(url); "
response.write "fetch(url)"
response.write ".then(response => response.json())"
response.write ".then(data => {closeDiv();location.reload();})"
response.write ".catch(err => console.log(err));"
response.write "}; "
response.write "function confirmQuantityChangeItem(drugID) {"
response.write "const adjustValue = document.querySelector('#QTY-' + drugID).innerText;"
response.write "const availableQuantity = document.querySelector('#AVQ-' + drugID).innerText;"

response.write "let url = 'wpgXMLHttp.asp?ProcedureName=AddItemAdjustment&itemid=' + drugID + '&storeid=" & JobSchedule & "' + '&newqty=' + (parseFloat(availableQuantity) - parseFloat(adjustValue||0)) + '&newStock=';"
response.write "console.log(url); "
response.write "fetch(url)"
response.write ".then(response => response.json())"
response.write ".then(data => {closeDiv();location.reload();})"
response.write ".catch(err => console.log(err));"
response.write "};"
response.write "</script>"



'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
