Dim sql
sql = "With cateringCTE"
sql = sql & " as"
sql = sql & " ("
sql = sql & " select "
sql = sql & " sum(FinalAmt) [FinalAmt] ,"
sql = sql & " convert(date, ConsultReviewDate) [TransactionDate]"
sql = sql & " from TreatCharges"
sql = sql & " join TreatType"
sql = sql & " on TreatCharges.TreatTypeID = TreatType.TreatTypeID"
sql = sql & " where TreatType.TreatTypeName  like '%CATERING%' "
sql = sql & " and (convert(date, ConsultReviewDate) between '2017-10-01' and '2019-12-31')"
sql = sql & " group by "
sql = sql & " convert(date, ConsultReviewDate)"
sql = sql & " ),"
sql = sql & " dischargeCTE as("
sql = sql & " select   "
sql = sql & " convert(date, DischargeDate) [TransactionDate],"
sql = sql & " sum(BedCharge * dbo.fn_NoOfDaysAdmitted(AdmissionDate, DischargeDate)) [FinalAmt] "
sql = sql & " from Admission"
sql = sql & " where BedCharge > 0"
sql = sql & " and dbo.fn_NoOfDaysAdmitted(AdmissionDate, DischargeDate) is not null"
sql = sql & " and (convert(date, DischargeDate) between '2017-10-01' and '2019-12-31')"
sql = sql & " group by  "
sql = sql & " convert(date, DischargeDate)"
sql = sql & " )"
sql = sql & " "
sql = sql & " select "
sql = sql & " format(isnull(cateringCTE.FinalAmt, 0), 'N2') [CateringAmt], "
sql = sql & " isnull(cateringCTE.TransactionDate, dischargeCTE.TransactionDate) [CateringDate], "
sql = sql & " format(isnull(dischargeCTE.FinalAmt, 0), 'N2') [DischargeAmt], "
sql = sql & " isnull(dischargeCTE.TransactionDate, cateringCTE.TransactionDate) [DischargeDate],"
sql = sql & " format((isnull(cateringCTE.FinalAmt, 0) + isnull(dischargeCTE.FinalAmt, 0)), 'N2') [TotalAmt]"
sql = sql & " from dischargeCTE"
sql = sql & " full outer join cateringCTE"
sql = sql & " on dischargeCTE.TransactionDate = cateringCTE.TransactionDate"
sql = sql & " order by convert(date, dischargeCTE.TransactionDate) desc"
