'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
Response.Clear
Response.Write "<!DOCTYPE html>"
Response.Write "<html lang=""en"">"
Response.Write "  <head>"
Response.Write "    <meta charset=""UTF-8"" />"
Response.Write "    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />"
Response.Write "    <link rel=""stylesheet"" href=""https://cdn.jsdelivr.net/npm/choices.js@11.1.0/public/assets/styles/choices.min.css"" />"
Response.Write "    <script src=""https://cdn.jsdelivr.net/npm/choices.js@11.1.0/public/assets/scripts/choices.min.js""></script>"
Response.Write "    <title>Sponsor Form</title>"

Response.Write "    <script>"

Response.Write "      const sponsorChoices = new Choices('#sponsors', {"
Response.Write "        searchEnabled: true,"
Response.Write "        placeholderValue: 'Search',"
Response.Write "        searchPlaceholderValue: 'Search',"
Response.Write "        itemSelectText: '',"
Response.Write "        shouldSort: false,"
Response.Write "        callbackOnInit: function () {"
Response.Write "          console.log('Sponsors dropdown initialized');"
Response.Write "        },"
Response.Write "        callbackOnChange: function (value) {"
Response.Write "          console.log('Sponsors selected:', value);"
Response.Write "        }"
Response.Write "      });"

Response.Write "      const billMonthChoices = new Choices('#billMonth', {"
Response.Write "        searchEnabled: true,"
Response.Write "        placeholderValue: 'Search',"
Response.Write "        searchPlaceholderValue: 'Search',"
Response.Write "        itemSelectText: '',"
Response.Write "        shouldSort: false,"
Response.Write "        callbackOnInit: function () {"
Response.Write "          console.log('Bill Month dropdown initialized');"
Response.Write "        },"
Response.Write "        callbackOnChange: function (value) {"
Response.Write "          console.log('Bill Months selected:', value);"
Response.Write "        }"
Response.Write "      });"

Response.Write "      function sendData(event) {"
Response.Write "        event.preventDefault(); // Prevent form submission"
Response.Write "        const sponsorSelect = document.getElementById('sponsors');"
Response.Write "        const selectedSponsor = sponsorSelect.selectedOptions[0] ? {"
Response.Write "          id: sponsorSelect.value,"
Response.Write "          value: sponsorSelect.selectedOptions[0].text"
Response.Write "        } : null;"
Response.Write "        const billMonthSelect = document.getElementById('billMonth');"
Response.Write "        const selectedBillMonth = billMonthSelect.selectedOptions[0] ? {"
Response.Write "          id: billMonthSelect.value,"
Response.Write "          value: billMonthSelect.selectedOptions[0].text"
Response.Write "        } : null;"
Response.Write "        const amount = document.getElementById('amount').value;"
Response.Write "        if (!selectedSponsor || !selectedBillMonth || !amount) {"
Response.Write "          alert('Please select a sponsor, a bill month, and enter an amount.');"
Response.Write "          return;"
Response.Write "        }"
Response.Write "        const data = {"
Response.Write "          sponsor: selectedSponsor,"
Response.Write "          billMonth: selectedBillMonth,"
Response.Write "          amount: amount"
Response.Write "        };"

Response.Write "      }"
Response.Write "    </script>"

Response.Write "    <style>"
Response.Write "      body {"
Response.Write "        display: flex;"
Response.Write "        justify-content: center;"
Response.Write "        align-items: center;"
Response.Write "        min-height: 100vh;"
Response.Write "        background-color: #f4f5f7;"
Response.Write "        margin: 0;"
Response.Write "        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;"
Response.Write "      }"
Response.Write "      .form-container {"
Response.Write "        background-color: #fff;"
Response.Write "        padding: 2rem;"
Response.Write "        border-radius: 0.5rem;"
Response.Write "        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);"
Response.Write "        max-width: 350px;"
Response.Write "        width: 100%;"
Response.Write "      }"
Response.Write "      form {"
Response.Write "        display: flex;"
Response.Write "        flex-direction: column;"
Response.Write "        gap: 1.2rem;"
Response.Write "      }"
Response.Write "      label {"
Response.Write "        font-size: 0.9rem;"
Response.Write "        font-weight: 500;"
Response.Write "        color: #374151;"
Response.Write "      }"
Response.Write "      .choices {"
Response.Write "        max-width: 100%;"
Response.Write "      }"
Response.Write "      .choices__inner {"
Response.Write "        padding: 0.5rem;"
Response.Write "        border: 1px solid #d1d5db;"
Response.Write "        border-radius: 0.375rem;"
Response.Write "        background-color: #fff;"
Response.Write "        font-size: 0.875rem;"
Response.Write "        line-height: 1.5rem;"
Response.Write "        min-height: 2.25rem;"
Response.Write "        width: 100%;"
Response.Write "        box-sizing: border-box;"
Response.Write "        transition: border-color 0.2s ease;"
Response.Write "      }"
Response.Write "      .choices__inner:hover, .choices__inner:focus, .choices__inner:focus-within {"
Response.Write "        border-color: #92e681;"
Response.Write "        width: 100% !important;"
Response.Write "      }"
Response.Write "      .choices__input {"
Response.Write "        background-color: #fff;"
Response.Write "        border: none;"
Response.Write "        outline: none;"
Response.Write "        font-size: 0.875rem;"
Response.Write "        line-height: 1.5rem;"
Response.Write "        padding: 0.25rem 0.5rem;"
Response.Write "        width: 100%;"
Response.Write "        box-sizing: border-box;"
Response.Write "      }"
Response.Write "      .choices__list--dropdown {"
Response.Write "        position: absolute;"
Response.Write "        z-index: 10;"
Response.Write "        border: 1px solid #d1d5db;"
Response.Write "        border-radius: 0.375rem;"
Response.Write "        background-color: #fff;"
Response.Write "        max-height: 15rem;"
Response.Write "        overflow: auto;"
Response.Write "        width: 100%;"
Response.Write "        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);"
Response.Write "      }"
Response.Write "      .choices__item--selectable {"
Response.Write "        padding: 0.5rem 0.75rem;"
Response.Write "        cursor: pointer;"
Response.Write "      }"
Response.Write "      .choices__item--selectable:hover {"
Response.Write "        background-color: #eaffe6;"
Response.Write "      }"
Response.Write "      .choices__placeholder {"
Response.Write "        opacity: 0.5;"
Response.Write "      }"
Response.Write "      input[type='number'] {"
Response.Write "        padding: 0.5rem;"
Response.Write "        border: 1px solid #d1d5db;"
Response.Write "        border-radius: 0.375rem;"
Response.Write "        font-size: 0.875rem;"
Response.Write "        line-height: 1.5rem;"
Response.Write "        width: 100%;"
Response.Write "        box-sizing: border-box;"
Response.Write "        transition: border-color 0.2s ease;"
Response.Write "      }"
Response.Write "      input[type='number']:focus {"
Response.Write "        outline: none;"
Response.Write "        border-color: #92e681;"
Response.Write "        box-shadow: 0 0 0 3px rgba(146, 230, 129, 0.2);"
Response.Write "      }"
Response.Write "      button {"
Response.Write "        padding: 0.5rem 1.5rem;"
Response.Write "        background-color: #327b2c;"
Response.Write "        color: #fff;"
Response.Write "        border: none;"
Response.Write "        border-radius: 0.375rem;"
Response.Write "        font-size: 0.875rem;"
Response.Write "        font-weight: 500;"
Response.Write "        cursor: pointer;"
Response.Write "        transition: background-color 0.2s ease, transform 0.1s ease;"
Response.Write "      }"
Response.Write "      button:hover {"
Response.Write "        background-color: #2a6724;"
Response.Write "        transform: translateY(-1px);"
Response.Write "      }"
Response.Write "      button:active {"
Response.Write "        transform: translateY(0);"
Response.Write "      }"
Response.Write "    </style>"
Response.Write "  </head>"
Response.Write "  <body>"
Response.Write "    <div class=""form-container"">"
Response.Write "      <form action="""">"
Response.Write "        <label for=""sponsors"">Sponsor:</label>"
Response.Write "        <select name=""sponsors"" id=""sponsors"">"
Response.Write "          <option value="""">--Please choose an option--</option>"
Response.Write "          <option value=""S06"">Ecobank</option>"
Response.Write "          <option value=""S05"">Acacia</option>"
Response.Write "          <option value=""S04"">Glico</option>"
Response.Write "          <option value=""S03"">Equity</option>"
Response.Write "          <option value=""S02"">Nationwide</option>"
Response.Write "        </select>"
Response.Write "        <label for=""billMonth"">Bill Month:</label>"
Response.Write "        <select name=""billMonth"" id=""billMonth"">"
Response.Write "          <option value="""">--Please choose an option--</option>"
Response.Write "          <option value=""MTH202509"">Sept 2025</option>"
Response.Write "          <option value=""MTH202508"">Aug 2025</option>"
Response.Write "          <option value=""MTH202507"">Jul 2025</option>"
Response.Write "          <option value=""MTH202506"">Jun 2025</option>"
Response.Write "          <option value=""MTH202505"">May 2025</option>"
Response.Write "        </select>"
Response.Write "        <label for=""amount"">Amount:</label>"
Response.Write "        <input type=""number"" id=""amount"" name=""amount"" />"
Response.Write "        <button type=""button"" onclick=""sendData(event)"">Save</button>"
Response.Write "      </form>"
Response.Write "    </div>"



Response.Write "  </body>"
Response.Write "</html>"

'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
