/* Delimiter changed to ; */
/* Connecting to 192.168.1.242 via Microsoft SQL Server (TCP/IP), username admin, using password: Yes ... */
SELECT DATEDIFF(SECOND, "login_time", CURRENT_TIMESTAMP) FROM "master"."dbo"."sysprocesses" WHERE "spid"=1;
SELECT GETDATE();
SELECT @@VERSION;
SELECT SERVERPROPERTY('ProductVersion');
SET TEXTSIZE 2147483647;
SELECT @@SPID;
/* Connected. Thread-ID: 136 */
/* Reading function definitions from C:\Program Files\HeidiSQL\functions-mssql.ini */
SELECT "name" FROM "sys"."databases" ORDER BY "name";
USE "YBMHMS01";
/* Entering session "YBMHMS01 - Live" */
SELECT *, SCHEMA_NAME("schema_id") AS 'schema' FROM "YBMHMS01"."sys"."objects" WHERE "type" IN ('P', 'U', 'V', 'TR', 'FN', 'TF', 'IF');
/* Loading file "C:\Users\Administrator\AppData\Roaming\HeidiSQL\Backups\query-tab-2025-02-11_17-34-56-825.sql" (79 B) into query tab #1 */
/* Loading file "C:\Users\Administrator\AppData\Roaming\HeidiSQL\Backups\query-tab-2025-03-20_13-16-11-176.sql" (60 B) into query tab #2 */
/* Loading file "C:\Users\Administrator\AppData\Roaming\HeidiSQL\Backups\query-tab-2025-03-20_13-18-24-492.sql" (3.5 KiB) into query tab #3 */
/* Loading file "C:\Users\Administrator\AppData\Roaming\HeidiSQL\Backups\query-tab-2025-04-03_16-35-20-544.sql" (124 B) into query tab #4 */
/* Loading file "C:\Users\Administrator\AppData\Roaming\HeidiSQL\Backups\query-tab-2025-04-11_12-32-34-622.sql" (72 B) into query tab #5 */
/* Scaling controls to screen DPI: 125% */
SELECT * FROM "INFORMATION_SCHEMA"."COLUMNS" WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='Admission' ORDER BY ORDINAL_POSITION;
SELECT c.name AS "column", prop.value AS "comment" FROM sys.extended_properties AS prop INNER JOIN sys.all_objects o ON prop.major_id = o.object_id INNER JOIN sys.schemas s ON o.schema_id = s.schema_id INNER JOIN sys.columns AS c ON prop.major_id = c.object_id AND prop.minor_id = c.column_id WHERE   prop.name='MS_Description'  AND s.name='dbo'  AND o.name='Admission';
SELECT * FROM "INFORMATION_SCHEMA"."KEY_COLUMN_USAGE" AS col, "INFORMATION_SCHEMA"."TABLE_CONSTRAINTS" AS con WHERE col.TABLE_SCHEMA='dbo' AND col.TABLE_NAME='Admission' AND col.TABLE_SCHEMA=con.TABLE_SCHEMA AND col.TABLE_NAME=con.TABLE_NAME AND col.CONSTRAINT_NAME=con.CONSTRAINT_NAME;
SELECT   f.name AS foreign_key_name,   COL_NAME(fc.parent_object_id, fc.parent_column_id) AS constraint_column_name,   OBJECT_NAME (f.referenced_object_id) AS referenced_object,   COL_NAME(fc.referenced_object_id, fc.referenced_column_id) AS referenced_column_name,   update_referential_action_desc,   delete_referential_action_desc FROM sys.foreign_keys AS f INNER JOIN sys.foreign_key_columns AS fc   ON f.object_id = fc.constraint_object_id WHERE f.parent_object_id = OBJECT_ID('Admission');
SELECT '' AS "Collation", '' AS "Charset", 0 AS "Id", '' AS "Default", '' AS "Compiled", 1 AS "Sortlen";
SELECT tc.CONSTRAINT_NAME, cc.CHECK_CLAUSE FROM "INFORMATION_SCHEMA"."CHECK_CONSTRAINTS" AS cc, "INFORMATION_SCHEMA"."TABLE_CONSTRAINTS" AS tc WHERE tc.CONSTRAINT_SCHEMA='dbo' AND tc.TABLE_NAME='Admission' AND tc.CONSTRAINT_TYPE='CHECK' AND tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME;
SELECT  "AdmissionID",  "AdmissionName",  "VisitationID",  "AdmissionTypeID",  "Remark",  "PatientID",  "BlockID",  "WardID",  "WardSectionID",  "BedID",  "BedNoID",  "BedPos",  "BedTypeID",  "BedModeID",  "BedCharge",  "AdmissionDate",  "DischargeDate",  "NoOfDays",  "AdmissionStatusID",  "GenderID",  "InsuredPatientID",  "InsuranceTypeID",  "InsuranceZoneID",  "InsuranceSchemeID",  "SystemUserID",  "JobScheduleID",  "WorkingYearID",  "WorkingMonthID",  "WorkingDayID",  "KeyPrefix",  "TransProcessStatID",  "TransProcessValID",  "PostTransactionID",  "AdmissionAmt1",  "AdmissionAmt2",  "AdmissionAmt3",  "AdmissionDate2",  "AdmissionDate3", LEFT("AdmissionInfo1", 256),  "AdmissionInfo2",  "SpecialistID",  "AgeGroupID",  "ReceiptTypeID",  "BillYearID",  "BillMonthID",  "BillDayID",  "BillProcessDate",  "MedicalStaffID",  "MedicalServiceID",  "BranchID",  "BedGroupID",  "BedClassID",  "RevenueCenterID",  "BillGroupCatID",  "BillGroupID",  "SponsorID",  "BranchBatchID",  "BranchSubBatchID",  "MedicalStaff2ID",  "MainValue1",  "MainValue2",  "MainDate1",  "MainDate2",  "MainInfo1",  "MainInfo2",  "MainInfo3",  "MainInfo4" FROM "YBMHMS01"."dbo"."Admission" ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
SELECT  "AdmissionID",  "AdmissionName",  "VisitationID",  "AdmissionTypeID",  "Remark",  "PatientID",  "BlockID",  "WardID",  "WardSectionID",  "BedID",  "BedNoID",  "BedPos",  "BedTypeID",  "BedModeID",  "BedCharge",  "AdmissionDate",  "DischargeDate",  "NoOfDays",  "AdmissionStatusID",  "GenderID",  "InsuredPatientID",  "InsuranceTypeID",  "InsuranceZoneID",  "InsuranceSchemeID",  "SystemUserID",  "JobScheduleID",  "WorkingYearID",  "WorkingMonthID",  "WorkingDayID",  "KeyPrefix",  "TransProcessStatID",  "TransProcessValID",  "PostTransactionID",  "AdmissionAmt1",  "AdmissionAmt2",  "AdmissionAmt3",  "AdmissionDate2",  "AdmissionDate3", LEFT("AdmissionInfo1", 256),  "AdmissionInfo2",  "SpecialistID",  "AgeGroupID",  "ReceiptTypeID",  "BillYearID",  "BillMonthID",  "BillDayID",  "BillProcessDate",  "MedicalStaffID",  "MedicalServiceID",  "BranchID",  "BedGroupID",  "BedClassID",  "RevenueCenterID",  "BillGroupCatID",  "BillGroupID",  "SponsorID",  "BranchBatchID",  "BranchSubBatchID",  "MedicalStaff2ID",  "MainValue1",  "MainValue2",  "MainDate1",  "MainDate2",  "MainInfo1",  "MainInfo2",  "MainInfo3",  "MainInfo4" FROM "YBMHMS01"."dbo"."Admission" ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
SELECT * FROM "INFORMATION_SCHEMA"."COLUMNS" WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='AdmissionStatus' ORDER BY ORDINAL_POSITION;
SELECT c.name AS "column", prop.value AS "comment" FROM sys.extended_properties AS prop INNER JOIN sys.all_objects o ON prop.major_id = o.object_id INNER JOIN sys.schemas s ON o.schema_id = s.schema_id INNER JOIN sys.columns AS c ON prop.major_id = c.object_id AND prop.minor_id = c.column_id WHERE   prop.name='MS_Description'  AND s.name='dbo'  AND o.name='AdmissionStatus';
SELECT * FROM "INFORMATION_SCHEMA"."KEY_COLUMN_USAGE" AS col, "INFORMATION_SCHEMA"."TABLE_CONSTRAINTS" AS con WHERE col.TABLE_SCHEMA='dbo' AND col.TABLE_NAME='AdmissionStatus' AND col.TABLE_SCHEMA=con.TABLE_SCHEMA AND col.TABLE_NAME=con.TABLE_NAME AND col.CONSTRAINT_NAME=con.CONSTRAINT_NAME;
SELECT   f.name AS foreign_key_name,   COL_NAME(fc.parent_object_id, fc.parent_column_id) AS constraint_column_name,   OBJECT_NAME (f.referenced_object_id) AS referenced_object,   COL_NAME(fc.referenced_object_id, fc.referenced_column_id) AS referenced_column_name,   update_referential_action_desc,   delete_referential_action_desc FROM sys.foreign_keys AS f INNER JOIN sys.foreign_key_columns AS fc   ON f.object_id = fc.constraint_object_id WHERE f.parent_object_id = OBJECT_ID('AdmissionStatus');
SELECT tc.CONSTRAINT_NAME, cc.CHECK_CLAUSE FROM "INFORMATION_SCHEMA"."CHECK_CONSTRAINTS" AS cc, "INFORMATION_SCHEMA"."TABLE_CONSTRAINTS" AS tc WHERE tc.CONSTRAINT_SCHEMA='dbo' AND tc.TABLE_NAME='AdmissionStatus' AND tc.CONSTRAINT_TYPE='CHECK' AND tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME;
SELECT * FROM "YBMHMS01"."dbo"."AdmissionStatus" ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
SELECT  "AdmissionID",  "AdmissionName",  "VisitationID",  "AdmissionTypeID",  "Remark",  "PatientID",  "BlockID",  "WardID",  "WardSectionID",  "BedID",  "BedNoID",  "BedPos",  "BedTypeID",  "BedModeID",  "BedCharge",  "AdmissionDate",  "DischargeDate",  "NoOfDays",  "AdmissionStatusID",  "GenderID",  "InsuredPatientID",  "InsuranceTypeID",  "InsuranceZoneID",  "InsuranceSchemeID",  "SystemUserID",  "JobScheduleID",  "WorkingYearID",  "WorkingMonthID",  "WorkingDayID",  "KeyPrefix",  "TransProcessStatID",  "TransProcessValID",  "PostTransactionID",  "AdmissionAmt1",  "AdmissionAmt2",  "AdmissionAmt3",  "AdmissionDate2",  "AdmissionDate3", LEFT("AdmissionInfo1", 256),  "AdmissionInfo2",  "SpecialistID",  "AgeGroupID",  "ReceiptTypeID",  "BillYearID",  "BillMonthID",  "BillDayID",  "BillProcessDate",  "MedicalStaffID",  "MedicalServiceID",  "BranchID",  "BedGroupID",  "BedClassID",  "RevenueCenterID",  "BillGroupCatID",  "BillGroupID",  "SponsorID",  "BranchBatchID",  "BranchSubBatchID",  "MedicalStaff2ID",  "MainValue1",  "MainValue2",  "MainDate1",  "MainDate2",  "MainInfo1",  "MainInfo2",  "MainInfo3",  "MainInfo4" FROM "YBMHMS01"."dbo"."Admission" ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
UPDATE "YBMHMS01"."dbo"."Admission" SET "AdmissionStatusID"=N'A002' WHERE  "AdmissionID"=N'A250417001';
SELECT "AdmissionID", "AdmissionName", "VisitationID", "AdmissionTypeID", "Remark", "PatientID", "BlockID", "WardID", "WardSectionID", "BedID", "BedNoID", "BedPos", "BedTypeID", "BedModeID", "BedCharge", "AdmissionDate", "DischargeDate", "NoOfDays", "AdmissionStatusID", "GenderID", "InsuredPatientID", "InsuranceTypeID", "InsuranceZoneID", "InsuranceSchemeID", "SystemUserID", "JobScheduleID", "WorkingYearID", "WorkingMonthID", "WorkingDayID", "KeyPrefix", "TransProcessStatID", "TransProcessValID", "PostTransactionID", "AdmissionAmt1", "AdmissionAmt2", "AdmissionAmt3", "AdmissionDate2", "AdmissionDate3", "AdmissionInfo1", "AdmissionInfo2", "SpecialistID", "AgeGroupID", "ReceiptTypeID", "BillYearID", "BillMonthID", "BillDayID", "BillProcessDate", "MedicalStaffID", "MedicalServiceID", "BranchID", "BedGroupID", "BedClassID", "RevenueCenterID", "BillGroupCatID", "BillGroupID", "SponsorID", "BranchBatchID", "BranchSubBatchID", "MedicalStaff2ID", "MainValue1", "MainValue2", "MainDate1", "MainDate2", "MainInfo1", "MainInfo2", "MainInfo3", "MainInfo4" FROM "YBMHMS01"."dbo"."Admission" WHERE  "AdmissionID"=N'A250417001';