UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=1 WHERE  "EMRVar3BID"=N'RES023015001';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015001';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=2 WHERE  "EMRVar3BID"=N'RES023015002';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015002';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=4 WHERE  "EMRVar3BID"=N'RES023015004';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015004';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=5 WHERE  "EMRVar3BID"=N'RES023015005';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015005';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');

UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=1 WHERE  "EMRVar3BID"=N'RES023015001';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015001';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=2 WHERE  "EMRVar3BID"=N'RES023015002';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015002';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=4 WHERE  "EMRVar3BID"=N'RES023015004';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015004';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=5 WHERE  "EMRVar3BID"=N'RES023015005';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015005';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
SELECT * FROM "FOHMS02"."dbo"."EMRVar3B" WHERE EMRVar3AID='RES023004'

 ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=1 WHERE  "EMRVar3BID"=N'RES023004001';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004001';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=2 WHERE  "EMRVar3BID"=N'RES023004002';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004002';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=4 WHERE  "EMRVar3BID"=N'RES023004004';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004004';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=5 WHERE  "EMRVar3BID"=N'RES023004005';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004005';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=1 WHERE  "EMRVar3BID"=N'RES023004005';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004005';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=2 WHERE  "EMRVar3BID"=N'RES023004004';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004004';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=4 WHERE  "EMRVar3BID"=N'RES023004002';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004002';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=5 WHERE  "EMRVar3BID"=N'RES023004001';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023004001';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
SELECT * FROM "FOHMS02"."dbo"."EMRVar3B" WHERE EMRVar3AID='RES023015'

 ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1000 ROWS ONLY;
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=1 WHERE  "EMRVar3BID"=N'RES023015005';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015005';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=2 WHERE  "EMRVar3BID"=N'RES023015004';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015004';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=4 WHERE  "EMRVar3BID"=N'RES023015002';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015002';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');
UPDATE "FOHMS02"."dbo"."EMRVar3B" SET "VarPos"=5 WHERE  "EMRVar3BID"=N'RES023015001';
SELECT "EMRVar3BID", "EMRVar3BName", "EMRVar3AID", "VarPos", "Description", "KeyPrefix" FROM "FOHMS02"."dbo"."EMRVar3B" WHERE  "EMRVar3BID"=N'RES023015001';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('FOHMS02.dbo.EMRVar3B');