response.write "<script> "
response.write "   document.getElementById('callApiButton').addEventListener('click', function() {"
response.write "       var xhr = new XMLHttpRequest();"
response.write "      var url = 'wpgxmlhttp.asp?procedurename=generatepatientinvoice&tablename=labbydoctor&KeyPrefix=E100002747-TH060&LabtestID=L324||L405';"
response.write "       xhr.open('GET', url, true);"
response.write "       xhr.onreadystatechange = function() {"
response.write "           if (xhr.readyState === 4 && xhr.status === 200) {"
response.write "               console.log(xhr.responseText);"
response.write "           }"
response.write "        };"
response.write "       xhr.send();"
response.write "   });"
response.write " </script>"