'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
response.Clear
response.write vbCrLf & "<html lang=""en"">"
response.write vbCrLf & "<head>"
response.write vbCrLf & "    <meta charset=""UTF-8"">"
response.write vbCrLf & "    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
response.write vbCrLf & "    <title>Document</title>"
response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.googleapis.com"">"
response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.gstatic.com"" crossorigin>"
response.write vbCrLf & "    <link href=""https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"" rel=""stylesheet"">"
response.write vbCrLf & "    <style>"
response.write vbCrLf & "        body{"
response.write vbCrLf & "            margin: 0;"
response.write vbCrLf & "            padding: 0;"
response.write vbCrLf & "            font-family: ""Nunito"", sans-serif;"
response.write vbCrLf & "            font-optical-sizing: auto;"
response.write vbCrLf & "            overflow-y: clip;"
response.write vbCrLf & "        }"
response.write vbCrLf & ""
response.write vbCrLf & "        main{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        button,input{"
response.write vbCrLf & "            font-family: inherit;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .main-content{"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            flex-direction: column;"
response.write vbCrLf & "            height:100vh;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-list{"
response.write vbCrLf & "            width: 400px;"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            height: 100vh;"
response.write vbCrLf & "            border-left: 1px solid gainsboro;"
response.write vbCrLf & "            box-sizing: border-box;"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            flex-direction: column;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .main-header{"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            padding: 7px 40px 0 40px;"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-nav ul{"
response.write vbCrLf & "            padding-left: 0;"
response.write vbCrLf & "            list-style: none;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            margin: 0;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-nav li{"
response.write vbCrLf & "            padding: 8px 20px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .active{"
response.write vbCrLf & "            background-color: rgba(220, 220, 220,0.6);"
response.write vbCrLf & "            border-bottom: 2px solid #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dynamic-content{"
response.write vbCrLf & "            scrollbar-width: thin;"
response.write vbCrLf & "            overflow-y: scroll;"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            /* padding: 0 40px; */"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .search-container{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .search-container input{"
response.write vbCrLf & "            padding: 5px 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .categories{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            grid-template-columns: repeat(4,1fr);"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-mart-items{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "            grid-template-columns: repeat(3,1fr);"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .category{"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            background-color: beige;"
response.write vbCrLf & "            border: 1px solid bisque; "
response.write vbCrLf & "            cursor: pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-mart-item{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            justify-content: space-between;"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            background-color: beige;"
response.write vbCrLf & "            border: 1px solid bisque; "
response.write vbCrLf & "            font-size: 11px;"
response.write vbCrLf & "            cursor: 11px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-items{"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            background-color: white;"
response.write vbCrLf & "            overflow:scroll;"
response.write vbCrLf & "            scrollbar-width:thin;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-action-button{"
response.write vbCrLf & "            border-top: 1px solid gainsboro;"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-action-button button{"
response.write vbCrLf & "            padding: 10px 0;"
response.write vbCrLf & "            border: none;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list{"
response.write vbCrLf & "            border-collapse: collapse;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list th,.item-order-list td{"
response.write vbCrLf & "            text-align: left;"
response.write vbCrLf & "            padding: 4px 6px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list tr{"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .spinner {"
response.write vbCrLf & "            border: 8px solid #f3f3f3; "
response.write vbCrLf & "            border-top: 8px solid #3498db;"
response.write vbCrLf & "            border-radius: 50%;"
response.write vbCrLf & "            width: 50px;"
response.write vbCrLf & "            height: 50px;"
response.write vbCrLf & "            animation: spin 1s linear infinite;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .spinner-container{"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            position: fixed;"
response.write vbCrLf & "            top: 0;"
response.write vbCrLf & "            left: 0;"
response.write vbCrLf & "            right: 0;"
response.write vbCrLf & "            bottom: 0;"
response.write vbCrLf & "            height: 100vh;"
response.write vbCrLf & "            background-color: rgba(0, 0, 0,0.5);"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            justify-content: center;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .error{"
response.write vbCrLf & "            border-color: red;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-selected{"
response.write vbCrLf & "            border-color: #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-selected{"
response.write vbCrLf & "            border-color: #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .drafts,.receipts{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            grid-template-columns: 1fr 1fr;"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .draft,.receipt{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            gap: 4px;"
response.write vbCrLf & "            font-size: 12px;"
response.write vbCrLf & "            background-color: beige;"
response.write vbCrLf & "            border: 1px solid bisque; "
response.write vbCrLf & "            padding: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-nav{"
response.write vbCrLf & "            cursor: pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list>tbody>tr{"
response.write vbCrLf & "            position:relative;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .remove-row{"
response.write vbCrLf & "            color:white;"
response.write vbCrLf & "            background-color:#FF5739;"
response.write vbCrLf & "            width:fit-content;"
response.write vbCrLf & "            cursor:pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        @keyframes spin {"
response.write vbCrLf & "            0% { transform: rotate(0deg); }"
response.write vbCrLf & "            100% { transform: rotate(360deg); }"
response.write vbCrLf & "        }"
response.write vbCrLf & "    </style>"
response.write vbCrLf & "</head>"
response.write vbCrLf & "<body>"
response.write vbCrLf & "    <div class=""spinner-container"" style=""display: none;"" id=""spinner"">"
response.write vbCrLf & "        <div class=""spinner"" ></div>"
response.write vbCrLf & "    </div>"
response.write vbCrLf & "    <template id=""miniMartTemplate"">"
response.write vbCrLf & "        <div class=""mini-mart-item"" id=""mini-mart-item"">"
response.write vbCrLf & "            <div style=""display: grid;gap: 2px;"">"
response.write vbCrLf & "                <span style=""font-size: 15px;"">{item-name}</span>"
response.write vbCrLf & "                <span>Price:{item-price}</span>"
response.write vbCrLf & "                <span>Qty:{item-qty}</span>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <input type=""checkbox"" value=""{itemid}"">"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""draftTemplate"">"
response.write vbCrLf & "        <div class=""draft"">"
response.write vbCrLf & "            <span>Order {order-id}</span>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;font-size: 16px;"">"
response.write vbCrLf & "                <span>{customer-name}</span><span>&#8373;{total-price}</span></div>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;""><span>Item No:{total-no}</span><span>Qty:{total-qty}</span></div>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""receiptTemplate"">"
response.write vbCrLf & "        <div class=""receipt"">"
response.write vbCrLf & "            <span>R90342341</span>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;font-size: 16px;"">"
response.write vbCrLf & "                <span>{customer-name}</span><span>&#8373;{total-price}</span></div>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;""><span>Item No:{total-no}</span><span>Qty:{total-qty}</span></div>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <main>"
response.write vbCrLf & "        <section class=""main-content"">"
response.write vbCrLf & "            <header class=""main-header"">"
response.write vbCrLf & "                <h3>Mini Mart</h3>"
response.write vbCrLf & "                <nav class=""mini-nav"">"
response.write vbCrLf & "                    <ul id=""mini-mart-nav-links"">"
response.write vbCrLf & "                        <li class=""active"" id=""store-link"">Store</li>"
response.write vbCrLf & "                        <li id=""draft-link"">Drafts</li>"
response.write vbCrLf & "                        <li id=""receipt-link"">Receipts</li>"
response.write vbCrLf & "                    </ul>"
response.write vbCrLf & "                </nav>"
response.write vbCrLf & "            </header>"
response.write vbCrLf & "            <div class=""dynamic-content"">"
response.write vbCrLf & "                <div class=""drafts"" for=""draft-link"" style=""display: none;"">"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "                <div class=""receipts"" for=""receipt-link"" style=""display: none;"">"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "                <div class=""store""  for=""store-link"">"
response.write vbCrLf & "                    <div class=""search-container"">"
response.write vbCrLf & "                        <span>Search</span>"
response.write vbCrLf & "                        <input type=""search"" id=""searchItemElement""/>"
response.write vbCrLf & "                    </div>"
response.write vbCrLf & "                    <div id=""categories"" class=""categories"" >"
response.write vbCrLf & "                    </div> "
response.write vbCrLf & "                    <div id=""mini-mart-items"" class=""mini-mart-items"">"
response.write vbCrLf & "                        "
response.write vbCrLf & "                    </div>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "        </section>"
response.write vbCrLf & "        <section class=""order-list"" id=""order-list"">"
response.write vbCrLf & "            <div style=""border-bottom: 1px solid gainsboro;padding-bottom: 10px;"">"
response.write vbCrLf & "                <h3>Item Sale Order</h3>"
response.write vbCrLf & "                <div>"
response.write vbCrLf & "                    <label for=""customer-name"" style=""display: grid; font-size: 15px;color: rgb(48, 47, 47);"">"
response.write vbCrLf & "                        Customer Name:"
response.write vbCrLf & "                        <input type=""text"" style=""padding: 6px 5px;"" id=""customerName"" placeholder=""must contain first name and last name separated by space"" >"
response.write vbCrLf & "                    </label>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <div class=""order-items"">"
response.write vbCrLf & "                <h4 style=""margin: 0; padding: 6px 5px;background-color: whitesmoke;border-bottom: 1px solid gainsboro;"">Order Items</h4>"
response.write vbCrLf & "                <table style=""font-size: 12px;"" width=""100%"" class=""item-order-list"" id=""item-order-list"">"
response.write vbCrLf & "                    <thead>"
response.write vbCrLf & "                        <tr>"
response.write vbCrLf & "                            <th>Item Name</th>"
response.write vbCrLf & "                            <th>Available Qty</th>"
response.write vbCrLf & "                            <th>Qty</th>"
response.write vbCrLf & "                            <th>Total Cost</th>"
response.write vbCrLf & "                        </tr>"
response.write vbCrLf & "                    </thead>"
response.write vbCrLf & "                    <tbody>"
response.write vbCrLf & "                    </tbody>"
response.write vbCrLf & "                </table>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <div class=""order-action-button"">"
response.write vbCrLf & "                <table style=""font-size: 13px;"">"
response.write vbCrLf & "                    <tr>"
response.write vbCrLf & "                        <td>Item No: <span id=""itemNoElement"">0</span></td> "
response.write vbCrLf & "                        <td>Total Qty: <span id=""itemQtyElement"">0</span></td> "
response.write vbCrLf & "                        <td>Total Price: <span id=""itemPriceElement"">0</span></td> "
response.write vbCrLf & "                    </tr>"
response.write vbCrLf & "                </table>"
response.write vbCrLf & "                <button style=""background-color: black;"" id=""saveDraftBtn"">"
response.write vbCrLf & "                    Save as Draft"
response.write vbCrLf & "                </button>"
response.write vbCrLf & "                <button style=""background-color: forestgreen;"" id=""processOrderBtn"">"
response.write vbCrLf & "                    Process"
response.write vbCrLf & "                </button>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "        </section>"
response.write vbCrLf & "    </main>"
response.write vbCrLf & "    <script>"
response.write vbCrLf & "        let itemList = [];"
response.write vbCrLf & "        let categoryList = [];"
response.write vbCrLf & "        let receiptHref = 'wpgPrtPrintLayoutAll.asp?PrintLayoutName=ReceiptSlip2A&PositionForTableName=WorkingDay&WorkingDayID=&drugsaleid=';"
response.write vbCrLf & "        let controller = new AbortController();"
response.write vbCrLf & "        function showLoader(bool){"
response.write vbCrLf & "            const spinner = document.getElementById('spinner');"
response.write vbCrLf & "            spinner.style.display = bool?'':'none';"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadStore(){"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            categories.style.display = 'grid';"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETCATEGORIES';"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            fetch(endpoint).then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    categoryList = data;"
response.write vbCrLf & "                    categories.innerHTML = """";"
response.write vbCrLf & "                    for(const obj of categoryList){"
response.write vbCrLf & "                        const div = document.createElement('div');"
response.write vbCrLf & "                        div.innerText = obj.catname;"
response.write vbCrLf & "                        div.id = obj.catid;"
response.write vbCrLf & "                        div.className = 'category';"
response.write vbCrLf & "                        div.addEventListener('click',function(){"
response.write vbCrLf & "                            openCategoryForItems(obj.catid);"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        categories.appendChild(div);"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "                if(data.length===0){"
response.write vbCrLf & "                    categories.innerHTML = ""No Item in Store"";"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.log(e);showLoader(false);})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadReceipts(){"
response.write vbCrLf & "            const receiptsContainer = document.querySelector('.receipts');"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETRECEIPTS';"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            fetch(endpoint).then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                receiptsContainer.innerHTML = """";"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    for(const obj of data){"
response.write vbCrLf & "                        const div = draftTemplate.content.cloneNode(true).querySelector('.draft');"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{order-id}',obj.drugsaleid);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{customer-name}',obj.drugsalename);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{total-price}',obj.itemprice);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{total-qty}',obj.itemqty);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{total-no}',obj.itemno);"
response.write vbCrLf & "                        receiptsContainer.appendChild(div);"
response.write vbCrLf & "                        div.addEventListener('click',function(){"
response.write vbCrLf & "                            window.open(receiptHref+obj.drugsaleid+'&receiptid='+obj.receiptid,'_blank','width=800px,height=800px')"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "                if(data.length===0){"
response.write vbCrLf & "                    receiptsContainer.innerHTML = ""No Receipt Found"";"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.log(e);showLoader(false);})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadDrafts(){"
response.write vbCrLf & "            const draftContainer = document.querySelector('.drafts');"
response.write vbCrLf & "            let drafts = []"
response.write vbCrLf & "            const prevDrafts = localStorage.getItem('mini-mart-drafts');"
response.write vbCrLf & "            if(prevDrafts){"
response.write vbCrLf & "                drafts = JSON.parse(prevDrafts);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            const cleanDrafts = drafts.filter(obj=>{"
response.write vbCrLf & "                return obj.exp >= Date.now();"
response.write vbCrLf & "            })"
response.write vbCrLf & "            draftContainer.innerHTML = """";"
response.write vbCrLf & "            if(cleanDrafts.length==0){return draftContainer.innerHTML = ""No Drafts Found"";}"
response.write vbCrLf & "            for(const obj of cleanDrafts){"
response.write vbCrLf & "                const div = draftTemplate.content.cloneNode(true).querySelector('.draft');"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{order-id}',obj.id);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{customer-name}',obj.customerName);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{total-price}',obj.totalPrice);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{total-qty}',obj.totalQty);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{total-no}',obj.totalNo);"
response.write vbCrLf & "                div.addEventListener('click',function(){"
response.write vbCrLf & "                    loadOrderFromObj(obj);"
response.write vbCrLf & "                })"
response.write vbCrLf & "                draftContainer.appendChild(div);"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        window.addEventListener('load',function(){"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const miniMartLinks = document.querySelectorAll('#mini-mart-nav-links li');"
response.write vbCrLf & "            const contentHolders = document.querySelectorAll('.dynamic-content>div');"
response.write vbCrLf & "            categories.style.display = 'grid';"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            customerName.value = 'IMAH Customer';"
response.write vbCrLf & "            loadStore();"
response.write vbCrLf & "            loadDrafts();"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            searchItemElement.addEventListener('input',function(){"
response.write vbCrLf & "                const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "                const categories = document.getElementById('categories');"
response.write vbCrLf & "                const searchString = searchItemElement.value;"
response.write vbCrLf & "                if(searchString?.length>0){"
response.write vbCrLf & "                    categories.style.display = 'none';"
response.write vbCrLf & "                    miniMartItems.style.display = 'grid';"
response.write vbCrLf & "                    searchItem(searchString);"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    categories.style.display = 'grid';"
response.write vbCrLf & "                    miniMartItems.style.display = 'none';"
response.write vbCrLf & "                }"
response.write vbCrLf & "            });"
response.write vbCrLf & "            if(miniMartLinks){"
response.write vbCrLf & "                for(const el of [...miniMartLinks]){"
response.write vbCrLf & "                    el.addEventListener('click',function(){"
response.write vbCrLf & "                        contentHolders.forEach(ele=>{"
response.write vbCrLf & "                            ele.style.display='none';"
response.write vbCrLf & "                            if(ele.getAttribute('for')===el.id){"
response.write vbCrLf & "                                ele.style.display = 'grid';"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        });"
response.write vbCrLf & "                        const prevActiveLink = document.querySelector('.active');"
response.write vbCrLf & "                        if(prevActiveLink){"
response.write vbCrLf & "                            prevActiveLink.classList.remove('active');"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        el.classList.add('active');"
response.write vbCrLf & "                        if(el.id===""store-link""){"
response.write vbCrLf & "                            loadStore();"
response.write vbCrLf & "                        }else if(el.id===""draft-link""){"
response.write vbCrLf & "                            loadDrafts();"
response.write vbCrLf & "                        }else if(el.id===""receipt-link""){"
response.write vbCrLf & "                            loadReceipts();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                    })"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "            saveDraftBtn.addEventListener('click',function(){"
response.write vbCrLf & "                saveAsDraft();"
response.write vbCrLf & "            });"
response.write vbCrLf & "            processOrderBtn.addEventListener('click',function(){"
response.write vbCrLf & "                processOrder();"
response.write vbCrLf & "            });"
response.write vbCrLf & "        })"
response.write vbCrLf & "        function openCategoryForItems(cat){"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETITEMSFROMCAT';"
response.write vbCrLf & "            endpoint += '&cat=' + cat;"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            fetch(endpoint).then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    itemList = data;"
response.write vbCrLf & "                    categories.style.display = 'none';"
response.write vbCrLf & "                    miniMartItems.style.display = 'grid';"
response.write vbCrLf & "                    miniMartItems.innerHTML = '';"
response.write vbCrLf & "                    showLoader(false);"
response.write vbCrLf & "                    for(const obj of itemList){"
response.write vbCrLf & "                        const miniMartItem = miniMartTemplate.content.cloneNode(true).getElementById('mini-mart-item');"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-name}',obj.itemname);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-price}',obj.itemprice);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-qty}',obj.itemqty);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{itemid}',obj.itemid);"
response.write vbCrLf & "                        const miniMartItemCheck = miniMartItem.querySelector('input[type=""checkbox""]');"
response.write vbCrLf & "                        miniMartItem.addEventListener('click',function(){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItemCheck.style.pointerEvents = 'none';"
response.write vbCrLf & "                        miniMartItemCheck.addEventListener('change',function(){"
response.write vbCrLf & "                            if(miniMartItemCheck.checked){"
response.write vbCrLf & "                                miniMartItem.classList.add('item-selected');"
response.write vbCrLf & "                                addOrderItem(obj.itemid)"
response.write vbCrLf & "                            }else{"
response.write vbCrLf & "                                miniMartItem.classList.remove('item-selected');"
response.write vbCrLf & "                                removeOrderItem(obj.itemid);"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItems.appendChild(miniMartItem);"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    alert('No drug found')"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{showLoader(false);})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function searchItem(sn){"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=SEARCH';"
response.write vbCrLf & "            endpoint += '&item=' + sn;"
response.write vbCrLf & "            controller.abort();"
response.write vbCrLf & "            controller = new AbortController();"
response.write vbCrLf & "            const signal = controller.signal;"
response.write vbCrLf & "            miniMartItems.innerHTML = 'Loading....';"
response.write vbCrLf & "            fetch(endpoint,{signal}).then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    categories.style.display = 'none';"
response.write vbCrLf & "                    miniMartItems.style.display = 'grid';"
response.write vbCrLf & "                    miniMartItems.innerHTML = '';"
response.write vbCrLf & "                    itemList = data;"
response.write vbCrLf & "                    for(const obj of itemList){"
response.write vbCrLf & "                        const miniMartItem = miniMartTemplate.content.cloneNode(true).getElementById('mini-mart-item');"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-name}',obj.itemname);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-price}',obj.itemprice);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-qty}',obj.itemqty);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{itemid}',obj.itemid);"
response.write vbCrLf & "                        const miniMartItemCheck = miniMartItem.querySelector('input[type=""checkbox""]');"
response.write vbCrLf & "                        miniMartItem.addEventListener('click',function(){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItemCheck.style.pointerEvents = 'none';"
response.write vbCrLf & "                        miniMartItemCheck.addEventListener('change',function(){"
response.write vbCrLf & "                            if(miniMartItemCheck.checked){"
response.write vbCrLf & "                                miniMartItem.classList.add('item-selected');"
response.write vbCrLf & "                                addOrderItem(obj.itemid)"
response.write vbCrLf & "                            }else{"
response.write vbCrLf & "                                miniMartItem.classList.remove('item-selected');"
response.write vbCrLf & "                                removeOrderItem(obj.itemid);"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItems.appendChild(miniMartItem);"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    alert('No drug found')"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.error(e)})"
response.write vbCrLf & "        }"
response.write vbCrLf & "           function removeOrderItem(itemid){"
response.write vbCrLf & "                const orderTable = document.getElementById('item-order-list');"
response.write vbCrLf & "                if(typeof itemid === ""string""){"
response.write vbCrLf & "                    const item = document.getElementById(itemid)"
response.write vbCrLf & "                    if(item){"
response.write vbCrLf & "                        const tr = item.closest('tr');"
response.write vbCrLf & "                        tr?.remove();"
response.write vbCrLf & "                        recalculate();"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        function addOrderItem(itemid){"
response.write vbCrLf & "            if(typeof itemid === ""string""){"
response.write vbCrLf & "                const item = document.getElementById(itemid)"
response.write vbCrLf & "                if(!item){"
response.write vbCrLf & "                    const itemObj = itemList.find(el=>el.itemid===itemid);"
response.write vbCrLf & "                    addToTable(itemObj);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function addToTable(itemObj){"
response.write vbCrLf & "           const orderTable = document.querySelector('#item-order-list');"
response.write vbCrLf & "           if(typeof itemObj === ""object""){"
response.write vbCrLf & "               if(orderTable){"
response.write vbCrLf & "                   if(!orderTable.querySelector('#'+itemObj.itemid)){"
response.write vbCrLf & "                       const orderTbody = document.querySelector('tbody');"
response.write vbCrLf & "                       const tr = document.createElement('tr');"
response.write vbCrLf & "                       const td = document.createElement('td');"
response.write vbCrLf & "                       td.id = itemObj.itemid;"
response.write vbCrLf & "                       td.innerText = itemObj.itemname;"
response.write vbCrLf & "                       td.className = itemObj.itemname;"
response.write vbCrLf & "                       const td2 = document.createElement('td');"
response.write vbCrLf & "                       td2.id = itemObj.itemid + ""-qty"";"
response.write vbCrLf & "                       td2.innerText = itemObj.itemqty||'-';"
response.write vbCrLf & "                       td2.className = itemObj.itemqty||'-';"
response.write vbCrLf & "                       const td3 = document.createElement('td');"
response.write vbCrLf & "                       const input = document.createElement('input');"
response.write vbCrLf & "                       input.type = 'number';"
response.write vbCrLf & "                       input.value = 1;"
response.write vbCrLf & "                       input.id = itemObj.itemid + ""-inp-qty"";"
response.write vbCrLf & "                       input.style.width = '60px';"
response.write vbCrLf & "                       input.addEventListener('input',function(){"
response.write vbCrLf & "                           const itemPrice = document.getElementById(itemObj.itemid + ""-price"");"
response.write vbCrLf & "                           if(input.value){"
response.write vbCrLf & "                               const qty = parseFloat(input.value);"
response.write vbCrLf & "                               const totalPrice = qty * itemObj.itemprice;"
response.write vbCrLf & "                               if(itemPrice){"
response.write vbCrLf & "                                   itemPrice.className = totalPrice;"
response.write vbCrLf & "                                   itemPrice.innerText = totalPrice;"
response.write vbCrLf & "                                   recalculate();"
response.write vbCrLf & "                               }"
response.write vbCrLf & "                           }"
response.write vbCrLf & "                       })"
response.write vbCrLf & "                       td3.appendChild(input);"
response.write vbCrLf & "                       const td4 = document.createElement('td');"
response.write vbCrLf & "                       td4.id = itemObj.itemid + ""-price"";"
response.write vbCrLf & "                       td4.innerText = itemObj.itemprice;"
response.write vbCrLf & "                       td4.setAttribute('original-qty', itemObj.itemprice);"
response.write vbCrLf & "                       td4.className = itemObj.itemprice;"
response.write vbCrLf & "                       const td5 = document.createElement('td');"
response.write vbCrLf & "                       td5.innerText = 'X';"
response.write vbCrLf & "                       td5.className = 'remove-row';"
response.write vbCrLf & "                       td5.addEventListener('click',function(){"
response.write vbCrLf & "                           tr.remove();"
response.write vbCrLf & "                       });"
response.write vbCrLf & "                       tr.appendChild(td);"
response.write vbCrLf & "                       tr.appendChild(td2);"
response.write vbCrLf & "                       tr.appendChild(td3);"
response.write vbCrLf & "                       tr.appendChild(td4);"
response.write vbCrLf & "                       tr.appendChild(td5);"
response.write vbCrLf & "                       orderTbody.appendChild(tr);"
response.write vbCrLf & "                       recalculate();"
response.write vbCrLf & "                   }"
response.write vbCrLf & "               }"
response.write vbCrLf & "           }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function recalculate(){"
response.write vbCrLf & "            const qtyList = document.querySelectorAll('[id$=""-inp-qty""]');"
response.write vbCrLf & "            const priceList = document.querySelectorAll('[id$=""-price""]');"
response.write vbCrLf & "            if(qtyList.length>=0 && priceList.length>=0){"
response.write vbCrLf & "                itemNoElement.innerText = qtyList.length;"
response.write vbCrLf & "                itemQtyElement.innerText = [...qtyList].map(el=>parseFloat(el.value||'0')).reduce((acc,c)=>acc+c,0);"
response.write vbCrLf & "                itemPriceElement.innerText = [...priceList].map(el=>parseFloat(el.className||'0')).reduce((acc,c)=>acc+c,0);"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function buildJSON(){"
response.write vbCrLf & "            const orderJSON = {};"
response.write vbCrLf & "            if(!/^[aA-zZ]{2,}\s[aA-zZ]{2,}$/.test(customerName.value)){"
response.write vbCrLf & "                customerName.classList.add('error');"
response.write vbCrLf & "                return null;"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                customerName.classList.remove('error');"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.id = generateID();"
response.write vbCrLf & "            orderJSON.customerName = customerName.value;"
response.write vbCrLf & "            const orderTable = document.getElementById('item-order-list');"
response.write vbCrLf & "            const tbody = orderTable.querySelector('tbody');"
response.write vbCrLf & "            const list = tbody.querySelectorAll('tr');"
response.write vbCrLf & "            if(list.length === 0){"
response.write vbCrLf & "                alert('no item selected')"
response.write vbCrLf & "                return null;"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.orderitems = []"
response.write vbCrLf & "            for(const tr of [...list]){"
response.write vbCrLf & "                const obj = {}"
response.write vbCrLf & "                const itemIdElement = tr.querySelector('td');"
response.write vbCrLf & "                obj.itemid = itemIdElement.id;"
response.write vbCrLf & "                obj.itemname = itemIdElement.className;"
response.write vbCrLf & "                const itemQtyElement = tr.querySelector('[id$=""-inp-qty""]');"
response.write vbCrLf & "                obj.issueqty = parseFloat(itemQtyElement.value||""0"");"
response.write vbCrLf & "                const itemPrice = tr.querySelector('[id$=""-price""]');"
response.write vbCrLf & "                obj.itemprice = parseFloat(itemPrice.getAttribute('original-qty')||""0"");"
response.write vbCrLf & "                orderJSON.orderitems.push(obj);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.totalNo = itemNoElement.innerText.trim()||0;"
response.write vbCrLf & "            orderJSON.totalPrice = itemPriceElement.innerText.trim()||0;"
response.write vbCrLf & "            orderJSON.totalQty = itemQtyElement.innerText.trim()||0;"
response.write vbCrLf & "            return orderJSON;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function processOrder(){"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=PROCESSORDER';"
response.write vbCrLf & "            const JSONBody = buildJSON();"
response.write vbCrLf & "            if(JSONBody){"
response.write vbCrLf & "                const ok = confirm('are you sure you want to proceed');"
response.write vbCrLf & "                if(ok){"
response.write vbCrLf & "                   showLoader(true);"
response.write vbCrLf & "                   fetch(endpoint,{"
response.write vbCrLf & "                       method:""POST"","
response.write vbCrLf & "                       body:JSON.stringify(JSONBody)"
response.write vbCrLf & "                   }).then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                          if(data.success){ "
response.write vbCrLf & "                              alert(data.message); "
response.write vbCrLf & "                              const activeLink = document.querySelector('#mini-mart-nav-links .active'); "
response.write vbCrLf & "                              if(activeLink){ "
response.write vbCrLf & "                                  activeLink.dispatchEvent(new Event('click')); "
response.write vbCrLf & "                              } "
response.write vbCrLf & "                              window.open(receiptHref+data.drugsaleid+'&receiptid='+data.receiptid,'_blank','width=800px,height=900px'); "
response.write vbCrLf & "                              resetOrder();"
response.write vbCrLf & "                          }else{ "
response.write vbCrLf & "                              alert(data.message); "
response.write vbCrLf & "                              showLoader(false);"
response.write vbCrLf & "                          } "
response.write vbCrLf & "                   }).catch(e=>{alert('Something went wrong');showLoader(false);})"
response.write vbCrLf & "               }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "       function saveAsDraft(){"
response.write vbCrLf & "           let drafts = []"
response.write vbCrLf & "           const prevDrafts = localStorage.getItem('mini-mart-drafts');"
response.write vbCrLf & "           if(prevDrafts){"
response.write vbCrLf & "               drafts = JSON.parse(prevDrafts);"
response.write vbCrLf & "           }"
response.write vbCrLf & "           const cleanDrafts = drafts.filter(obj=>{"
response.write vbCrLf & "               return obj.exp >= Date.now();"
response.write vbCrLf & "           })"
response.write vbCrLf & "           const JSONOrder = buildJSON();"
response.write vbCrLf & "           if(JSONOrder){"
response.write vbCrLf & "               JSONOrder.exp = Date.now() + (7*24*60*60*1000);"
response.write vbCrLf & "               cleanDrafts.unshift(JSONOrder);"
response.write vbCrLf & "               alert('saved to Draft');"
response.write vbCrLf & "               resetOrder();"
response.write vbCrLf & "           }"
response.write vbCrLf & "           localStorage.setItem('mini-mart-drafts',JSON.stringify(cleanDrafts));"
response.write vbCrLf & "           const activeLink = document.querySelector('#mini-mart-nav-links .active'); "
response.write vbCrLf & "           if(activeLink){ "
response.write vbCrLf & "               activeLink.dispatchEvent(new Event('click')); "
response.write vbCrLf & "           } "
response.write vbCrLf & "       }"
response.write vbCrLf & "       function resetOrder(){"
response.write vbCrLf & "           if(customerName){"
response.write vbCrLf & "               customerName.value = """";"
response.write vbCrLf & "           }"
response.write vbCrLf & "           const orderTable = document.getElementById('item-order-list');"
response.write vbCrLf & "           const tbody = orderTable.querySelector('tbody');"
response.write vbCrLf & "           if(tbody){"
response.write vbCrLf & "               tbody.innerHTML = """";"
response.write vbCrLf & "           }"
response.write vbCrLf & "           recalculate();"
response.write vbCrLf & "       }"
response.write vbCrLf & "       function loadOrderFromObj(obj){"
response.write vbCrLf & "           if(obj){"
response.write vbCrLf & "               resetOrder()"
response.write vbCrLf & "               if(customerName){"
response.write vbCrLf & "                   customerName.value = obj.customerName;"
response.write vbCrLf & "               }"
response.write vbCrLf & "               for(const itemObj of obj.orderitems){"
response.write vbCrLf & "                   addToTable(itemObj);"
response.write vbCrLf & "                   const input = document.getElementById(itemObj.itemid + ""-inp-qty"");"
response.write vbCrLf & "                   if(input){"
response.write vbCrLf & "                       input.value = itemObj.issueqty;"
response.write vbCrLf & "                       input.dispatchEvent(new Event('input'));"
response.write vbCrLf & "                       recalculate();"
response.write vbCrLf & "                   }"
response.write vbCrLf & "               }"
response.write vbCrLf & "           }"
response.write vbCrLf & "       }"
response.write vbCrLf & "       function generateID() {"
response.write vbCrLf & "           const prefix = 'IMAH';"
response.write vbCrLf & "           let numbers = '';"
response.write vbCrLf & "           for (let i = 0; i < 8; i++) {"
response.write vbCrLf & "               numbers += Math.floor(Math.random() * 1e10 % 10); "
response.write vbCrLf & "           }"
response.write vbCrLf & "           return prefix + numbers;"
response.write vbCrLf & "       }"
response.write vbCrLf & "    </script>"
response.write vbCrLf & "</body>"
response.write vbCrLf & "</html>"

'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
