CssStyles
InPatientList

Sub InPatientList
  response.write"<body>"
    response.write"    <h1>Company Name</h1>"
    response.write"    <h2>In Patient List(Month)</h2>"
    response.write"    <table cellpadding='2' border='1' width='100%' cellspacing='0'>"
    response.write"      <thead>"
    response.write"        <tr>"
    response.write"          <th>Name Of Patient</th>"
    response.write"          <th>Name Of Principal</th>"
    response.write"          <th>Insurance/Staff No.</th>"
    response.write"          <th>Visit No.</th>"
    response.write"          <th>Admission Date</th>"
    response.write"          <th>Discharge Date</th>"
    response.write"          <th>Ward</th>"
    response.write"          <th>Amount</th>"
    response.write"          <th>View Bill</th>"
    response.write"        </tr>"
    response.write"      </thead>"
    response.write"      <tbody>"
    response.write"        <tr>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"        </tr>"
    response.write"        <tr>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"        </tr>"
    response.write"        <tr>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"          <td>DUMMY</td>"
    response.write"        </tr>"
    response.write"      </tbody>"
    response.write"    </table>"
  response.write"  </body>"
End Sub

Sub CssStyles
  response.write"<style>"                                                               
  response.write"  body {"
  response.write"    width: 80%;"
  response.write"    padding: 50px 100px;"
  response.write"    margin: auto;"
  response.write"    font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;"
  response.write"  }"

  response.write"  h1,"
  response.write"  h2 {"
  response.write"    text-align: center;"
  response.write"  }"
  response.write"</style>"
End Sub
