'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
response.Clear
response.write vbCrLf & "<html lang=""en"">"
response.write vbCrLf & "<head>"
response.write vbCrLf & "    <meta charset=""UTF-8"">"
response.write vbCrLf & "    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">"
response.write vbCrLf & "    <title>Document</title>"
response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.googleapis.com"">"
response.write vbCrLf & "    <link rel=""preconnect"" href=""https://fonts.gstatic.com"" crossorigin>"
response.write vbCrLf & "    <link href=""https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap"" rel=""stylesheet"">"
response.write vbCrLf & "    <style>"
response.write vbCrLf & "        body{"
response.write vbCrLf & "            margin: 0;"
response.write vbCrLf & "            padding: 0;"
response.write vbCrLf & "            font-family: ""Nunito"", sans-serif;"
response.write vbCrLf & "            font-optical-sizing: auto;"
response.write vbCrLf & "            overflow-y: clip;"
response.write vbCrLf & "        }"
response.write vbCrLf & ""
response.write vbCrLf & "        main{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        button,input,select{"
response.write vbCrLf & "            font-family: inherit;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .main-content{"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            flex-direction: column;"
response.write vbCrLf & "            height:100vh;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-list{"
response.write vbCrLf & "            width: 400px;"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            height: 100vh;"
response.write vbCrLf & "            border-left: 1px solid gainsboro;"
response.write vbCrLf & "            box-sizing: border-box;"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            flex-direction: column;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .main-header{"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            padding: 7px 0px 0 0;"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .main-header>*{"
response.write vbCrLf & "            padding-left: 40px !important;"
response.write vbCrLf & "            padding-right: 40px !important;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-nav ul{"
response.write vbCrLf & "            padding-left: 0;"
response.write vbCrLf & "            list-style: none;"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            margin: 0;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-nav li{"
response.write vbCrLf & "            padding: 8px 20px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .active{"
response.write vbCrLf & "            background-color: rgba(220, 220, 220,0.6);"
response.write vbCrLf & "            border-bottom: 2px solid #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .dynamic-content{"
response.write vbCrLf & "            scrollbar-width: thin;"
response.write vbCrLf & "            overflow-y: scroll;"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            /* padding: 0 40px; */"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .search-container{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "            padding: 10px 0;"
response.write vbCrLf & "            background-color: whitesmoke;"
response.write vbCrLf & "            border-top: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .search-container input{"
response.write vbCrLf & "            padding: 5px 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .categories{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            grid-template-columns: repeat(4,1fr);"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-mart-items{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "            grid-template-columns: repeat(3,1fr);"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .category{"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            background-color: beige;"
response.write vbCrLf & "            border: 1px solid bisque; "
response.write vbCrLf & "            cursor: pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-mart-item{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            justify-content: space-between;"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            background-color: beige;"
response.write vbCrLf & "            border: 1px solid bisque; "
response.write vbCrLf & "            font-size: 11px;"
response.write vbCrLf & "            cursor: 11px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-items{"
response.write vbCrLf & "            flex: 1;"
response.write vbCrLf & "            background-color: white;"
response.write vbCrLf & "            overflow:scroll;"
response.write vbCrLf & "            scrollbar-width:thin;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-action-button{"
response.write vbCrLf & "            border-top: 1px solid gainsboro;"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .order-action-button button{"
response.write vbCrLf & "            padding: 10px 0;"
response.write vbCrLf & "            border: none;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list{"
response.write vbCrLf & "            border-collapse: collapse;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list th,.item-order-list td{"
response.write vbCrLf & "            text-align: left;"
response.write vbCrLf & "            padding: 4px 6px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list tr{"
response.write vbCrLf & "            border-bottom: 1px solid gainsboro;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .spinner {"
response.write vbCrLf & "            border: 8px solid #f3f3f3; "
response.write vbCrLf & "            border-top: 8px solid #3498db;"
response.write vbCrLf & "            border-radius: 50%;"
response.write vbCrLf & "            width: 50px;"
response.write vbCrLf & "            height: 50px;"
response.write vbCrLf & "            animation: spin 1s linear infinite;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .spinner-container{"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            position: fixed;"
response.write vbCrLf & "            top: 0;"
response.write vbCrLf & "            left: 0;"
response.write vbCrLf & "            right: 0;"
response.write vbCrLf & "            bottom: 0;"
response.write vbCrLf & "            height: 100vh;"
response.write vbCrLf & "            background-color: rgba(0, 0, 0,0.5);"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            justify-content: center;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .error{"
response.write vbCrLf & "            border-color: red;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-selected{"
response.write vbCrLf & "            border-color: #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-selected{"
response.write vbCrLf & "            border-color: #0078D4;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .drafts,.receipts,.invoices,.sales{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            grid-template-columns: 1fr 1fr;"
response.write vbCrLf & "            padding: 10px 40px;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .draft,.receipt,.invoice{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            gap: 4px;"
response.write vbCrLf & "            font-size: 12px;"
response.write vbCrLf & "            background-color: beige;"
response.write vbCrLf & "            border: 1px solid bisque; "
response.write vbCrLf & "            padding: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .sales{"
response.write vbCrLf & "            cursor: pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .mini-nav{"
response.write vbCrLf & "            cursor: pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .item-order-list>tbody>tr{"
response.write vbCrLf & "            position:relative;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .remove-row{"
response.write vbCrLf & "            color:white;"
response.write vbCrLf & "            background-color:#FF5739;"
response.write vbCrLf & "            width:fit-content;"
response.write vbCrLf & "            cursor:pointer;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .pending-text{"
response.write vbCrLf & "            color: #FF5739;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .issued-text{"
response.write vbCrLf & "            color: #76C542;"
response.write vbCrLf & "            font-style: normal;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .pending-div{"
response.write vbCrLf & "            background-color: gainsboro !important; "
response.write vbCrLf & "            border-color: grey !important; "
response.write vbCrLf & "        }"
response.write vbCrLf & "        .read-only input,.read-only select,.read-only table{"
response.write vbCrLf & "            pointer-events: none;"
response.write vbCrLf & "            background-color: gainsboro;"
response.write vbCrLf & "            opacity: 0.8;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .read-only #saveDraftBtn{"
response.write vbCrLf & "            background-color: #FF5739 !important;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .partial table{"
response.write vbCrLf & "            pointer-events: initial;"
response.write vbCrLf & "            background-color: initial;"
response.write vbCrLf & "            opacity: initial;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .partial table input{"
response.write vbCrLf & "            pointer-events: initial;"
response.write vbCrLf & "            background-color: initial;"
response.write vbCrLf & "            opacity: initial;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .receipt{"
response.write vbCrLf & "            height: fit-content;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .receipt button{"
response.write vbCrLf & "            border: none;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .disable-input{"
response.write vbCrLf & "            background-color: gainsboro;"
response.write vbCrLf & "            pointer-events: none;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .salesFilter{"
response.write vbCrLf & "            display: none;"
response.write vbCrLf & "            justify-content: flex-end;"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .flex{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .salesFilter button{"
response.write vbCrLf & "            border: none;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "            background-color: #0078D4;"
response.write vbCrLf & "            padding: 2px 15px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .sale,.sale-1{"
response.write vbCrLf & "            display: grid;"
response.write vbCrLf & "            background-color: #3498db;"
response.write vbCrLf & "            padding: 10px 20px;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "            font-size: 12px;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .sale-1{"
response.write vbCrLf & "            background-color: #76C542;"
response.write vbCrLf & "            align-items: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .sale-1 table{"
response.write vbCrLf & "            font-size: 12px;"
response.write vbCrLf & "            color: white;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .sale-1 th{"
response.write vbCrLf & "            font-weight: normal;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .sale-1 td{"
response.write vbCrLf & "            font-size: 20px;"
response.write vbCrLf & "            font-weight: bold;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .bar-record{"
response.write vbCrLf & "            display: flex;"
response.write vbCrLf & "            gap: 10px;"
response.write vbCrLf & "            place-items: center;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .bar{"
response.write vbCrLf & "            width: 100%;"
response.write vbCrLf & "            background-color: gainsboro;"
response.write vbCrLf & "            height: 7px; "
response.write vbCrLf & "            margin: 3px 0; "
response.write vbCrLf & "            border-radius: 10px; "
response.write vbCrLf & "            contain: paint;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        .inner-bar{"
response.write vbCrLf & "            background-color: #FF5739;"
response.write vbCrLf & "            height: 100%;"
response.write vbCrLf & "            border-radius: 12px;"
response.write vbCrLf & "            animation: bar-effect 0.6s ease;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        @keyframes spin {"
response.write vbCrLf & "            0% { transform: rotate(0deg); }"
response.write vbCrLf & "            100% { transform: rotate(360deg); }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        @keyframes bar-effect {"
response.write vbCrLf & "            from{width: 0;}"
response.write vbCrLf & "        }"
response.write vbCrLf & ""
response.write vbCrLf & "    </style>"
response.write vbCrLf & "</head>"
response.write vbCrLf & "<body>"
response.write vbCrLf & "    <div class=""spinner-container"" style=""display: none;"" id=""spinner"">"
response.write vbCrLf & "        <div class=""spinner"" ></div>"
response.write vbCrLf & "    </div>"
response.write vbCrLf & "    <template id=""miniMartTemplate"">"
response.write vbCrLf & "        <div class=""mini-mart-item"" id=""mini-mart-item"">"
response.write vbCrLf & "            <div style=""display: grid;gap: 2px;"">"
response.write vbCrLf & "                <span style=""font-size: 15px;"">{item-name}</span>"
response.write vbCrLf & "                <span>Price:{item-price}</span>"
response.write vbCrLf & "                <span>Qty:{item-qty}</span>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <input type=""checkbox"" value=""{itemid}"">"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""draftTemplate"">"
response.write vbCrLf & "        <div class=""draft"">"
response.write vbCrLf & "            <span>Order {order-id}</span>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;font-size: 16px;"">"
response.write vbCrLf & "                <span>{customer-name}</span><span>&#8373;{total-price}</span></div>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;""><span>Item No:{total-no}</span><span>Qty:{total-qty}</span></div>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""receiptTemplate"">"
response.write vbCrLf & "        <div class=""receipt"">"
response.write vbCrLf & "            <span>{order-id}</span>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;font-size: 16px;"">"
response.write vbCrLf & "                <span>{customer-name}</span><span>&#8373;{total-price}</span></div>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;""><span>Item No:{total-no}</span><span>Qty:{total-qty}</span></div>"
response.write vbCrLf & "            <div id=""receiptAction"" style=""display: grid; grid-template-columns: repeat(2,1fr);gap: 10px;"">"
response.write vbCrLf & "                <button class=""printreceipt"" style=""background-color: #3498db;"">Print</button>"
response.write vbCrLf & "                <button class=""returnitem"" style=""background-color: #FF5739;"">Return Item</button>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""invoiceTemplate"">"
response.write vbCrLf & "        <div class=""invoice"">"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;""><span>Order {order-id}</span><span id=""invoice-status"">{invoice-status}</span></div>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;font-size: 16px;"">"
response.write vbCrLf & "                <span>{customer-name}</span><span>&#8373;{total-price}</span></div>"
response.write vbCrLf & "            <div style=""display: flex;justify-content: space-between;align-items: center;""><span>Item No:{total-no}</span><span>Qty:{total-qty}</span></div>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <template id=""saleTemplate"">"
response.write vbCrLf & "        <div class=""sale"">"
response.write vbCrLf & "            <h3 style=""margin: 0;"">Sales : {from} - {to}</h3>"
response.write vbCrLf & "            <span style=""font-size: 25px; font-weight: bold;text-align: center;"">Ghs {total-amt}</span>"
response.write vbCrLf & "            <div class=""bar-record""><div>Cash</div>"
response.write vbCrLf & "                <div style=""display: flex;width: 100%;place-items: center;gap:10px"">"
response.write vbCrLf & "                    <div class=""bar"">"
response.write vbCrLf & "                        <div id=""cash-per"" class=""inner-bar""></div>"
response.write vbCrLf & "                    </div>"
response.write vbCrLf & "                    <span style=""text-align: center;text-wrap: nowrap;"">Ghs {cash-amt}</span>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <div class=""bar-record""><div>MoMo</div>"
response.write vbCrLf & "                <div style=""display: flex;width: 100%;place-items: center;gap:10px"">"
response.write vbCrLf & "                    <div class=""bar"">"
response.write vbCrLf & "                        <div id=""momo-per"" class=""inner-bar""></div>"
response.write vbCrLf & "                    </div>"
response.write vbCrLf & "                    <span style=""text-align: center;text-wrap: nowrap;"">Ghs {momo-amt}</span>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <span style=""text-align: right;"">Attendant:&nbsp;{attendant}</span>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "        <div class=""sale-1"">"
response.write vbCrLf & "            <table width=""100%"" style=""border-collapse: collapse;height: fit-content;"">"
response.write vbCrLf & "                <tr>"
response.write vbCrLf & "                    <th style=""border-right: 1px solid whitesmoke;"">Total Item</th>"
response.write vbCrLf & "                    <th>Total Qty</th>"
response.write vbCrLf & "                </tr>"
response.write vbCrLf & "                <tr>"
response.write vbCrLf & "                    <td style=""border-right: 1px solid whitesmoke;"" align=""center"">{total-sales}</td>"
response.write vbCrLf & "                    <td align=""center"">{total-qty}</td>"
response.write vbCrLf & "                </tr>"
response.write vbCrLf & "            </table>"
response.write vbCrLf & "        </div>"
response.write vbCrLf & "    </template>"
response.write vbCrLf & "    <main>"
response.write vbCrLf & "        <section class=""main-content"">"
response.write vbCrLf & "            <header class=""main-header"">"
response.write vbCrLf & "                <h3>Mini Mart</h3>"
response.write vbCrLf & "                <nav class=""mini-nav"">"
response.write vbCrLf & "                    <ul id=""mini-mart-nav-links"">"
response.write vbCrLf & "                        <li class=""active"" id=""store-link"">Store</li>"
response.write vbCrLf & "                        <li id=""draft-link"">Drafts</li>"
response.write vbCrLf & "                        <li id=""receipt-link"">Receipts</li>"
response.write vbCrLf & "                        <li id=""invoice-link"">Invoices</li>"
response.write vbCrLf & "                        <li id=""sales-link"">Sales</li>"
response.write vbCrLf & "                    </ul>"
response.write vbCrLf & "                </nav>"
response.write vbCrLf & "                <div class=""search-container"">"
response.write vbCrLf & "                    <span id=""searchText"">Search</span>"
response.write vbCrLf & "                    <input type=""search"" id=""searchItemElement""/>"
response.write vbCrLf & "                    <div id=""salesFilter"" class=""salesFilter"">"
response.write vbCrLf & "                        <select id=""saleAttendant"" style=""width: 100px;"">"
response.write vbCrLf & "                        </select>"
response.write vbCrLf & "                        <div>"
response.write vbCrLf & "                            <input type=""date"" id=""fromElement"" style=""width: 150px;"">"
response.write vbCrLf & "                            <input type=""date"" id=""toElement"" style=""width: 150px;"">"
response.write vbCrLf & "                        </div>"
response.write vbCrLf & "                    <button id=""filterBtn"">filter</button>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </header>"
response.write vbCrLf & "            <div class=""dynamic-content"">"
response.write vbCrLf & "                <div class=""drafts"" for=""draft-link"" style=""display: none;"">"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "                <div class=""receipts"" for=""receipt-link"" style=""display: none;"">"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "                <div class=""invoices"" for=""invoice-link"" style=""display: none;"">"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "                <div class=""sales"" for=""sales-link"" style=""display: none;"">"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "                <div class=""store""  for=""store-link"">"
response.write vbCrLf & "                    <div id=""categories"" class=""categories"" >"
response.write vbCrLf & "                    </div> "
response.write vbCrLf & "                    <div id=""mini-mart-items"" class=""mini-mart-items"">"
response.write vbCrLf & "                        "
response.write vbCrLf & "                    </div>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "        </section>"
response.write vbCrLf & "        <section class=""order-list"" id=""order-list"">"
response.write vbCrLf & "            <input type=""hidden"" id=""receiptElement""/>"
response.write vbCrLf & "            <input type=""hidden"" id=""drugSaleElement""/>"
response.write vbCrLf & "            <input type=""hidden"" id=""orderIdElement""/>"
response.write vbCrLf & "            <div style=""border-bottom: 1px solid gainsboro;padding-bottom: 10px;"">"
response.write vbCrLf & "                <h3>Item Sale Order</h3>"
response.write vbCrLf & "                <div style=""display: flex;gap:10px;"">"
response.write vbCrLf & "                    <label for=""customer-name"" style=""display: grid; font-size: 15px;color: rgb(48, 47, 47);flex:1"">"
response.write vbCrLf & "                        Customer Name:"
response.write vbCrLf & "                        <input type=""text"" style=""padding: 6px 5px;"" id=""customerName"" placeholder=""must contain first name and last name separated by space"" >"
response.write vbCrLf & "                    </label>"
response.write vbCrLf & "                    <label for=""customer-name"" style=""display: grid; font-size: 15px;color: rgb(48, 47, 47);"">"
response.write vbCrLf & "                        Payment Mode:"
response.write vbCrLf & "                        <select id=""paymentMode"" style=""width: 100px;padding:6px 5px;"">"
response.write vbCrLf & "                            <option value=""cash"">Cash</option>"
response.write vbCrLf & "                            <option value=""invoice"">Mobile Money</option>"
response.write vbCrLf & "                        </select>"
response.write vbCrLf & "                    </label>"
response.write vbCrLf & "                </div>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <div class=""order-items"">"
response.write vbCrLf & "                <h4 style=""margin: 0; padding: 6px 5px;background-color: whitesmoke;border-bottom: 1px solid gainsboro;"">Order Items</h4>"
response.write vbCrLf & "                <table style=""font-size: 12px;"" width=""100%"" class=""item-order-list"" id=""item-order-list"">"
response.write vbCrLf & "                    <thead>"
response.write vbCrLf & "                        <tr>"
response.write vbCrLf & "                            <th>Item Name</th>"
response.write vbCrLf & "                            <th>Available Qty</th>"
response.write vbCrLf & "                            <th>Qty</th>"
response.write vbCrLf & "                            <th>Total Cost</th>"
response.write vbCrLf & "                        </tr>"
response.write vbCrLf & "                    </thead>"
response.write vbCrLf & "                    <tbody>"
response.write vbCrLf & "                    </tbody>"
response.write vbCrLf & "                </table>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "            <div class=""order-action-button"">"
response.write vbCrLf & "                <table style=""font-size: 13px;"">"
response.write vbCrLf & "                    <tr>"
response.write vbCrLf & "                        <td>Item No: <span id=""itemNoElement"">0</span></td> "
response.write vbCrLf & "                        <td>Total Qty: <span id=""itemQtyElement"">0</span></td> "
response.write vbCrLf & "                        <td>Total Price: <span id=""itemPriceElement"">0</span></td> "
response.write vbCrLf & "                    </tr>"
response.write vbCrLf & "                </table>"
response.write vbCrLf & "                <button style=""background-color: black;"" id=""saveDraftBtn"">"
response.write vbCrLf & "                    Save as Draft"
response.write vbCrLf & "                </button>"
response.write vbCrLf & "                <button style=""background-color: forestgreen;"" id=""processOrderBtn"">"
response.write vbCrLf & "                    Process"
response.write vbCrLf & "                </button>"
response.write vbCrLf & "            </div>"
response.write vbCrLf & "        </section>"
response.write vbCrLf & "    </main>"
response.write vbCrLf & "    <script>"
response.write vbCrLf & "        let itemList = [];"
response.write vbCrLf & "        let categoryList = [];"
response.write vbCrLf & "        let receiptHref = 'wpgPrtPrintLayoutAll.asp?PrintLayoutName=ReceiptSlip2A&PositionForTableName=WorkingDay&WorkingDayID=&drugsaleid=';"
response.write vbCrLf & "        let salesHref = 'wpgPrtPrintLayoutAll.asp?PrintLayoutName=SaleSummary&PositionForTableName=WorkingDay&WorkingDayID=';"
response.write vbCrLf & "        let controller = new AbortController();"
response.write vbCrLf & "        connect();"
response.write vbCrLf & "        function showLoader(bool){"
response.write vbCrLf & "            const spinner = document.getElementById('spinner');"
response.write vbCrLf & "            spinner.style.display = bool?'':'none';"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadStore(){"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            categories.style.display = 'grid';"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETCATEGORIES';"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            fetch(endpoint)"
response.write vbCrLf & "            .then(res=>{"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                return res.json();"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    categoryList = data;"
response.write vbCrLf & "                    categories.innerHTML = """";"
response.write vbCrLf & "                    const topRecent = document.createElement('div');"
response.write vbCrLf & "                    topRecent.innerText = 'RECENT SOLD';"
response.write vbCrLf & "                    topRecent.id = 'recent_sold';"
response.write vbCrLf & "                    topRecent.className = 'category';"
response.write vbCrLf & "                    topRecent.addEventListener('click',function(){"
response.write vbCrLf & "                        getTopItems('RECENT');"
response.write vbCrLf & "                    })"
response.write vbCrLf & "                    const top50 = document.createElement('div');"
response.write vbCrLf & "                    top50.innerText = 'MOST SOLD';"
response.write vbCrLf & "                    top50.id = 'top_50';"
response.write vbCrLf & "                    top50.className = 'category';"
response.write vbCrLf & "                    top50.addEventListener('click',function(){"
response.write vbCrLf & "                        getTopItems('TOP-50');"
response.write vbCrLf & "                    })"
response.write vbCrLf & "                    categories.appendChild(topRecent);"
response.write vbCrLf & "                    categories.appendChild(top50);"
response.write vbCrLf & "                    for(const obj of categoryList){"
response.write vbCrLf & "                        const div = document.createElement('div');"
response.write vbCrLf & "                        div.innerText = obj.catname;"
response.write vbCrLf & "                        div.id = obj.catid;"
response.write vbCrLf & "                        div.className = 'category';"
response.write vbCrLf & "                        div.addEventListener('click',function(){"
response.write vbCrLf & "                            openCategoryForItems(obj.catid);"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        categories.appendChild(div);"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "                if(data.length===0){"
response.write vbCrLf & "                    categories.innerHTML = ""No Item in Store"";"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.log(e);})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        "
response.write vbCrLf & "        function cleanOrderDraft(id){"
response.write vbCrLf & "            let drafts = []"
response.write vbCrLf & "            const prevDrafts = localStorage.getItem('mini-mart-drafts');"
response.write vbCrLf & "            if(prevDrafts){"
response.write vbCrLf & "                drafts = JSON.parse(prevDrafts);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            const cleanDrafts = drafts.filter(obj=>{"
response.write vbCrLf & "                return obj.exp >= Date.now() && obj.id !== id;"
response.write vbCrLf & "            })"
response.write vbCrLf & "            localStorage.setItem('mini-mart-drafts',JSON.stringify(cleanDrafts));"
response.write vbCrLf & "            loadDrafts();"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function getTopItems(id){"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETTOPITEMS';"
response.write vbCrLf & "            endpoint += '&filter=' + id;"
response.write vbCrLf & "            categories.style.display = 'none';"
response.write vbCrLf & "            miniMartItems.style.display = 'grid';"
response.write vbCrLf & "            miniMartItems.innerHTML = '';"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            fetch(endpoint)"
response.write vbCrLf & "            .then(res=>{"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                return res.json();"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    itemList = data;"
response.write vbCrLf & "                    for(const obj of itemList){"
response.write vbCrLf & "                        const miniMartItem = miniMartTemplate.content.cloneNode(true).getElementById('mini-mart-item');"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-name}',obj.itemname);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-price}',obj.itemprice);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-qty}',obj.itemqty);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{itemid}',obj.itemid);"
response.write vbCrLf & "                        const miniMartItemCheck = miniMartItem.querySelector('input[type=""checkbox""]');"
response.write vbCrLf & "                        miniMartItem.addEventListener('click',function(){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        const orderTable = document.querySelector('#item-order-list');"
response.write vbCrLf & "                        const orderItem = orderTable?.querySelector('[id=""'+obj.itemid+'""]');"
response.write vbCrLf & "                        miniMartItemCheck.style.pointerEvents = 'none';"
response.write vbCrLf & "                        miniMartItemCheck.addEventListener('change',function(){"
response.write vbCrLf & "                            if(miniMartItemCheck.checked){"
response.write vbCrLf & "                                miniMartItem.classList.add('item-selected');"
response.write vbCrLf & "                                addOrderItem(obj.itemid)"
response.write vbCrLf & "                            }else{"
response.write vbCrLf & "                                miniMartItem.classList.remove('item-selected');"
response.write vbCrLf & "                                removeOrderItem(obj.itemid);"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItems.appendChild(miniMartItem);"
response.write vbCrLf & "                        if(orderItem){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    miniMartItems.innerHTML = 'No Item found';"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.error(e)})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadReceipts(){"
response.write vbCrLf & "            const receiptsContainer = document.querySelector('.receipts');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETRECEIPTS';"
response.write vbCrLf & "            const sn = searchItemElement.value;"
response.write vbCrLf & "            if(sn){"
response.write vbCrLf & "                endpoint += '&search=' + sn;"
response.write vbCrLf & "                receiptsContainer.innerHTML = ""loading..."";"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                showLoader(true);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            controller.abort();"
response.write vbCrLf & "            controller = new AbortController();"
response.write vbCrLf & "            const signal = controller.signal;"
response.write vbCrLf & "            fetch(endpoint,{signal})"
response.write vbCrLf & "            .then(res=>{"
response.write vbCrLf & "                receiptsContainer.innerHTML = """";"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                return res.json();"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    for(const obj of data){"
response.write vbCrLf & "                        const div = receiptTemplate.content.cloneNode(true).querySelector('.receipt');"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{order-id}',obj.drugsaleid);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{customer-name}',obj.drugsalename);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{total-price}',obj.itemprice);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{total-qty}',obj.itemqty);"
response.write vbCrLf & "                        div.innerHTML = div.innerHTML.replace('{total-no}',obj.itemno);"
response.write vbCrLf & "                        const printReceiptBtn = div.querySelector('.printreceipt');"
response.write vbCrLf & "                        const returnItemBtn = div.querySelector('.returnitem');"
response.write vbCrLf & "                        receiptsContainer.appendChild(div);"
response.write vbCrLf & "                        printReceiptBtn.onclick = function(){"
response.write vbCrLf & "                            printReceipt(obj.drugsaleid,obj.receiptid)"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        returnItemBtn.onclick = returnDrug(obj.drugsaleid);"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "                if(data.length===0){"
response.write vbCrLf & "                    receiptsContainer.innerHTML = ""No Receipt Found"";"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.log(e);})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function printReceipt(drugsaleid,receiptid){"
response.write vbCrLf & "            window.open(receiptHref+drugsaleid+'&receiptid='+receiptid,'_blank','width=800px,height=800px')"
response.write vbCrLf & "        }"
response.write vbCrLf & "        "
response.write vbCrLf & "        function loadInvoices(){"
response.write vbCrLf & "            let endpoint = ""wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETINVOICES"";"
response.write vbCrLf & "            const invoiceContainer = document.querySelector('.invoices');"
response.write vbCrLf & "            const sn = searchItemElement.value;"
response.write vbCrLf & "            if(sn){"
response.write vbCrLf & "                endpoint += '&search=' + sn;"
response.write vbCrLf & "                invoiceContainer.innerHTML = ""loading..."";"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                showLoader(true);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            controller.abort();"
response.write vbCrLf & "            controller = new AbortController();"
response.write vbCrLf & "            const signal = controller.signal;"
response.write vbCrLf & "            fetch(endpoint,{signal}).then(res=>{"
response.write vbCrLf & "                invoiceContainer.innerHTML = """";"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                return res.json();"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                if(data.length==0)return invoiceContainer.innerHTML = ""No Invoices Found"";"
response.write vbCrLf & "                data.reverse();"
response.write vbCrLf & "                for(const obj of data){"
response.write vbCrLf & "                    const invoiceObj = obj[""invoicedetails""];"
response.write vbCrLf & "                    const div = invoiceTemplate.content.cloneNode(true).querySelector('.invoice');"
response.write vbCrLf & "                    div.innerHTML = div.innerHTML.replace('{order-id}',obj.id);"
response.write vbCrLf & "                    div.innerHTML = div.innerHTML.replace('{invoice-status}',invoiceObj.invoicestatus??"""");"
response.write vbCrLf & "                    div.innerHTML = div.innerHTML.replace('{customer-name}',obj.customerName);"
response.write vbCrLf & "                    div.innerHTML = div.innerHTML.replace('{total-price}',obj.totalPrice);"
response.write vbCrLf & "                    div.innerHTML = div.innerHTML.replace('{total-qty}',obj.totalQty);"
response.write vbCrLf & "                    div.innerHTML = div.innerHTML.replace('{total-no}',obj.totalNo);"
response.write vbCrLf & "                    const invoiceStatus = div.querySelector('#invoice-status');"
response.write vbCrLf & "                    if(invoiceObj.invoicestatus.trim().toUpperCase()===""P001""){"
response.write vbCrLf & "                        invoiceStatus.className = ""pending-text"";"
response.write vbCrLf & "                        invoiceStatus.innerText = ""pending"";"
response.write vbCrLf & "                        div.classList.add('pending-div');"
response.write vbCrLf & "                    }else if(invoiceObj.invoicestatus.trim().toUpperCase()===""P002""){"
response.write vbCrLf & "                        invoiceStatus.className = ""issued-text"";"
response.write vbCrLf & "                        invoiceStatus.innerText = ""paid"";"
response.write vbCrLf & "                        const orderSection = document.getElementById('order-list');"
response.write vbCrLf & "                        div.addEventListener('click',function(){"
response.write vbCrLf & "                            loadOrderFromObj(obj);"
response.write vbCrLf & "                            receiptElement.value = invoiceObj.receiptno;"
response.write vbCrLf & "                            paymentMode.value = 'invoice';"
response.write vbCrLf & "                            if(orderSection){"
response.write vbCrLf & "                                orderSection.classList.add('read-only');"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                            saveDraftBtn.innerText = 'Cancel';"
response.write vbCrLf & "                            processOrderBtn.innerHTML = 'Process&nbsp;[&#8373;' + invoiceObj.receiptamount + ']';"
response.write vbCrLf & "                            saveDraftBtn.onclick = resetOrder;"
response.write vbCrLf & "                            processOrderBtn.onclick = processOrder;"
response.write vbCrLf & "                        });"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                    invoiceContainer.appendChild(div);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.log(e);})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function disableSearch(bool){"
response.write vbCrLf & "            if(bool){"
response.write vbCrLf & "                searchItemElement.classList.add('disable-input')"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                searchItemElement.classList.remove('disable-input')"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadDrafts(){"
response.write vbCrLf & "            send('add-attendant',{user:'"" & uname & ""'})"
response.write vbCrLf & "            const draftContainer = document.querySelector('.drafts');"
response.write vbCrLf & "            let drafts = []"
response.write vbCrLf & "            const prevDrafts = localStorage.getItem('mini-mart-drafts');"
response.write vbCrLf & "            if(prevDrafts){"
response.write vbCrLf & "                drafts = JSON.parse(prevDrafts);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            const cleanDrafts = drafts.filter(obj=>{"
response.write vbCrLf & "                return obj.exp >= Date.now();"
response.write vbCrLf & "            })"
response.write vbCrLf & "            draftContainer.innerHTML = """";"
response.write vbCrLf & "            if(cleanDrafts.length==0){return draftContainer.innerHTML = ""No Drafts Found"";}"
response.write vbCrLf & "            for(const obj of cleanDrafts){"
response.write vbCrLf & "                const div = draftTemplate.content.cloneNode(true).querySelector('.draft');"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{order-id}',obj.id);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{customer-name}',obj.customerName);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{total-price}',obj.totalPrice);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{total-qty}',obj.totalQty);"
response.write vbCrLf & "                div.innerHTML = div.innerHTML.replace('{total-no}',obj.totalNo);"
response.write vbCrLf & "                div.addEventListener('click',function(){"
response.write vbCrLf & "                    loadOrderFromObj(obj);"
response.write vbCrLf & "                    if(paymentMode){"
response.write vbCrLf & "                        paymentMode.value = obj.paymentMode;"
response.write vbCrLf & "                        paymentMode.dispatchEvent(new Event('change'));"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                })"
response.write vbCrLf & "                draftContainer.appendChild(div);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            localStorage.setItem('mini-mart-drafts',JSON.stringify(cleanDrafts));"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadSales(){"
response.write vbCrLf & "            const salesContainer = document.querySelector('.sales');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETSALES'"
response.write vbCrLf & "            let filterItems = '';"
response.write vbCrLf & "            if(saleAttendant.value) filterItems += '&sale-attendant=' + saleAttendant.value;"
response.write vbCrLf & "            if(fromElement) filterItems += '&from=' + fromElement.value;"
response.write vbCrLf & "            if(toElement) filterItems += '&to=' + toElement.value;"
response.write vbCrLf & "            endpoint += filterItems;"
response.write vbCrLf & "            salesContainer.innerHTML = '';"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            fetch(endpoint).then(res=>{"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                return res.json();"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                if(data){"
response.write vbCrLf & "                    const obj = data;"
response.write vbCrLf & "                    const sale = saleTemplate.content.cloneNode('true').querySelector('.sale');"
response.write vbCrLf & "                    const sale1 = saleTemplate.content.cloneNode('true').querySelector('.sale-1');"
response.write vbCrLf & "                    sale.innerHTML = sale.innerHTML.replace('{from}',obj.from??'-');"
response.write vbCrLf & "                    sale.innerHTML = sale.innerHTML.replace('{to}',obj.to??'-');"
response.write vbCrLf & "                    sale.innerHTML = sale.innerHTML.replace('{total-amt}',formatNumberToMoney(obj.totalamt)??'-');"
response.write vbCrLf & "                    sale.innerHTML = sale.innerHTML.replace('{cash-amt}',formatNumberToMoney(obj.cashamt)??'-');"
response.write vbCrLf & "                    sale.innerHTML = sale.innerHTML.replace('{momo-amt}',formatNumberToMoney(obj.momoamt)??'-');"
response.write vbCrLf & "                    sale.innerHTML = sale.innerHTML.replace('{attendant}',obj.attendant??'-');"
response.write vbCrLf & "                    const cashPer = sale.querySelector('#cash-per');"
response.write vbCrLf & "                    cashPer.style.width = obj.cashamt / obj.totalamt * 100 + '%';"
response.write vbCrLf & "                    const momoPer = sale.querySelector('#momo-per');"
response.write vbCrLf & "                    momoPer.style.width = obj.momoamt / obj.totalamt * 100 + '%';"
response.write vbCrLf & "                    sale1.innerHTML = sale1.innerHTML.replace('{total-sales}',formatNumberToMoney(obj.totalsales)??'-');"
response.write vbCrLf & "                    sale1.innerHTML = sale1.innerHTML.replace('{total-qty}',formatNumberToMoney(obj.totalqty)??'-');"
response.write vbCrLf & "                    sale.addEventListener('click',function(){"
response.write vbCrLf & "                        window.open(salesHref+filterItems,'_blank','width=800px,height=900px');"
response.write vbCrLf & "                    })"
response.write vbCrLf & "                    sale1.addEventListener('click',function(){"
response.write vbCrLf & "                        window.open(salesHref+filterItems,'_blank','width=800px,height=900px');"
response.write vbCrLf & "                    })"
response.write vbCrLf & "                    salesContainer.appendChild(sale);"
response.write vbCrLf & "                    salesContainer.appendChild(sale1);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>console.error(e))"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function loadAttendants(){"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETATTENDANTS'"
response.write vbCrLf & "            saleAttendant.innerHTML = '<option value=""ALL"">ALL</option>';"
response.write vbCrLf & "            fetch(endpoint).then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                for(const obj of data){"
response.write vbCrLf & "                    const option = document.createElement('option');"
response.write vbCrLf & "                    option.value = obj.attendantid;"
response.write vbCrLf & "                    option.innerText = obj.attendantname;"
response.write vbCrLf & "                    saleAttendant.appendChild(option);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>console.error(e));"
response.write vbCrLf & "        }"
response.write vbCrLf & "        window.addEventListener('load',function(){"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const miniMartLinks = document.querySelectorAll('#mini-mart-nav-links li');"
response.write vbCrLf & "            const contentHolders = document.querySelectorAll('.dynamic-content>div');"
response.write vbCrLf & "            categories.style.display = 'grid';"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            customerName.value = 'IMAH Customer';"
response.write vbCrLf & "            loadAttendants();"
response.write vbCrLf & "            loadStore();"
response.write vbCrLf & "            loadDrafts();"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            miniMartItems.style.display = 'none';"
response.write vbCrLf & "            filterBtn.onclick = loadSales;"
response.write vbCrLf & "            searchItemElement.oninput = searchForStore;"
response.write vbCrLf & "            if(miniMartLinks){"
response.write vbCrLf & "                for(const el of [...miniMartLinks]){"
response.write vbCrLf & "                    el.addEventListener('click',function(){"
response.write vbCrLf & "                        contentHolders.forEach(ele=>{"
response.write vbCrLf & "                            ele.style.display='none';"
response.write vbCrLf & "                            if(ele.getAttribute('for')===el.id){"
response.write vbCrLf & "                                ele.style.display = 'grid';"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        });"
response.write vbCrLf & "                        const prevActiveLink = document.querySelector('.active');"
response.write vbCrLf & "                        if(prevActiveLink){"
response.write vbCrLf & "                            prevActiveLink.classList.remove('active');"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        el.classList.add('active');"
response.write vbCrLf & "                        searchItemElement.value = """";"
response.write vbCrLf & "                        if(el.id===""store-link""){"
response.write vbCrLf & "                            searchItemElement.oninput = searchForStore;"
response.write vbCrLf & "                            hideFilter(true);"
response.write vbCrLf & "                            disableSearch(false);"
response.write vbCrLf & "                            loadStore();"
response.write vbCrLf & "                        }else if(el.id===""draft-link""){"
response.write vbCrLf & "                            disableSearch(true);"
response.write vbCrLf & "                            hideFilter(true);"
response.write vbCrLf & "                            loadDrafts();"
response.write vbCrLf & "                        }else if(el.id===""receipt-link""){"
response.write vbCrLf & "                            hideFilter(true);"
response.write vbCrLf & "                            searchItemElement.oninput = loadReceipts;"
response.write vbCrLf & "                            disableSearch(false);"
response.write vbCrLf & "                            loadReceipts();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        else if(el.id===""invoice-link""){"
response.write vbCrLf & "                            hideFilter(true);"
response.write vbCrLf & "                            searchItemElement.oninput = loadInvoices;"
response.write vbCrLf & "                            disableSearch(false);"
response.write vbCrLf & "                            loadInvoices();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        else if(el.id===""sales-link""){"
response.write vbCrLf & "                            hideFilter(false);"
response.write vbCrLf & "                            disableSearch(true);"
response.write vbCrLf & "                            loadSales();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                    })"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "            paymentMode.addEventListener('change',function(){"
response.write vbCrLf & "                if(paymentMode.value === ""cash""){"
response.write vbCrLf & "                    processOrderBtn.innerText = ""Process"";"
response.write vbCrLf & "                    processOrderBtn.removeEventLi"
response.write vbCrLf & "                    processOrderBtn.onclick = processOrder;"
response.write vbCrLf & "                }else if(paymentMode.value === ""invoice""){"
response.write vbCrLf & "                    processOrderBtn.innerText = ""Issue Invoice"";"
response.write vbCrLf & "                    processOrderBtn.onclick = issueInvoice;"
response.write vbCrLf & "                }"
response.write vbCrLf & "            });"
response.write vbCrLf & "            saveDraftBtn.onclick = saveAsDraft;"
response.write vbCrLf & "            paymentMode.dispatchEvent(new Event('change'));"
response.write vbCrLf & "        })"
response.write vbCrLf & "        function hideFilter(bool){"
response.write vbCrLf & "            bool?salesFilter.classList.remove('flex'):salesFilter.classList.add('flex');"
response.write vbCrLf & "        }"
response.write vbCrLf & ""
response.write vbCrLf & "        function searchForStore(){"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            const searchString = searchItemElement.value;"
response.write vbCrLf & "            if(searchString?.length>0){"
response.write vbCrLf & "                categories.style.display = 'none';"
response.write vbCrLf & "                miniMartItems.style.display = 'grid';"
response.write vbCrLf & "                searchItem(searchString);"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                categories.style.display = 'grid';"
response.write vbCrLf & "                miniMartItems.style.display = 'none';"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function openCategoryForItems(cat){"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETITEMSFROMCAT';"
response.write vbCrLf & "            endpoint += '&cat=' + cat;"
response.write vbCrLf & "            showLoader(true);"
response.write vbCrLf & "            categories.style.display = 'none';"
response.write vbCrLf & "            miniMartItems.style.display = 'grid';"
response.write vbCrLf & "            miniMartItems.innerHTML = '';"
response.write vbCrLf & "            fetch(endpoint)"
response.write vbCrLf & "            .then(res=>{"
response.write vbCrLf & "                showLoader(false);"
response.write vbCrLf & "                return res.json();"
response.write vbCrLf & "            }).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    itemList = data;"
response.write vbCrLf & "                    for(const obj of itemList){"
response.write vbCrLf & "                        const miniMartItem = miniMartTemplate.content.cloneNode(true).getElementById('mini-mart-item');"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-name}',obj.itemname);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-price}',obj.itemprice);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-qty}',obj.itemqty);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{itemid}',obj.itemid);"
response.write vbCrLf & "                        const miniMartItemCheck = miniMartItem.querySelector('input[type=""checkbox""]');"
response.write vbCrLf & "                        miniMartItem.addEventListener('click',function(){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        const orderTable = document.querySelector('#item-order-list');"
response.write vbCrLf & "                        const orderItem = orderTable?.querySelector('[id=""'+obj.itemid+'""]');"
response.write vbCrLf & "                        miniMartItemCheck.style.pointerEvents = 'none';"
response.write vbCrLf & "                        miniMartItemCheck.addEventListener('change',function(){"
response.write vbCrLf & "                            if(miniMartItemCheck.checked){"
response.write vbCrLf & "                                miniMartItem.classList.add('item-selected');"
response.write vbCrLf & "                                addOrderItem(obj.itemid)"
response.write vbCrLf & "                            }else{"
response.write vbCrLf & "                                miniMartItem.classList.remove('item-selected');"
response.write vbCrLf & "                                removeOrderItem(obj.itemid);"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItems.appendChild(miniMartItem);"
response.write vbCrLf & "                        if(orderItem){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    miniMartItems.innerHTML = 'No Item found';"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.error(e)})"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function searchItem(sn){"
response.write vbCrLf & "            const miniMartItems = document.getElementById('mini-mart-items');"
response.write vbCrLf & "            const categories = document.getElementById('categories');"
response.write vbCrLf & "            let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=SEARCH';"
response.write vbCrLf & "            endpoint += '&item=' + sn;"
response.write vbCrLf & "            controller.abort();"
response.write vbCrLf & "            controller = new AbortController();"
response.write vbCrLf & "            const signal = controller.signal;"
response.write vbCrLf & "            miniMartItems.innerHTML = 'Loading....';"
response.write vbCrLf & "            fetch(endpoint,{signal})"
response.write vbCrLf & "            .then(res=>res.json()).then(data=>{"
response.write vbCrLf & "                if(data.length>0){"
response.write vbCrLf & "                    categories.style.display = 'none';"
response.write vbCrLf & "                    miniMartItems.style.display = 'grid';"
response.write vbCrLf & "                    miniMartItems.innerHTML = '';"
response.write vbCrLf & "                    itemList = data;"
response.write vbCrLf & "                    for(const obj of itemList){"
response.write vbCrLf & "                        const miniMartItem = miniMartTemplate.content.cloneNode(true).getElementById('mini-mart-item');"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-name}',obj.itemname);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-price}',obj.itemprice);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{item-qty}',obj.itemqty);"
response.write vbCrLf & "                        miniMartItem.innerHTML = miniMartItem.innerHTML.replace('{itemid}',obj.itemid);"
response.write vbCrLf & "                        const miniMartItemCheck = miniMartItem.querySelector('input[type=""checkbox""]');"
response.write vbCrLf & "                        miniMartItem.addEventListener('click',function(){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        });"
response.write vbCrLf & "                        const orderTable = document.querySelector('#item-order-list');"
response.write vbCrLf & "                        const orderItem = orderTable?.querySelector('[id=""'+obj.itemid+'""]');"
response.write vbCrLf & "                        miniMartItemCheck.style.pointerEvents = 'none';"
response.write vbCrLf & "                        miniMartItemCheck.addEventListener('change',function(){"
response.write vbCrLf & "                            if(miniMartItemCheck.checked){"
response.write vbCrLf & "                                miniMartItem.classList.add('item-selected');"
response.write vbCrLf & "                                addOrderItem(obj.itemid)"
response.write vbCrLf & "                            }else{"
response.write vbCrLf & "                                miniMartItem.classList.remove('item-selected');"
response.write vbCrLf & "                                removeOrderItem(obj.itemid);"
response.write vbCrLf & "                            }"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        miniMartItems.appendChild(miniMartItem);"
response.write vbCrLf & "                        if(orderItem){"
response.write vbCrLf & "                            miniMartItemCheck.click();"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }else{"
response.write vbCrLf & "                    miniMartItems.innerHTML = 'No Item found';"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }).catch(e=>{console.error(e)})"
response.write vbCrLf & "        }"
response.write vbCrLf & "           function removeOrderItem(itemid){"
response.write vbCrLf & "                const orderTable = document.getElementById('item-order-list');"
response.write vbCrLf & "                if(typeof itemid === ""string""){"
response.write vbCrLf & "                    const item = document.getElementById(itemid)"
response.write vbCrLf & "                    if(item){"
response.write vbCrLf & "                        const tr = item.closest('tr');"
response.write vbCrLf & "                        tr?.remove();"
response.write vbCrLf & "                        recalculate();"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        function addOrderItem(itemid){"
response.write vbCrLf & "            if(typeof itemid === ""string""){"
response.write vbCrLf & "                const item = document.getElementById(itemid)"
response.write vbCrLf & "                if(!item){"
response.write vbCrLf & "                    const itemObj = itemList.find(el=>el.itemid===itemid);"
response.write vbCrLf & "                    addToTable(itemObj);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function addToTable(itemObj){"
response.write vbCrLf & "           const orderTable = document.querySelector('#item-order-list');"
response.write vbCrLf & "           const orderSection = document.querySelector('#order-list');"
response.write vbCrLf & "           if(typeof itemObj === ""object""){"
response.write vbCrLf & "               if(orderTable && !orderSection.classList.contains('read-only')){"
response.write vbCrLf & "                   if(!orderTable.querySelector('[id=""'+itemObj.itemid+'""]')){"
response.write vbCrLf & "                       const orderTbody = orderTable.querySelector('tbody');"
response.write vbCrLf & "                       const tr = document.createElement('tr');"
response.write vbCrLf & "                       const td = document.createElement('td');"
response.write vbCrLf & "                       td.id = itemObj.itemid;"
response.write vbCrLf & "                       td.innerText = itemObj.itemname;"
response.write vbCrLf & "                       td.className = itemObj.itemname;"
response.write vbCrLf & "                       const td2 = document.createElement('td');"
response.write vbCrLf & "                       td2.id = itemObj.itemid + ""-qty"";"
response.write vbCrLf & "                       td2.innerText = itemObj.itemqty??'-';"
response.write vbCrLf & "                       td2.className = itemObj.itemqty??'-';"
response.write vbCrLf & "                       const td3 = document.createElement('td');"
response.write vbCrLf & "                       const input = document.createElement('input');"
response.write vbCrLf & "                       input.type = 'number';"
response.write vbCrLf & "                       input.id = itemObj.itemid + ""-inp-qty"";"
response.write vbCrLf & "                       input.style.width = '60px';"
response.write vbCrLf & "                       input.addEventListener('input',function(){"
response.write vbCrLf & "                           const itemPrice = document.getElementById(itemObj.itemid + ""-price"");"
response.write vbCrLf & "                           if(input.value){"
response.write vbCrLf & "                               const qty = parseFloat(input.value);"
response.write vbCrLf & "                               const totalPrice = qty * itemObj.itemprice;"
response.write vbCrLf & "                               if(itemPrice){"
response.write vbCrLf & "                                   itemPrice.className = totalPrice;"
response.write vbCrLf & "                                   itemPrice.innerText = totalPrice;"
response.write vbCrLf & "                                   recalculate();"
response.write vbCrLf & "                               }"
response.write vbCrLf & "                           }"
response.write vbCrLf & "                       })"
response.write vbCrLf & "                       td3.appendChild(input);"
response.write vbCrLf & "                       const td4 = document.createElement('td');"
response.write vbCrLf & "                       td4.id = itemObj.itemid + ""-price"";"
response.write vbCrLf & "                       td4.innerText = itemObj.itemprice;"
response.write vbCrLf & "                       td4.setAttribute('original-qty', itemObj.itemprice);"
response.write vbCrLf & "                       td4.className = itemObj.itemprice;"
response.write vbCrLf & "                       const td5 = document.createElement('td');"
response.write vbCrLf & "                       td5.innerText = 'X';"
response.write vbCrLf & "                       td5.className = 'remove-row';"
response.write vbCrLf & "                       td5.addEventListener('click',function(){"
response.write vbCrLf & "                           tr.remove();"
response.write vbCrLf & "                           recalculate();"
response.write vbCrLf & "                       });"
response.write vbCrLf & "                       tr.appendChild(td);"
response.write vbCrLf & "                       tr.appendChild(td2);"
response.write vbCrLf & "                       tr.appendChild(td3);"
response.write vbCrLf & "                       tr.appendChild(td4);"
response.write vbCrLf & "                       tr.appendChild(td5);"
response.write vbCrLf & "                       orderTbody.appendChild(tr);"
response.write vbCrLf & "                       input.value = itemObj.issueqty??1;"
response.write vbCrLf & "                       input.dispatchEvent(new Event('input'));"
response.write vbCrLf & "                       recalculate();"
response.write vbCrLf & "                   }"
response.write vbCrLf & "               }"
response.write vbCrLf & "           }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function recalculate(){"
response.write vbCrLf & "            const qtyList = document.querySelectorAll('[id$=""-inp-qty""]');"
response.write vbCrLf & "            const priceList = document.querySelectorAll('[id$=""-price""]');"
response.write vbCrLf & "            if(qtyList.length>=0 && priceList.length>=0){"
response.write vbCrLf & "                itemNoElement.innerText = qtyList.length;"
response.write vbCrLf & "                itemQtyElement.innerText = [...qtyList].map(el=>parseFloat(el.value||'0')).reduce((acc,c)=>acc+c,0);"
response.write vbCrLf & "                itemPriceElement.innerText = [...priceList].map(el=>parseFloat(el.className||'0')).reduce((acc,c)=>acc+c,0);"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function returnDrug(drugsaleid){"
response.write vbCrLf & "            return function(){"
response.write vbCrLf & "                let endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=GETRECEIPTITEM';"
response.write vbCrLf & "                endpoint += '&drugsaleid=' + drugsaleid;"
response.write vbCrLf & "                showLoader(true);"
response.write vbCrLf & "                fetch(endpoint).then(res=>{"
response.write vbCrLf & "                    showLoader(false);"
response.write vbCrLf & "                    return res.json();"
response.write vbCrLf & "                }).then(data=>{"
response.write vbCrLf & "                    if(data.success){"
response.write vbCrLf & "                        const obj = data[""data""];"
response.write vbCrLf & "                        loadOrderFromObj(obj);"
response.write vbCrLf & "                        const orderSection = document.getElementById('order-list');"
response.write vbCrLf & "                        if(orderSection){"
response.write vbCrLf & "                            orderSection.classList.add('read-only');"
response.write vbCrLf & "                            orderSection.classList.add('partial');"
response.write vbCrLf & "                        }"
response.write vbCrLf & "                        drugSaleElement.value = obj[""drugsaleid""]??'';"
response.write vbCrLf & "                        saveDraftBtn.innerText = 'Cancel';"
response.write vbCrLf & "                        processOrderBtn.innerText = 'Return'"
response.write vbCrLf & "                        saveDraftBtn.onclick = resetOrder;"
response.write vbCrLf & "                        processOrderBtn.onclick = processReturnDrug;"
response.write vbCrLf & "                    }"
response.write vbCrLf & "                })"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function connect(){"
response.write vbCrLf & "            this.socket = new WebSocket('ws://172.19.0.36:9000/');"
response.write vbCrLf & "            this.messageQueue = [];"
response.write vbCrLf & "            this.isOpen = false;"
response.write vbCrLf & "            this.socket.addEventListener(""open"", () => {"
response.write vbCrLf & "                console.log(""Connected "");"
response.write vbCrLf & "                this.isOpen = true;"
response.write vbCrLf & "                while (this.messageQueue.length > 0) {"
response.write vbCrLf & "                    const message = this.messageQueue.shift();"
response.write vbCrLf & "                    _safeSend(message);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            });"
response.write vbCrLf & ""
response.write vbCrLf & "            this.socket.addEventListener(""message"", (event) => {"
response.write vbCrLf & "                const message = JSON.parse(event.data);"
response.write vbCrLf & "                console.log(message)"
response.write vbCrLf & "                if(message.event===""order-done""){"
response.write vbCrLf & "                    if(message.data) saveDraft(message.data);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            });"
response.write vbCrLf & ""
response.write vbCrLf & "            this.socket.addEventListener(""close"", (event) => {"
response.write vbCrLf & "                console.warn("" Disconnected:"", event.reason);"
response.write vbCrLf & "                this.isOpen = false;"
response.write vbCrLf & "                connect();"
response.write vbCrLf & "            });"
response.write vbCrLf & ""
response.write vbCrLf & "            this.socket.addEventListener(""error"", (error) => {"
response.write vbCrLf & "                console.error("" Error:"", error);"
response.write vbCrLf & "            });"
response.write vbCrLf & "            this._safeSend = (data) =>{"
response.write vbCrLf & "                if (this.isOpen && this.socket.readyState === WebSocket.OPEN) {"
response.write vbCrLf & "                    this.socket.send(data);"
response.write vbCrLf & "                } else {"
response.write vbCrLf & "                    console.warn(""[WebSocket] Tried to send but socket not ready, queueing."");"
response.write vbCrLf & "                    this.messageQueue.push(data);"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & ""
response.write vbCrLf & "            this.send = (event, data) =>{"
response.write vbCrLf & "                const message = JSON.stringify({ event, data });"
response.write vbCrLf & "                _safeSend(message);"
response.write vbCrLf & "            }"
response.write vbCrLf & ""
response.write vbCrLf & "            this.close = () => {"
response.write vbCrLf & "                socket.close();"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function saveDraft(obj){"
response.write vbCrLf & "            let drafts = []"
response.write vbCrLf & "            const prevDrafts = localStorage.getItem('mini-mart-drafts');"
response.write vbCrLf & "            if(prevDrafts){"
response.write vbCrLf & "                drafts = JSON.parse(prevDrafts);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            const cleanDrafts = drafts.filter(obj=>{"
response.write vbCrLf & "                return obj.exp >= Date.now();"
response.write vbCrLf & "            })"
response.write vbCrLf & "            const JSONOrder = obj;"
response.write vbCrLf & "            if(JSONOrder){"
response.write vbCrLf & "                JSONOrder.exp = Date.now() + (7*24*60*60*1000);"
response.write vbCrLf & "                cleanDrafts.unshift(JSONOrder);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            localStorage.setItem('mini-mart-drafts',JSON.stringify(cleanDrafts));"
response.write vbCrLf & "            loadDrafts()"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function processReturnDrug(){"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=RETURNITEM';"
response.write vbCrLf & "            const JSONBody = buildJSON();"
response.write vbCrLf & "            if(JSONBody){"
response.write vbCrLf & "                    const ok = confirm('are you sure you want to proceed with drug return');"
response.write vbCrLf & "                    if(ok){"
response.write vbCrLf & "                        showLoader(true);"
response.write vbCrLf & "                        fetch(endpoint,{"
response.write vbCrLf & "                        method:""POST"","
response.write vbCrLf & "                        body:JSON.stringify(JSONBody)"
response.write vbCrLf & "                        })"
response.write vbCrLf & "                        .then(res=>{"
response.write vbCrLf & "                        showLoader(false);"
response.write vbCrLf & "                        return res.json();"
response.write vbCrLf & "                        }).then(data=>{"
response.write vbCrLf & "                            if(data.success){ "
response.write vbCrLf & "                                alert(data.message);"
response.write vbCrLf & "                                resetOrder();"
response.write vbCrLf & "                            }else{ "
response.write vbCrLf & "                                alert(data.message); "
response.write vbCrLf & "                            } "
response.write vbCrLf & "                        }).catch(e=>{alert('Something went wrong');})"
response.write vbCrLf & "                }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function formatNumberToMoney(number) {"
response.write vbCrLf & "            return number.toLocaleString('en-US', {"
response.write vbCrLf & "                minimumFractionDigits: 2,"
response.write vbCrLf & "                maximumFractionDigits: 2"
response.write vbCrLf & "            });"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function buildJSON(){"
response.write vbCrLf & "            const orderJSON = {};"
response.write vbCrLf & "            if(!/^[aA-zZ]{2,}\s[aA-zZ]{2,}$/.test(customerName.value)){"
response.write vbCrLf & "                customerName.classList.add('error');"
response.write vbCrLf & "                return null;"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                customerName.classList.remove('error');"
response.write vbCrLf & "            }"
response.write vbCrLf & "            if(drugSaleElement.value){"
response.write vbCrLf & "                orderJSON.drugsaleid = drugSaleElement.value;"
response.write vbCrLf & "            }"
response.write vbCrLf & "            if(orderIdElement.value){"
response.write vbCrLf & "                orderJSON.id = orderIdElement.value;"
response.write vbCrLf & "            }else{"
response.write vbCrLf & "                orderJSON.id = generateID();"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.customerName = customerName.value;"
response.write vbCrLf & "            if(receiptElement.value){"
response.write vbCrLf & "                orderJSON.receiptno = receiptElement.value;"
response.write vbCrLf & "            }"
response.write vbCrLf & "            if(!paymentMode.value){"
response.write vbCrLf & "                return null;"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.paymentMode = paymentMode.value;"
response.write vbCrLf & "            const orderTable = document.getElementById('item-order-list');"
response.write vbCrLf & "            const tbody = orderTable.querySelector('tbody');"
response.write vbCrLf & "            const list = tbody.querySelectorAll('tr');"
response.write vbCrLf & "            if(list.length === 0){"
response.write vbCrLf & "                alert('no item selected');"
response.write vbCrLf & "                return null;"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.orderitems = []"
response.write vbCrLf & "            for(const tr of [...list]){"
response.write vbCrLf & "                const obj = {}"
response.write vbCrLf & "                const itemIdElement = tr.querySelector('td');"
response.write vbCrLf & "                obj.itemid = itemIdElement.id;"
response.write vbCrLf & "                obj.itemname = itemIdElement.className;"
response.write vbCrLf & "                const itemQtyElement = tr.querySelector('[id$=""-inp-qty""]');"
response.write vbCrLf & "                obj.issueqty = parseFloat(itemQtyElement.value||""0"");"
response.write vbCrLf & "                const itemPrice = tr.querySelector('[id$=""-price""]');"
response.write vbCrLf & "                obj.itemprice = parseFloat(itemPrice.getAttribute('original-qty')||""0"");"
response.write vbCrLf & "                orderJSON.orderitems.push(obj);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            orderJSON.totalNo = itemNoElement.innerText.trim()||0;"
response.write vbCrLf & "            orderJSON.totalPrice = itemPriceElement.innerText.trim()||0;"
response.write vbCrLf & "            orderJSON.totalQty = itemQtyElement.innerText.trim()||0;"
response.write vbCrLf & "            return orderJSON;"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function processOrder(){"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=PROCESSORDER';"
response.write vbCrLf & "            const JSONBody = buildJSON();"
response.write vbCrLf & "            if(JSONBody){"
response.write vbCrLf & "                const ok = confirm('are you sure you want to proceed');"
response.write vbCrLf & "                if(ok){"
response.write vbCrLf & "                   showLoader(true);"
response.write vbCrLf & "                   fetch(endpoint,{"
response.write vbCrLf & "                       method:""POST"","
response.write vbCrLf & "                       body:JSON.stringify(JSONBody)"
response.write vbCrLf & "                   })"
response.write vbCrLf & "                   .then(res=>{"
response.write vbCrLf & "                        showLoader(false);"
response.write vbCrLf & "                        return res.json();"
response.write vbCrLf & "                    }).then(data=>{"
response.write vbCrLf & "                          if(data.success){ "
response.write vbCrLf & "                              alert(data.message); "
response.write vbCrLf & "                              cleanOrderDraft(JSONBody.id);"
response.write vbCrLf & "                              window.open(receiptHref+data.drugsaleid+'&receiptid='+data.receiptid,'_blank','width=800px,height=900px'); "
response.write vbCrLf & "                              resetOrder();"
response.write vbCrLf & "                          }else{ "
response.write vbCrLf & "                              alert(data.message); "
response.write vbCrLf & "                          } "
response.write vbCrLf & "                   }).catch(e=>{alert('Something went wrong');})"
response.write vbCrLf & "               }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & ""
response.write vbCrLf & "        function issueInvoice(){"
response.write vbCrLf & "            const endpoint = 'wpgXMLHTTP.asp?procedurename=MiniMart&operation=ISSUEINVOICE';"
response.write vbCrLf & "            const JSONBody = buildJSON();"
response.write vbCrLf & "            if(JSONBody){"
response.write vbCrLf & "                const ok = confirm('Issue invoice!, are you sure you want to proceed');"
response.write vbCrLf & "                if(ok){"
response.write vbCrLf & "                   showLoader(true);"
response.write vbCrLf & "                   fetch(endpoint,{"
response.write vbCrLf & "                       method:""POST"","
response.write vbCrLf & "                       body:JSON.stringify(JSONBody)"
response.write vbCrLf & "                   }).then(res=>{"
response.write vbCrLf & "                        showLoader(false);"
response.write vbCrLf & "                        return res.json();"
response.write vbCrLf & "                    }).then(data=>{"
response.write vbCrLf & "                          if(data.success){ "
response.write vbCrLf & "                              alert(data.message);"
response.write vbCrLf & "                              cleanOrderDraft(JSONBody.id);"
response.write vbCrLf & "                              resetOrder();"
response.write vbCrLf & "                          }else{ "
response.write vbCrLf & "                              alert(data.message); "
response.write vbCrLf & "                          } "
response.write vbCrLf & "                   }).catch(e=>{alert('Something went wrong');})"
response.write vbCrLf & "               }"
response.write vbCrLf & "            }"
response.write vbCrLf & "        }"
response.write vbCrLf & "        function saveInvoice(data){"
response.write vbCrLf & "            let invoices = [];"
response.write vbCrLf & "            const prevInvoices = localStorage.getItem('mini-mart-invoices');"
response.write vbCrLf & "            if(prevInvoices){"
response.write vbCrLf & "                invoices = JSON.parse(prevInvoices);"
response.write vbCrLf & "            }"
response.write vbCrLf & "            const cleanInvoices = invoices.filter(obj=>{"
response.write vbCrLf & "                return obj.exp >= Date.now();"
response.write vbCrLf & "            })"
response.write vbCrLf & "            if(data){"
response.write vbCrLf & "                data.exp = Date.now() + (7*24*60*60*1000);"
response.write vbCrLf & "                cleanInvoices.unshift(data);"
response.write vbCrLf & "                resetOrder();"
response.write vbCrLf & "            }"
response.write vbCrLf & "            localStorage.setItem('mini-mart-invoices',JSON.stringify(cleanInvoices));"
response.write vbCrLf & "        }"
response.write vbCrLf & "       function saveAsDraft(){"
response.write vbCrLf & "           let drafts = []"
response.write vbCrLf & "           const prevDrafts = localStorage.getItem('mini-mart-drafts');"
response.write vbCrLf & "           if(prevDrafts){"
response.write vbCrLf & "               drafts = JSON.parse(prevDrafts);"
response.write vbCrLf & "           }"
response.write vbCrLf & "           const cleanDrafts = drafts.filter(obj=>{"
response.write vbCrLf & "               return obj.exp >= Date.now();"
response.write vbCrLf & "           })"
response.write vbCrLf & "           const JSONOrder = buildJSON();"
response.write vbCrLf & "           if(JSONOrder){"
response.write vbCrLf & "               JSONOrder.exp = Date.now() + (7*24*60*60*1000);"
response.write vbCrLf & "               cleanDrafts.unshift(JSONOrder);"
response.write vbCrLf & "               alert('saved to Draft');"
response.write vbCrLf & "               resetOrder();"
response.write vbCrLf & "           }"
response.write vbCrLf & "           localStorage.setItem('mini-mart-drafts',JSON.stringify(cleanDrafts));"
response.write vbCrLf & "       }"
response.write vbCrLf & "       function resetOrder(){"
response.write vbCrLf & "           if(customerName){"
response.write vbCrLf & "               customerName.value = ""IMAH Customer"";"
response.write vbCrLf & "           }"
response.write vbCrLf & "           const orderTable = document.getElementById('item-order-list');"
response.write vbCrLf & "           const tbody = orderTable.querySelector('tbody');"
response.write vbCrLf & "           if(tbody){"
response.write vbCrLf & "               tbody.innerHTML = """";"
response.write vbCrLf & "           }"
response.write vbCrLf & "           paymentMode.value = ""cash"";"
response.write vbCrLf & "           const orderSection = document.getElementById('order-list');"
response.write vbCrLf & "            receiptElement.value = """";"
response.write vbCrLf & "            orderSection.classList.remove('read-only');"
response.write vbCrLf & "            orderSection.classList.remove('partial');"
response.write vbCrLf & "            saveDraftBtn.innerText = 'Save as Draft';"
response.write vbCrLf & "            saveDraftBtn.onclick = saveAsDraft;"
response.write vbCrLf & "            processOrderBtn.innerText = 'Process';"
response.write vbCrLf & "            processOrderBtn.onclick = processOrder;"
response.write vbCrLf & "           recalculate();"
response.write vbCrLf & "       }"
response.write vbCrLf & "       function loadOrderFromObj(obj){"
response.write vbCrLf & "           if(obj){"
response.write vbCrLf & "               resetOrder();"
response.write vbCrLf & "               if(customerName){"
response.write vbCrLf & "                   customerName.value = obj.customerName;"
response.write vbCrLf & "               }"
response.write vbCrLf & "               if(obj.drugsaleid){"
response.write vbCrLf & "                  drugSaleElement.value = obj.drugsaleid;"
response.write vbCrLf & "               }"
response.write vbCrLf & "               if(obj.id){"
response.write vbCrLf & "                  orderIdElement.value = obj.id;"
response.write vbCrLf & "               }"
response.write vbCrLf & "               for(const itemObj of obj.orderitems){"
response.write vbCrLf & "                   addToTable(itemObj);"
response.write vbCrLf & "               }"
response.write vbCrLf & "           }"
response.write vbCrLf & "       }"
response.write vbCrLf & "       function generateID() {"
response.write vbCrLf & "           const prefix = 'IMAH';"
response.write vbCrLf & "           let numbers = '';"
response.write vbCrLf & "           for (let i = 0; i < 8; i++) {"
response.write vbCrLf & "               numbers += Math.floor(Math.random() * 1e10 % 10); "
response.write vbCrLf & "           }"
response.write vbCrLf & "           return prefix + numbers;"
response.write vbCrLf & "       }"
response.write vbCrLf & "    </script>"
response.write vbCrLf & "</body>"
response.write vbCrLf & "</html>"
response.write vbCrLf & ""
response.write vbCrLf & ""
response.write vbCrLf & ""
response.write vbCrLf & ""
response.write vbCrLf & ""
response.write vbCrLf & ""
response.write vbCrLf & ""







'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
