


INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A', 'Blood Transfusion Record - NEW', 'MM-W007-N007-5', '09', 18, '-', '-**-**-', '?', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-01', 'SECTION I', 'MM-W007-N007-5-19-A', '09', 18, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=NUR110.1&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-02', 'SECTION II', 'MM-W007-N007-5-19-A', '09', 18, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=NUR110.2&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-03', 'SECTION III', 'MM-W007-N007-5-19-A', '09', 18, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=NUR110.3&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-04', 'Blood Transfusion Record - FULL FORM', 'MM-W006-N007-5-19-A', '09', 17, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);




INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A', 'Blood Transfusion Record - NEW', 'MM-W007-N007-5', '09', 20, '-', '-**-**-', '?', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-01', 'SECTION I', 'MM-W007-N007-5-19-A', '09', 20, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=NUR110.1&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-02', 'SECTION II', 'MM-W007-N007-5-19-A', '09', 20, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=NUR110.2&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-03', 'SECTION III', 'MM-W007-N007-5-19-A', '09', 20, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=NUR110.3&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-W007-N007-5-19-A-04', 'Blood Transfusion Record - FULL FORM', 'MM-W006-N007-5-19-A', '09', 19, '-', '-**-**-', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=NUR110&EMRCompTabID=&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankWithdrawStatus', 'USA001', 'IN||NAV||800||600||OPEN', '-', '-', NULL);


                                                                                                                                                                                                                                                                                                                         