INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-8', 'ICU Hourly Chart [Vitals]', 'MM-M0315-N007-5', '09', 8, '-', 'ICU Hourly Chart [Vitals]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096A&EMRCompTabID=RHD096A&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N001', 'BrowseRpt', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-9', 'ICU Hourly Chart [Mode of Ventilation]', 'MM-M0315-N007-5', '09', 9, '-', 'ICU Hourly Chart [Mode of Ventilation]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096B&EMRCompTabID=RHD096B&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'UserAccessible', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-10', 'ICU Hourly Chart [Observation]', 'MM-M0315-N007-5', '09', 10, '-', 'ICU Hourly Chart [Observation]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096C&EMRCompTabID=RHD096C&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N001', 'AdminBrowse', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-11', 'ICU Hourly Chart [Conscious Level]', 'MM-M0315-N007-5', '09', 11, '-', 'ICU Hourly Chart [Conscious Level]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096D&EMRCompTabID=RHD096D&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'Account', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-12', 'ICU Hourly Chart [Intake]', 'MM-M0315-N007-5', '09', 12, '-', 'ICU Hourly Chart [Intake]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096E&EMRCompTabID=RHD096E&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BulkPrintDependTbl', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-13', 'ICU Hourly Chart [Output]', 'MM-M0315-N007-5', '09', 13, '-', 'ICU Hourly Chart [Output]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096F&EMRCompTabID=RHD096F&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'BankCharges', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-14', 'ICU Hourly Chart [Remarks/ Intervention]', 'MM-M0315-N007-5', '09', 14, '-', 'ICU Hourly Chart [Remarks/ Intervention]', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096G&EMRCompTabID=RHD096G&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'PasswordPolicy', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('MM-M0315-N007-5-15', 'ICU Hourly Chart', 'MM-M0315-N007-5', '09', 15, '-', 'ICU Hourly Chart', 'wpgPrtPrintLayoutAll.asp?PositionForTableName=WorkingDay&WorkingDayID=DAY20160401&PrintLayoutName=EMRSelector&EMRDataID=RHD096&EMRCompTabID=RHD096&POSITIONFORQUERYSTRING&CompTableKeyID=EMRComponentID', 'N003', 'AccountStatus', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);


--26/11/2025
INSERT INTO "ItemStore" ("AllowNegativeStockID", "ItemStoreID", "ItemStoreName", "BranchID", "JobScheduleID", "ItemStoreTypeID", "ItemStoreStatusID", "ItemStoreLocationID", "ItemPricePercent", "ContactInfo", "Description", "KeyPrefix") VALUES ('A001', 'ITSupport', 'IT Support', 'B001', 'DPT001', 'I001', 'I001', 'I001', 100, '', '', '');
