'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
Dim SponsorID
addCSS
SponsorID = Trim(Request.QueryString("PrintFilter0"))
processRpt SponsorID
addJS

Sub processRpt(SponsorID)
  Dim pat, vDate
  ' pat = GetComboNameFld("Visitation", SponsorID, "PatientID")
  ' vDate = GetComboNameFld("Visitation", SponsorID, "VisitDate")
  With response
    .write vbCrLf & "<div class='container'>"
    'selectScheme sponsorID, VisitID
    .write vbCrLf & "  <div class='data'>"
    .write vbCrLf & "    <label>Sponsor: <input type='text' value='" & GetComboName("PerformVar22", SponsorID) & "' readonly></label>"
    .write vbCrLf & "    <label>Discount (%): <input type='number' id='discount' min='0' max='100' value='" & getDiscount(SponsorID) & "' onblur='updateDiscount()'></label>"
    .write vbCrLf & "  </div>"
    .write vbCrLf & "  </div>"
    .write vbCrLf & "  <div class='tab_box'>"
    .write vbCrLf & "    <button class='tab_btn active'>Drugs</button>"
    .write vbCrLf & "    <button class='tab_btn'>Items</button>"
    .write vbCrLf & "    <button class='tab_btn'>Investigations</button>"
    .write vbCrLf & "    <button class='tab_btn'>Services</button>"
    .write vbCrLf & "    <div class='line'></div>"
    .write vbCrLf & "  </div>"
    .write vbCrLf & "  <div class='content_box'>"
    .write vbCrLf & "    <div class='content active' id='drgBox'>"
    .write vbCrLf & "    <div id='srhBox'><input type='search' name='qry-search' id='drg-search' class='qry-search' placeholder='Search Drug Item' onkeyup='drgSearch()'></div> "
    .write vbCrLf & "    <div id='drgResult'> "
    .write vbCrLf & "   <h3>Loading ...</h3>"
    'drop
    .write vbCrLf & ""
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    <div class='content' id='itmBox'>"
    .write vbCrLf & "    <div id='srhBox'><input type='search' name='qry-search' id='itm-search' class='qry-search' placeholder='Search Consumable Item' onkeyup='itmSearch()'> </div> "
    .write vbCrLf & "    <div id='itmResult'> "
    .write vbCrLf & "   <h3>Loading ...</h3>"
    'drop
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    <div class='content' id='labBox'>"
    .write vbCrLf & "    <div id='srhBox'><input type='search' name='qry-search' id='lab-search' class='qry-search' placeholder='Search Lab/X-Ray Item' onkeyup='labSearch()'> </div> "
    .write vbCrLf & "    <div id='labResult'> "
    .write vbCrLf & "   <h3>Loading ...</h3>"
    'drop
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    <div class='content' id='trtBox'>"
    .write vbCrLf & "    <div id='srhBox'><input type='search' name='qry-search' id='treat-search' class='qry-search' placeholder='Search Services/Treatment List' onkeyup='treatSearch()'> </div> "
    .write vbCrLf & "    <div id='treatResult'> "
    .write vbCrLf & "   <h3>Loading ...</h3>"
    'drop
    .write vbCrLf & "    </div>"
    .write vbCrLf & "    </div>"

    .write vbCrLf & "  </div>"
    .write vbCrLf & "</div>"
  End With
End Sub


Sub addJS()
  With response
    .write vbCrLf & "<script type='text/javascript'>"
    .write vbCrLf & "  let tabs = document.querySelectorAll('.tab_btn');"
    .write vbCrLf & "  let all_content = document.querySelectorAll('.content');"
    .write vbCrLf & "  tabs.forEach((tab, index) => {"
    .write vbCrLf & "    tab.addEventListener('click', (e) => {"
    .write vbCrLf & "      tabs.forEach(tab => { tab.classList.remove('active') });"
    .write vbCrLf & "      tab.classList.add('active');"
    .write vbCrLf & "      var line = document.querySelector('.line');"
    .write vbCrLf & "      line.style.width = e.target.offsetwidth + 'px';"
    .write vbCrLf & "      line.style.left = e.target.offsetLeft + 'px';"
    .write vbCrLf & "      all_content.forEach(content => { content.classList.remove('active') });"
    .write vbCrLf & "      all_content[index].classList.add('active');"
    .write vbCrLf & "    });"
    .write vbCrLf & "  });"
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "window.addEventListener('change', function(event){"
    .write vbCrLf & "   if(event.target.tagName.toUpperCase() === 'INPUT' && event.target.type.toUpperCase() === 'CHECKBOX'){"
    .write vbCrLf & "     updateLabel(event.target);"
    .write vbCrLf & "     "
    .write vbCrLf & "}"
    .write vbCrLf & "});"
    .write vbCrLf & "function updateLabel(checkbox) {"
    .write vbCrLf & "  const span = checkbox.parentNode.querySelector('span');"
    .write vbCrLf & "  if (checkbox.checked) {"
    .write vbCrLf & "    span.textContent = span.textContent.replace('Add', 'Remove');"
    .write vbCrLf & "  } else {"
    .write vbCrLf & "    span.textContent = span.textContent.replace('Remove', 'Add');"
    .write vbCrLf & "  }"
    .write vbCrLf & "}"
    .write vbCrLf & ""
    .write vbCrLf & "function getTxt(id){"
    .write vbCrLf & "   let txtid = id "
    .write vbCrLf & "   let txtVal = document.getElementById(txtid).value; "
    .write vbCrLf & "   return txtVal; "
    .write vbCrLf & "}"
    .write vbCrLf & ""
    .write vbCrLf & "function DoAjaxUpdate(id) {"
    .write vbCrLf & "  let visitID = '" & SponsorID & "';"
    .write vbCrLf & "  let Qty = id; "
    .write vbCrLf & "  let Qsplt = Qty.split('||'); "
    .write vbCrLf & "  let nqty = Number(getTxt(Qsplt[0])); "

    .write vbCrLf & "  let vst = '" & SponsorID & "';"
    .write vbCrLf & "  UpdateProformaInfo(id, visitID, vst, nqty);"
    .write vbCrLf & "  function UpdateProformaInfo(id, visitID, vst, qty) {"
    .write vbCrLf & "    let url, getStr;"
    .write vbCrLf & "    if (Helpers.len(visitID) > 2) {"
    .write vbCrLf & "      // Determine if this is add or remove based on checkbox state AFTER click"
    .write vbCrLf & "      let checkboxId = id.split('||')[0];"
    .write vbCrLf & "      let checkboxes = document.querySelectorAll('input[type=\""checkbox\""]');"
    .write vbCrLf & "      let checkbox = null;"
    .write vbCrLf & "      for (let i = 0; i < checkboxes.length; i++) {"
    .write vbCrLf & "        if (checkboxes[i].value === checkboxId) {"
    .write vbCrLf & "          checkbox = checkboxes[i];"
    .write vbCrLf & "          break;"
    .write vbCrLf & "        }"
    .write vbCrLf & "      }"
    .write vbCrLf & "      let action = checkbox && checkbox.checked ? 'add' : 'remove';"
    .write vbCrLf & "      "
    .write vbCrLf & "      // Call the appropriate action (add or remove)"
    .write vbCrLf & "      getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=' + action + '&chkedID=' + id;"
    .write vbCrLf & "      getStr = getStr + '&chkQty=' + qty;"
    .write vbCrLf & "      getStr = getStr + '&vst=' + vst;"
    .write vbCrLf & "      url = 'wpgXmlHttp.asp?' + getStr;"
    .write vbCrLf & "      Helpers.xmlhttprequest(Helpers.ucase('GET'), url, UpdatePerformVar58Count);"
    .write vbCrLf & "    }"
    .write vbCrLf & "  }"
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "  function UpdatePerformVar58Count(readyState, responseText) {"
    .write vbCrLf & "    var arr, ul, num, str, rec;"
    .write vbCrLf & "    if (readyState == 4) {"
    .write vbCrLf & "      str = ReplaceXmlHttpComment(responseText);"
    .write vbCrLf & "      arr = Split(str, delim(1));"
    .write vbCrLf & "      ul = UBound(arr);"
    .write vbCrLf & "      if (ul >= 0) {"
    .write vbCrLf & "        rec = Helpers.trim(arr(0));"
    .write vbCrLf & "        if (Helpers.ucase(rec) == Helpers.ucase('True')) {"
    .write vbCrLf & "          // Update successful"
    .write vbCrLf & "        } else {"
    .write vbCrLf & "          // Update failed"
    .write vbCrLf & "        }"
    .write vbCrLf & "      }"
    .write vbCrLf & "    }"
    .write vbCrLf & "  }"
    .write vbCrLf & "}"
    .write vbCrLf & ""
    .write vbCrLf & "  function UpdatePerformVar22Count(readyState, responseText) {"
    .write vbCrLf & "    var arr, ul, num, str, rec;"
    .write vbCrLf & "    if (readyState == 4) {"
    .write vbCrLf & "      str = ReplaceXmlHttpComment(responseText);"
    .write vbCrLf & "      arr = Split(str, delim(1));"
    .write vbCrLf & "      ul = UBound(arr);"
    .write vbCrLf & "      if (ul >= 0) {"
    .write vbCrLf & "        rec = Helpers.trim(arr(0));"
    .write vbCrLf & "        if (Helpers.ucase(rec) == Helpers.ucase('True')) {"
    .write vbCrLf & "        } else {"
    .write vbCrLf & "        }"
    .write vbCrLf & "      }"
    .write vbCrLf & "    }"
    .write vbCrLf & "  }"
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "function getAllDrugs(){ "
    .write vbCrLf & "  let drgContainer = document.getElementById('drgResult'); "
    .write vbCrLf & "  let visitID = '" & SponsorID & "';"
    .write vbCrLf & "  getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=getDrugs&vst=' + visitID; "
    .write vbCrLf & "  url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "  fetch(url) "
    .write vbCrLf & "  .then(response => response.text()) "
    .write vbCrLf & "  .then(data => { "
    .write vbCrLf & "    drgContainer.innerHTML = data; "
    .write vbCrLf & "    loadCheckedStates(); "
    .write vbCrLf & "  }) "
    .write vbCrLf & "  .catch(error => { "
    .write vbCrLf & "  }); "
    .write vbCrLf & "} "
    .write vbCrLf & "getAllDrugs();"
    .write vbCrLf & ""
    .write vbCrLf & "function loadCheckedStates() {"
    .write vbCrLf & "  let visitID = '" & SponsorID & "';"
    .write vbCrLf & "  let getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=getPerformVar22JSON&vst=' + visitID;"
    .write vbCrLf & "  let url = 'wpgXMLHttp.asp?' + getStr;"
    .write vbCrLf & "  fetch(url)"
    .write vbCrLf & "  .then(response => response.text())"
    .write vbCrLf & "  .then(data => {"
    .write vbCrLf & "    try {"
    .write vbCrLf & "      let jsonData = JSON.parse(data);"
    .write vbCrLf & "      applyCheckedStates(jsonData);"
    .write vbCrLf & "    } catch (e) {"
    .write vbCrLf & "    }"
    .write vbCrLf & "  })"
    .write vbCrLf & "  .catch(error => {"
    .write vbCrLf & "  });"
    .write vbCrLf & "}"
    .write vbCrLf & ""
    .write vbCrLf & "function applyCheckedStates(jsonData) {"
    .write vbCrLf & "  for (let key in jsonData) {"
    .write vbCrLf & "    let item = jsonData[key];"
    .write vbCrLf & "    let checkboxId = item.type + '-' + item.id;"
    .write vbCrLf & "    let checkbox = document.querySelector('input[name=' + checkboxId + ']');"
    .write vbCrLf & "    if (checkbox) {"
    .write vbCrLf & "      checkbox.checked = (item.checked === 'true' || item.checked === true);"
    .write vbCrLf & "      updateLabel(checkbox);"
    .write vbCrLf & "    } else {"
    .write vbCrLf & "      // Try alternative selector by value"
    .write vbCrLf & "      let altCheckbox = document.querySelector('input[value=' + checkboxId + ']');"
    .write vbCrLf & "      if (altCheckbox) {"
    .write vbCrLf & "        altCheckbox.checked = (item.checked === 'true' || item.checked === true);"
    .write vbCrLf & "        updateLabel(altCheckbox);"
    .write vbCrLf & "      }"
    .write vbCrLf & "    }"
    .write vbCrLf & "  }"
    .write vbCrLf & "}"
    .write vbCrLf & ""
    .write vbCrLf & "function getAllItems(){ "
    .write vbCrLf & "  let itmContainer = document.getElementById('itmResult'); "
    .write vbCrLf & "  let visitID = '" & SponsorID & "';"
    .write vbCrLf & "  getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=getItems&vst=' + visitID; "
    .write vbCrLf & "  url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "  fetch(url) "
    .write vbCrLf & "  .then(response => response.text()) "
    .write vbCrLf & "  .then(data => { "
    .write vbCrLf & "    itmContainer.innerHTML = data; "
    .write vbCrLf & "    loadCheckedStates(); "
    .write vbCrLf & "  }) "
    .write vbCrLf & "  .catch(error => { "
    .write vbCrLf & "  }); "
    .write vbCrLf & "} "
    .write vbCrLf & "getAllItems();"
    .write vbCrLf & ""
    .write vbCrLf & "function getAllLabs(){ "
    .write vbCrLf & "  let labsContainer = document.getElementById('labResult'); "
    .write vbCrLf & "  let visitID = '" & SponsorID & "';"
    .write vbCrLf & "  getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=getLabs&vst=' + visitID; "
    .write vbCrLf & "  url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "  fetch(url) "
    .write vbCrLf & "  .then(response => response.text()) "
    .write vbCrLf & "  .then(data => { "
    .write vbCrLf & "    labsContainer.innerHTML = data; "
    .write vbCrLf & "    loadCheckedStates(); "
    .write vbCrLf & "  }) "
    .write vbCrLf & "  .catch(error => { "
    .write vbCrLf & "  }); "
    .write vbCrLf & "} "
    .write vbCrLf & "getAllLabs();"
    .write vbCrLf & ""
    .write vbCrLf & "function getAllTreats(){ "
    .write vbCrLf & "  let trtContainer = document.getElementById('treatResult'); "
    .write vbCrLf & "  let visitID = '" & SponsorID & "';"
    .write vbCrLf & "  getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=getTreats&vst=' + visitID; "
    .write vbCrLf & "  url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "  fetch(url) "
    .write vbCrLf & "  .then(response => response.text()) "
    .write vbCrLf & "  .then(data => { "
    .write vbCrLf & "    trtContainer.innerHTML = data; "
    .write vbCrLf & "    loadCheckedStates(); "
    .write vbCrLf & "  }) "
    .write vbCrLf & "  .catch(error => { "
    .write vbCrLf & "  }); "
    .write vbCrLf & "} "
    .write vbCrLf & "getAllTreats();"
    .write vbCrLf & ""
    .write vbCrLf & "function updateDiscount(){ "
    .write vbCrLf & "  const discount = document.getElementById('discount'); "
    .write vbCrLf & "  const discountValue = discount.value; "
    .write vbCrLf & "  let visitID = '" & SponsorID & "'; "
    .write vbCrLf & "  let getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=updateDiscount&discount=' + discountValue + '&vst=' + visitID; "
    .write vbCrLf & "  let url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "  // Remove any existing message "
    .write vbCrLf & "  const existingMessage = document.getElementById('discountMessage'); "
    .write vbCrLf & "  if (existingMessage) { "
    .write vbCrLf & "    existingMessage.remove(); "
    .write vbCrLf & "  } "
    .write vbCrLf & "  "
    .write vbCrLf & "  fetch(url) "
    .write vbCrLf & "  .then(response => response.text()) "
    .write vbCrLf & "  .then(data => { "
    .write vbCrLf & "    // Create a message element "
    .write vbCrLf & "    const messageDiv = document.createElement('div'); "
    .write vbCrLf & "    messageDiv.id = 'discountMessage'; "
    .write vbCrLf & "    messageDiv.innerHTML = data; "
    .write vbCrLf & "    "
    .write vbCrLf & "    // Insert the message after the discount input "
    .write vbCrLf & "    discount.parentNode.insertBefore(messageDiv, discount.nextSibling); "
    .write vbCrLf & "    "
    .write vbCrLf & "    // Auto-remove success message after 3 seconds "
    .write vbCrLf & "    if (data.includes('successfully')) { "
    .write vbCrLf & "      setTimeout(() => { "
    .write vbCrLf & "        if (messageDiv.parentNode) { "
    .write vbCrLf & "          messageDiv.remove(); "
    .write vbCrLf & "        } "
    .write vbCrLf & "      }, 3000); "
    .write vbCrLf & "    } "
    .write vbCrLf & "  }) "
    .write vbCrLf & "  .catch(error => { "
    .write vbCrLf & "    console.error('Error updating discount:', error); "
    .write vbCrLf & "  }); "
    .write vbCrLf & "} "
    .write vbCrLf & ""
    .write vbCrLf & "function drgSearch(){ "
    .write vbCrLf & "  const drgInput = document.getElementById('drg-search'); "
    .write vbCrLf & "  let drgResults = document.getElementById('drgResult'); "
    .write vbCrLf & "  const query = drgInput.value.trim(); "
    .write vbCrLf & "  drgResults.innerHTML = ''; "
    .write vbCrLf & "  if(query !== ''){ makeDrgServerRequest(query); } "
    .write vbCrLf & "  else{ getAllDrugs(); }"
    .write vbCrLf & "} "
    .write vbCrLf & "function makeDrgServerRequest(query){ "
    .write vbCrLf & "  let visitID = '" & SponsorID & "'; "
    .write vbCrLf & "  let drgResults = document.getElementById('drgResult'); "
    .write vbCrLf & "  let getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=searchDrugs&srhDrg=' + encodeURIComponent(query) + '&vst=' + visitID; "
    .write vbCrLf & "  const url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "  fetch(url)  "
    .write vbCrLf & "  .then(response => response.text()) "
    .write vbCrLf & "  .then(data => { "
    .write vbCrLf & "    drgResults.innerHTML = data; "
    .write vbCrLf & "  }) "
    .write vbCrLf & "} "
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "function itmSearch(){ "
    .write vbCrLf & "     const itmInput = document.getElementById('itm-search'); "
    .write vbCrLf & "     const itmResults = document.getElementById('itmResult'); "
    .write vbCrLf & "     const query = itmInput.value.trim(); "
    .write vbCrLf & "     itmResults.innerHTML = ''; "
    .write vbCrLf & "     if(query !== ''){ makeItmServerRequest(query); } "
    .write vbCrLf & "     else{ getAllItems(); }"
    .write vbCrLf & "} "
    .write vbCrLf & "   function makeItmServerRequest(query){ "
    .write vbCrLf & "     let visitID = '" & SponsorID & "'; "
    .write vbCrLf & "     const itmResults = document.getElementById('itmResult'); "
    .write vbCrLf & "     let getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=searchItems&srhItm=' + encodeURIComponent(query) + '&vst=' + visitID; "
    .write vbCrLf & "     const url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "     fetch(url)  "
    .write vbCrLf & "     .then(response => response.text()) "
    .write vbCrLf & "     .then(data => { "
    .write vbCrLf & "       itmResults.innerHTML = data; "
    .write vbCrLf & "     }) "
    .write vbCrLf & "   } "
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "   function labSearch(){ "
    .write vbCrLf & "     const labInput = document.getElementById('lab-search'); "
    .write vbCrLf & "     const labResults = document.getElementById('labResult'); "
    .write vbCrLf & "     const query = labInput.value.trim(); "
    .write vbCrLf & "     labResults.innerHTML = ''; "
    .write vbCrLf & "     if(query !== ''){ makeLabServerRequest(query); } "
    .write vbCrLf & "     else{ getAllLabs(); }"
    .write vbCrLf & "   } "
    .write vbCrLf & "   function makeLabServerRequest(query){ "
    .write vbCrLf & "     const labResults = document.getElementById('labResult'); "
    .write vbCrLf & "     let visitID = '" & SponsorID & "'; "
    .write vbCrLf & "     let getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=searchLabs&srhLab=' + encodeURIComponent(query) + '&vst=' + visitID; "
    .write vbCrLf & "     const url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "     fetch(url)  "
    .write vbCrLf & "     .then(response => response.text()) "
    .write vbCrLf & "     .then(data => { "
    .write vbCrLf & "       labResults.innerHTML = data; "
    .write vbCrLf & "     }) "
    .write vbCrLf & "   } "
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "   function treatSearch(){ "
    .write vbCrLf & "     const treatInput = document.getElementById('treat-search'); "
    .write vbCrLf & "     const treatResults = document.getElementById('treatResult'); "
    .write vbCrLf & "     const query = treatInput.value.trim(); "
    .write vbCrLf & "     treatResults.innerHTML = ''; "
    .write vbCrLf & "     if(query !== ''){ makeTreatServerRequest(query); } "
    .write vbCrLf & "     else{ getAllTreats(); }"
    .write vbCrLf & "   } "
    .write vbCrLf & "   function makeTreatServerRequest(query){ "
    .write vbCrLf & "     let visitID = '" & SponsorID & "'; "
    .write vbCrLf & "     const treatResults = document.getElementById('treatResult'); "
    .write vbCrLf & "     let getStr = 'ProcedureName=UpdateProformaInfoClientSponsor&action=searchTreats&srhTreat=' + encodeURIComponent(query) + '&vst=' + visitID; "
    .write vbCrLf & "     const url = 'wpgXMLHttp.asp?' + getStr; "
    .write vbCrLf & "     fetch(url)  "
    .write vbCrLf & "     .then(response => response.text()) "
    .write vbCrLf & "     .then(data => { "
    .write vbCrLf & "       treatResults.innerHTML = data; "
    .write vbCrLf & "     }) "
    .write vbCrLf & "   } "
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & ""
    .write vbCrLf & "</script>"
  End With
End Sub

Function getDiscount(SponsorID)
    Dim rst, sql, ot, dsc
    Set rst = CreateObject("ADODB.RecordSet")
    sql = "SELECT Description FROM PerformVar22 WHERE PerformVar22ID = '" & SponsorID & "'"
    rst.open qryPro.FltQry(sql), conn, 3, 4
        If rst.RecordCount > 0 Then
            rst.MoveFirst
            dsc = rst.fields("Description")
            If Len(dsc) > 0 Then
                ot = dsc
            Else
                ot = 0
            End If
        End If
    rst.Close
    Set rst = Nothing
    getDiscount = ot
End Function

Sub addCSS()
  With response
    .write vbCrLf & "  <style>"
    .write vbCrLf & "    * {"
    .write vbCrLf & "      margin: 0;"
    .write vbCrLf & "      padding: 0;"
    .write vbCrLf & "      box-sizing: border-box;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    body {"
    .write vbCrLf & "      background-color: #f8f9ff;"
    .write vbCrLf & "      height: 100vh;"
    .write vbCrLf & "      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .container {"
    .write vbCrLf & "      width: 100%;"
    .write vbCrLf & "      max-width: 1400px;"
    .write vbCrLf & "      background-color: #fff;"
    .write vbCrLf & "      padding: 20px;"
    .write vbCrLf & "      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);"
    .write vbCrLf & "      border-radius: 8px;"
    .write vbCrLf & "      margin: 20px auto;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .data {"
    .write vbCrLf & "      display: flex;"
    .write vbCrLf & "      justify-content: space-between;"
    .write vbCrLf & "      gap: 20px;"
    .write vbCrLf & "      margin-bottom: 20px;"
    .write vbCrLf & "      padding: 15px;"
    .write vbCrLf & "      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    .write vbCrLf & "      border-radius: 8px;"
    .write vbCrLf & "      color: white;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .data label {"
    ' .write vbCrLf & "      display: flex;"
    ' .write vbCrLf & "      flex-direction: column;"
    ' .write vbCrLf & "      gap: 5px;"
    .write vbCrLf & "      font-weight: 500;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .data input {"
    .write vbCrLf & "      padding: 8px 12px;"
    .write vbCrLf & "      border: 1px solid rgba(255, 255, 255, 0.3);"
    .write vbCrLf & "      border-radius: 4px;"
    .write vbCrLf & "      background-color: rgba(255, 255, 255, 0.1);"
    .write vbCrLf & "      color: white;"
    .write vbCrLf & "      font-size: 14px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .data input::placeholder {"
    .write vbCrLf & "      color: rgba(255, 255, 255, 0.7);"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .tab_box {"
    .write vbCrLf & "      width: 100%;"
    .write vbCrLf & "      display: flex;"
    .write vbCrLf & "      justify-content: space-around;"
    .write vbCrLf & "      align-items: center;"
    .write vbCrLf & "      border-bottom: 2px solid #e0e0e0;"
    .write vbCrLf & "      position: relative;"
    .write vbCrLf & "      margin-bottom: 20px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .tab_box .tab_btn {"
    .write vbCrLf & "      font-size: 16px;"
    .write vbCrLf & "      font-weight: 500;"
    .write vbCrLf & "      color: #919191;"
    .write vbCrLf & "      background: none;"
    .write vbCrLf & "      border: none;"
    .write vbCrLf & "      padding: 15px 20px;"
    .write vbCrLf & "      cursor: pointer;"
    .write vbCrLf & "      transition: all 0.3s ease;"
    .write vbCrLf & "      border-radius: 4px 4px 0 0;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .tab_box .tab_btn:hover {"
    .write vbCrLf & "      color: #667eea;"
    .write vbCrLf & "      background-color: rgba(102, 126, 234, 0.1);"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .tab_box .tab_btn.active {"
    .write vbCrLf & "      color: #667eea;"
    .write vbCrLf & "      background-color: rgba(102, 126, 234, 0.1);"
    .write vbCrLf & "      font-weight: 600;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box {"
    .write vbCrLf & "      padding: 20px;"
    .write vbCrLf & "      height: 70vh;"
    .write vbCrLf & "      overflow-x: hidden;"
    .write vbCrLf & "      overflow-y: auto;"
    .write vbCrLf & "      background-color: #fafafa;"
    .write vbCrLf & "      border-radius: 8px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box::-webkit-scrollbar {"
    .write vbCrLf & "      width: 8px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box::-webkit-scrollbar-thumb {"
    .write vbCrLf & "      border-radius: 4px;"
    .write vbCrLf & "      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box::-webkit-scrollbar-track {"
    .write vbCrLf & "      background: #f0f0f0;"
    .write vbCrLf & "      border-radius: 4px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable {"
    .write vbCrLf & "      width: 100%;"
    .write vbCrLf & "      border-collapse: collapse;"
    .write vbCrLf & "      text-align: center;"
    .write vbCrLf & "      margin-top: 20px;"
    .write vbCrLf & "      font-size: 14px;"
    .write vbCrLf & "      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
    .write vbCrLf & "      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);"
    .write vbCrLf & "      border-radius: 8px;"
    .write vbCrLf & "      overflow: hidden;"
    .write vbCrLf & "      background-color: #fff;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable th {"
    .write vbCrLf & "      font-weight: 600;"
    .write vbCrLf & "      padding: 12px;"
    .write vbCrLf & "      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    .write vbCrLf & "      color: white;"
    .write vbCrLf & "      text-transform: uppercase;"
    .write vbCrLf & "      letter-spacing: 0.5px;"
    .write vbCrLf & "      border: none;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable td {"
    .write vbCrLf & "      padding: 12px;"
    .write vbCrLf & "      border-bottom: 1px solid #e0e0e0;"
    .write vbCrLf & "      transition: all 0.3s ease;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable tr:hover {"
    .write vbCrLf & "      background-color: #f8f9ff;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable tr:nth-child(even) {"
    .write vbCrLf & "      background-color: #fafafa;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable tr:nth-child(even):hover {"
    .write vbCrLf & "      background-color: #f0f2ff;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content #myTable th:nth-child(6),"
    .write vbCrLf & "    .content_box .content #myTable td:nth-child(6) {"
    .write vbCrLf & "      width: 250px;"
    .write vbCrLf & "      min-width: 160px;"
    .write vbCrLf & "      text-align: center;"
    .write vbCrLf & "      padding: 12px 10px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content {"
    .write vbCrLf & "      display: none;"
    .write vbCrLf & "      animation: moving .5s ease;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    @keyframes moving {"
    .write vbCrLf & "      from {"
    .write vbCrLf & "        transform: translate(50px);"
    .write vbCrLf & "        opacity: 0;"
    .write vbCrLf & "      }"
    .write vbCrLf & ""
    .write vbCrLf & "      to {"
    .write vbCrLf & "        transform: translate(0px);"
    .write vbCrLf & "        opacity: 1;"
    .write vbCrLf & "      }"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .content_box .content.active {"
    .write vbCrLf & "      display: block;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .line {"
    .write vbCrLf & "      position: absolute;"
    .write vbCrLf & "      bottom: 0;"
    .write vbCrLf & "      left: 20px;"
    .write vbCrLf & "      width: 90px;"
    .write vbCrLf & "      height: 3px;"
    .write vbCrLf & "      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);"
    .write vbCrLf & "      border-radius: 2px;"
    .write vbCrLf & "      transition: all 0.3s ease-in-out;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label {"
    .write vbCrLf & "      cursor: pointer;"
    .write vbCrLf & "      display: block;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .Quantity {"
    .write vbCrLf & "      border: 1px solid #e0e0e0;"
    .write vbCrLf & "      border-radius: 4px;"
    .write vbCrLf & "      text-align: center;"
    .write vbCrLf & "      padding: 6px 8px;"
    .write vbCrLf & "      font-size: 14px;"
    .write vbCrLf & "      transition: border-color 0.3s ease;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    .Quantity:focus {"
    .write vbCrLf & "      outline: none;"
    .write vbCrLf & "      border-color: #667eea;"
    .write vbCrLf & "      box-shadow: 0 0 0 2px rgba(102, 126, 234, 0.2);"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox'] {"
    .write vbCrLf & "      display: none;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox']~span {"
    .write vbCrLf & "      position: relative;"
    .write vbCrLf & "      display: inline-block;"
    .write vbCrLf & "      padding: 3px 0 3px 15px;"
    .write vbCrLf & "      white-space: nowrap;"
    .write vbCrLf & "      overflow: visible;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox']~span:before,"
    .write vbCrLf & "    #myTable label input[type='checkbox']~span:after {"
    .write vbCrLf & "      content: '';"
    .write vbCrLf & "      position: absolute;"
    .write vbCrLf & "      display: block;"
    .write vbCrLf & "      width: 20px;"
    .write vbCrLf & "      height: 20px;"
    .write vbCrLf & "      background: #fff;"
    .write vbCrLf & "      margin-right: 8px;"
    .write vbCrLf & "      border: 1px solid #ccc;"
    .write vbCrLf & "      left: -45px;"
    .write vbCrLf & "      top: 0;"
    .write vbCrLf & "      box-sizing: border-box;"
    .write vbCrLf & "      transition: all 300ms ease-in-out;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox']~span:before {"
    .write vbCrLf & "      width: 45px;"
    .write vbCrLf & "      border-radius: 20px;"
    .write vbCrLf & "      box-shadow: inset 0 2px 5px -1px rgba(0, 0, 0, 0.4), inset 0 -2px 0 -1px rgba(255, 255, 255, 0.2);"
    .write vbCrLf & "      background: #e74c3c;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox']~span:after {"
    .write vbCrLf & "      box-shadow: 0 3px 4px -2px rgba(0, 0, 0, 0.5);"
    .write vbCrLf & "      border-radius: 50%;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox']:checked~span:before {"
    .write vbCrLf & "      background: #27ae60;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #myTable label input[type='checkbox']:checked~span:after {"
    .write vbCrLf & "      left: -13px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    div.select {"
    .write vbCrLf & "      display: flex;"
    .write vbCrLf & "      align-items: center;"
    .write vbCrLf & "      justify-content: center;"
    .write vbCrLf & "      margin: 10px 0;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    div.select select {"
    .write vbCrLf & "      border: 1px solid #e0e0e0;"
    .write vbCrLf & "      border-radius: 4px;"
    .write vbCrLf & "      font-size: 14px;"
    .write vbCrLf & "      padding: 8px 12px;"
    .write vbCrLf & "      background-color: #fff;"
    .write vbCrLf & "      transition: border-color 0.3s ease;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    div.select select:focus {"
    .write vbCrLf & "      outline: none;"
    .write vbCrLf & "      border-color: #667eea;"
    .write vbCrLf & "      box-shadow: 0 0 0 2px rgba(102, 126, 234, 0.2);"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    div#srhBox {"
    .write vbCrLf & "      text-align: center;"
    .write vbCrLf & "      display: flex;"
    .write vbCrLf & "      align-items: center;"
    .write vbCrLf & "      justify-content: center;"
    .write vbCrLf & "      margin-bottom: 20px;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    div#srhBox .qry-search {"
    .write vbCrLf & "      width: 300px;"
    .write vbCrLf & "      font-size: 16px;"
    .write vbCrLf & "      padding: 12px 16px;"
    .write vbCrLf & "      border: 1px solid #e0e0e0;"
    .write vbCrLf & "      border-radius: 8px;"
    .write vbCrLf & "      background-color: #fff;"
    .write vbCrLf & "      transition: all 0.3s ease;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    div#srhBox .qry-search:focus {"
    .write vbCrLf & "      outline: none;"
    .write vbCrLf & "      border-color: #667eea;"
    .write vbCrLf & "      box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #discountMessage {"
    .write vbCrLf & "      margin-top: 8px;"
    .write vbCrLf & "      padding: 8px 12px;"
    .write vbCrLf & "      border-radius: 4px;"
    .write vbCrLf & "      font-size: 14px;"
    .write vbCrLf & "      font-weight: 500;"
    .write vbCrLf & "      animation: fadeIn 0.3s ease-in-out;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    #discountMessage small {"
    .write vbCrLf & "      display: block;"
    .write vbCrLf & "      margin: 0;"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    @keyframes fadeIn {"
    .write vbCrLf & "      from { opacity: 0; transform: translateY(-10px); }"
    .write vbCrLf & "      to { opacity: 1; transform: translateY(0); }"
    .write vbCrLf & "    }"
    .write vbCrLf & ""
    .write vbCrLf & "    @media (max-width: 768px) {"
    .write vbCrLf & "      .container {"
    .write vbCrLf & "        margin: 10px;"
    .write vbCrLf & "        padding: 15px;"
    .write vbCrLf & "      }"
    .write vbCrLf & "      .data {"
    .write vbCrLf & "        flex-direction: column;"
    .write vbCrLf & "        gap: 10px;"
    .write vbCrLf & "      }"
    .write vbCrLf & "      div#srhBox .qry-search {"
    .write vbCrLf & "        width: 100%;"
    .write vbCrLf & "        max-width: 300px;"
    .write vbCrLf & "      }"
    .write vbCrLf & "    }"
    .write vbCrLf & "  </style>"
  End With
End Sub
'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
