'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>

AddPageScript
Init
Sub AddPageScript()
    Dim html
    html = html & vbCrLf & "<script type='text/javascript'>"
    html = html & vbCrLf & "    function DynamicTableLoader() {"
    html = html & vbCrLf & "        this.isStopped = true;"
    html = html & vbCrLf & "        this.tableId = null;"
    html = html & vbCrLf & "        this.targetElementID = null;"
    html = html & vbCrLf & "        this.currentRowData = null;"
    html = html & vbCrLf & "        this.isNewRow = null;"
    html = html & vbCrLf & "        this.newRows = null;"
    html = html & vbCrLf & "        this.oldRowData = null;"
    html = html & vbCrLf & "        this.oldJsonObj = null;"
    html = html & vbCrLf & "        this.currentJsonObj = null;"
    html = html & vbCrLf & "        this.currentRowData = null;"
    html = html & vbCrLf & "        this.url = null;"
    html = html & vbCrLf & "        this.loadInterval = 30;"
    html = html & vbCrLf & "        this.xmlReq = new XMLHttpRequest();"
    html = html & vbCrLf & "        this.timeout = null;"
    html = html & vbCrLf & "        this.lastRefreshDate = null;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "        this.writeDynamicRows = function (tableJson) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            let table = _self.buildDynamicRows(tableJson, 0);"
    html = html & vbCrLf & "            let targetElement = document.getElementById(_self.targetElementID);"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            let oldTable = document.getElementById(_self.tableId);"
    html = html & vbCrLf & "            if (oldTable) {"
    html = html & vbCrLf & "                if (tableJson['persist-old-rows'] === true) {"
    html = html & vbCrLf & "                    let firstRow = oldTable.tBodies[0].firstElementChild;"
    html = html & vbCrLf & "                    while (table.tBodies[0].rows.length > 0) {"
    html = html & vbCrLf & "                        let new_row = table.tBodies[0].rows[0];"
    html = html & vbCrLf & "                        new_row.remove();"
    html = html & vbCrLf & "                        oldTable.tBodies[0].insertBefore(new_row, firstRow);"
    html = html & vbCrLf & "                    }"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                else {"
    html = html & vbCrLf & "                    oldTable.remove();"
    html = html & vbCrLf & "                    oldTable = null;"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            table.setAttribute('id', _self.tableId);"
    html = html & vbCrLf & "            table.classList.add('dynamic-table-style');"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            if (!oldTable) {"
    html = html & vbCrLf & "                if (targetElement) {"
    html = html & vbCrLf & "                    targetElement.appendChild(table);"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                else if (targetElement == null) {"
    html = html & vbCrLf & "                    document.body.appendChild(table);"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                _self.addRowNumbers();"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            //call load function"
    html = html & vbCrLf & "            if (tableJson['onload']) {"
    html = html & vbCrLf & "                let fn = new Function(tableJson['onload']);"
    html = html & vbCrLf & "                fn();"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            "
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.addRowNumbers = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            let table = document.getElementById(_self.tableId);"
    html = html & vbCrLf & "            if (table) {"
    html = html & vbCrLf & "                let style = document.createElement('style');"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                let css = '#' + _self.tableId + '.dynamic-table-style{';"
    html = html & vbCrLf & "                css += 'counter-reset: row-counter;';"
    html = html & vbCrLf & "                css += '}';"
    html = html & vbCrLf & "                css += '#' + _self.tableId + '.dynamic-table-style>tbody>tr>td.row-number::before {';"
    html = html & vbCrLf & "                css += 'counter-increment: row-counter;';"
    html = html & vbCrLf & "                css += 'content: counter(row-counter);';"
    html = html & vbCrLf & "                css += '}';"
    html = html & vbCrLf & "                style.appendChild(document.createTextNode(css));"
    html = html & vbCrLf & "                document.body.appendChild(style);"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.buildDynamicRows = function (tableJson, depth) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            let rows = null;"
    html = html & vbCrLf & "            let notif = null;"
    html = html & vbCrLf & "            let header = null;"
    html = html & vbCrLf & "            let table = document.createElement('table');"
    html = html & vbCrLf & ""
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            depth += 1;"
    html = html & vbCrLf & "            "
    html = html & vbCrLf & "            if (tableJson.constructor.name === 'Array') {"
    html = html & vbCrLf & "                rows = tableJson;"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            else if (tableJson.constructor.name === 'Object') {"
    html = html & vbCrLf & "                rows = tableJson['rows'];"
    html = html & vbCrLf & "                if (!rows && tableJson['row-data']) {"
    html = html & vbCrLf & "                    rows = [tableJson]"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                header = tableJson['header'];"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            if (Array.isArray(header)) {"
    html = html & vbCrLf & "                let thead = table.createTHead();"
    html = html & vbCrLf & "                let tRow = thead.insertRow();"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                if (tableJson['show-row-numbers'] === true) {"
    html = html & vbCrLf & "                    let td = tRow.insertCell();"
    html = html & vbCrLf & "                    td.classList.add('row-number');"
    html = html & vbCrLf & "                    td.style.zIndex = 1;"
    html = html & vbCrLf & "                    td.innerText = 'No.';"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                header.forEach(head => {"
    html = html & vbCrLf & "                    let td = tRow.insertCell();"
    html = html & vbCrLf & "                    td.innerHTML = head;"
    html = html & vbCrLf & "                });"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            let row_size = 0;"
    html = html & vbCrLf & "            if (Array.isArray(rows)) {"
    html = html & vbCrLf & "                let tbody = table.createTBody();"
    html = html & vbCrLf & "                row_size = rows.length;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                rows.forEach((row, index) => {"
    html = html & vbCrLf & "                    _self.currentRowData.push(JSON.stringify(row));"
    html = html & vbCrLf & "                    let row_data = row['row-data'] || row;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                    if (row_data) {"
    html = html & vbCrLf & "                        let tRow = tbody.insertRow();"
    html = html & vbCrLf & "                        //row properties"
    html = html & vbCrLf & "                        if (depth === 1 && _self.isNewRow(row)) {"
    html = html & vbCrLf & "                            tRow.classList.add('new-dynamic-row');"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        if (row['tooltip']) {"
    html = html & vbCrLf & "                            _self.addtooltip(tRow, row['tooltip']);"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        if (row['class']) {"
    html = html & vbCrLf & "                            tRow.classList.add(row['class']);"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        if (row['click-url']) {"
    html = html & vbCrLf & "                            addClickUrl(tRow, row['click-url']);"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        if (row['style']) {"
    html = html & vbCrLf & "                            tRow.style.cssText = row['style'];"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                        if (!Array.isArray(row_data)) {"
    html = html & vbCrLf & "                            row_data = [row_data];"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        if (tableJson['show-row-numbers'] === true) {"
    html = html & vbCrLf & "                            let td = tRow.insertCell();"
    html = html & vbCrLf & "                            td.classList.add('row-number')"
    html = html & vbCrLf & "                            //td.innerText = index + 1;"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        row_data.forEach(cell => {"
    html = html & vbCrLf & "                            let td = tRow.insertCell();"
    html = html & vbCrLf & "                            if (cell && typeof cell === 'object' && (cell.constructor.name === 'Array' || cell.constructor.name === 'Object')) {"
    html = html & vbCrLf & "                                td.appendChild(_self.buildDynamicRows(cell, depth));"
    html = html & vbCrLf & "                            }"
    html = html & vbCrLf & "                            else {"
    html = html & vbCrLf & "                                td.innerHTML = cell;"
    html = html & vbCrLf & "                            }"
    html = html & vbCrLf & "                        })"
    html = html & vbCrLf & "                    }"
    html = html & vbCrLf & "                });"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (tableJson['title'] || true) {"
    html = html & vbCrLf & "                let thead = table.createTHead();"
    html = html & vbCrLf & "                let tRow = thead.insertRow(0);"
    html = html & vbCrLf & "                let td = tRow.insertCell();"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                td.setAttribute('colspan', 100);"
    html = html & vbCrLf & "                td.classList.add('title');"
    html = html & vbCrLf & "                notif = document.createElement('div');"
    html = html & vbCrLf & "                notif.setAttribute('id', 'new-row-counter');"
    html = html & vbCrLf & "                notif.style.display = 'none';"
    html = html & vbCrLf & "                notif.classList.add('new-row-notif');"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                td.innerHTML = notif.outerHTML + (tableJson['title'] || '');"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                tRow = thead.insertRow(0);"
    html = html & vbCrLf & "                td = tRow.insertCell();"
    html = html & vbCrLf & "                td.classList.add('loading');"
    html = html & vbCrLf & "                td.setAttribute('id', _self.tableId + '-loading');"
    html = html & vbCrLf & "                td.setAttribute('colspan', 100);"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (tableJson['control-panel']) {"
    html = html & vbCrLf & "                let thead = table.createTHead();"
    html = html & vbCrLf & "                let tRow = thead.insertRow(0);"
    html = html & vbCrLf & "                let td = tRow.insertCell();"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                td.setAttribute('colspan', 100);"
    html = html & vbCrLf & "                td.classList.add('control-panel');"
    html = html & vbCrLf & "                td.setAttribute('id', 'control-panel');"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                td.innerHTML = (tableJson['control-panel'] || '');"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (tableJson['css-text']) {"
    html = html & vbCrLf & "                let id = 'css-text-' + (_self.tableId || '');"
    html = html & vbCrLf & "                let css = document.createElement('style');"
    html = html & vbCrLf & "                css.setAttribute('id', id);"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                let oldCss = document.getElementById(id);"
    html = html & vbCrLf & "                if (oldCss) {"
    html = html & vbCrLf & "                    oldCss.remove();"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                css.innerText = tableJson['css-text'];"
    html = html & vbCrLf & "                document.body.appendChild(css);"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (tableJson['javascript-text']) {"
    html = html & vbCrLf & "                let id = 'javascript-text-' + (_self.tableId || '');"
    html = html & vbCrLf & "                let js = document.createElement('script');"
    html = html & vbCrLf & "                js.setAttribute('id', id);"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                let oldJs = document.getElementById(id);"
    html = html & vbCrLf & "                if (oldJs) {"
    html = html & vbCrLf & "                    oldJs.remove();"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                js.innerText = tableJson['javascript-text'];"
    html = html & vbCrLf & "                document.body.appendChild(js);"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (tableJson['style']) {"
    html = html & vbCrLf & "                table.style.cssText = tableJson['style'];"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            return table;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.isNewRow = function (row_data) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            if (!_self.newRows) {"
    html = html & vbCrLf & "                _self.newRows = [];"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (row_data['is-new'] === true) {"
    html = html & vbCrLf & "                let row_str = JSON.stringify(row_data);"
    html = html & vbCrLf & "                if (!_self.newRows.includes(row_str)) {"
    html = html & vbCrLf & "                    _self.newRows.push(row_str);"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & "                return true;"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            return false;"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.addTooltip = function (tRow, tooltip) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.extractRowData = function (jsonObj) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            row_data = [];"
    html = html & vbCrLf & "            if (Array.isArray(jsonObj['rows'])) {"
    html = html & vbCrLf & "                jsonObj['rows'].forEach(row => {"
    html = html & vbCrLf & "                    row_data = [...row_data, JSON.stringify(_self.extractRowData(row))];"
    html = html & vbCrLf & "                });"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            else if (Array.isArray(jsonObj['row-data'])) {"
    html = html & vbCrLf & "                jsonObj['row-data'].forEach(row => {"
    html = html & vbCrLf & "                    row_data = [...row_data, ..._self.extractRowData(row)];"
    html = html & vbCrLf & "                });"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            else if (Array.isArray(jsonObj)) {"
    html = html & vbCrLf & "                jsonObj.forEach(row => {"
    html = html & vbCrLf & "                    row_data = [...row_data, ..._self.extractRowData(row)];"
    html = html & vbCrLf & "                });"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            else {"
    html = html & vbCrLf & "                row_data = jsonObj;"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            return row_data;"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.addClickUrl = function (tRow, clickUrl) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            tRow.classList.add('dynamic-table-clickable');"
    html = html & vbCrLf & "            tRow.dataset.clickUrl = clickUrl;"
    html = html & vbCrLf & "            tRow.setAttribute('onclick', 'DynamicTableLoader.openurl(this.dataset.clickUrl);');"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.getDynamicRows = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            try {"
    html = html & vbCrLf & "                if (!document.hidden && !_self.isStopped) { //fetch only on active window"
    html = html & vbCrLf & "                    let jsonObj = JSON.parse(_self.xmlReq.response);"
    html = html & vbCrLf & "                    _self.numberOfRequestSent += 1;"
    html = html & vbCrLf & "                    _self.currentRowData = [];"
    html = html & vbCrLf & "                    _self.currentJsonObj = JSON.stringify(jsonObj);"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                    _self.hideLoadingAnimation();"
    html = html & vbCrLf & "                    if (!_self.oldRowData) {"
    html = html & vbCrLf & "                        _self.oldRowData = [];"
    html = html & vbCrLf & "                    }"
    html = html & vbCrLf & "                    if (_self.currentJsonObj !== _self.oldJsonObj || jsonObj['persist-old-rows'] === true) {"
    html = html & vbCrLf & "                        _self.writeDynamicRows(jsonObj);"
    html = html & vbCrLf & "                        _self.oldRowData = _self.currentRowData"
    html = html & vbCrLf & "                        _self.oldJsonObj = _self.currentJsonObj"
    html = html & vbCrLf & "                        _self.showNewRowCount();"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                    }"
    html = html & vbCrLf & "                    else {"
    html = html & vbCrLf & "                        //highlight new records for only a minute"
    html = html & vbCrLf & "                        let currDate = new Date();"
    html = html & vbCrLf & "                        if (_self.lastRefreshDate) {"
    html = html & vbCrLf & "                            if (currDate - _self.lastRefreshDate >= 60000) {"
    html = html & vbCrLf & "                                _self.lastRefreshDate = currDate"
    html = html & vbCrLf & "                                _self.clearCache();"
    html = html & vbCrLf & "                            }"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                        else {"
    html = html & vbCrLf & "                            _self.lastRefreshDate = currDate"
    html = html & vbCrLf & "                        }"
    html = html & vbCrLf & "                    }"
    html = html & vbCrLf & "                }"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            catch (e) {"
    html = html & vbCrLf & "                console.log(e, 'failed on', _self.url, 'at', new Date().toGMTString());"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            if (!_self.isStopped) {"
    html = html & vbCrLf & "                _self.timeout = setTimeout(function () {"
    html = html & vbCrLf & "                    _self.showLoadingAnimation();"
    html = html & vbCrLf & "                    _self.xmlReq.open('GET', _self.url);"
    html = html & vbCrLf & "                    _self.xmlReq.send();"
    html = html & vbCrLf & "                }, _self.loadInterval);"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.showNewRowCount = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            let notif = document.getElementById('new-row-counter');"
    html = html & vbCrLf & "            let row_count = document.getElementsByClassName('new-dynamic-row').length;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            if (notif && row_count > 0) {"
    html = html & vbCrLf & "                notif.innerText = row_count + ' new';"
    html = html & vbCrLf & "                notif.style.display = 'inline-block';"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            "
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.clearCache = function () {"
    html = html & vbCrLf & "            let _self = this"
    html = html & vbCrLf & "            _self.currentRowData = [];"
    html = html & vbCrLf & "            _self.newRows = [];"
    html = html & vbCrLf & "            _self.oldRowData = [];"
    html = html & vbCrLf & "            _self.oldJsonObj = [];"
    html = html & vbCrLf & "            _self.currentJsonObj = [];"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.showLoadingAnimation = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            let loading = document.getElementById(_self.tableId + '-loading');"
    html = html & vbCrLf & "            if (loading) {"
    html = html & vbCrLf & "                loading.classList.add('loading-animation');"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.hideLoadingAnimation = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            let loading = document.getElementById(_self.tableId + '-loading');"
    html = html & vbCrLf & "            if (loading) {"
    html = html & vbCrLf & "                loading.classList.remove('loading-animation');"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.openurl = function (url) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            window.open(url, '_blank', 'width=700,height=600');"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.loadDynamicTable = function (tableId, targetElementID, url, loadInterval) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            _self.numberOfRequestSent = 0;"
    html = html & vbCrLf & "            _self.tableId = tableId;"
    html = html & vbCrLf & "            _self.targetElementID = targetElementID;"
    html = html & vbCrLf & "            _self.url = url;"
    html = html & vbCrLf & "            _self.loadInterval = loadInterval;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            _self.xmlReq.onload = function () {"
    html = html & vbCrLf & "                _self.getDynamicRows();"
    html = html & vbCrLf & "            };"
    html = html & vbCrLf & "            _self.xmlReq.onabort = function () {"
    html = html & vbCrLf & "                _self.hideLoadingAnimation();"
    html = html & vbCrLf & "                _self.isStopped = true;"
    html = html & vbCrLf & "            };"
    html = html & vbCrLf & "            _self.start();"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.stop = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            _self.xmlReq.abort();"
    html = html & vbCrLf & "            if (_self.timeout) {"
    html = html & vbCrLf & "                clearTimeout(_self.timeout);"
    html = html & vbCrLf & "                _self.timeout = null;"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.start = function () {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "            if (!(_self.xmlReq.readyState === _self.xmlReq.UNSENT)) {"
    html = html & vbCrLf & "                return;"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            _self.stop();"
    html = html & vbCrLf & "            if (_self.tableId && _self.url && _self.loadInterval) {"
    html = html & vbCrLf & "                _self.isStopped = false;"
    html = html & vbCrLf & "                _self.xmlReq.open('GET', _self.url);"
    html = html & vbCrLf & "                _self.xmlReq.send();"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "            else {"
    html = html & vbCrLf & "                console.log('Failed to start, please pass the right values to :loadDynamicTable');"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.getParam = function (name) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            if (_self.url) {"
    html = html & vbCrLf & "                let url = _self.url.split('?');"
    html = html & vbCrLf & "                let url_search = new URLSearchParams((url[1] || ''));"
    html = html & vbCrLf & "                return url_search.get(name) || '';"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        this.setParam = function (name, value) {"
    html = html & vbCrLf & "            let _self = this;"
    html = html & vbCrLf & "            if (_self.url) {"
    html = html & vbCrLf & "                _self.stop();"
    html = html & vbCrLf & "                _self.clearCache();"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                let url = _self.url.split('?');"
    html = html & vbCrLf & "                let url_search = new URLSearchParams((url[1] || ''));"
    html = html & vbCrLf & "                url_search.set(name, value);"
    html = html & vbCrLf & "                _self.url = url[0] + '?' + url_search.toString();"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "                _self.start();"
    html = html & vbCrLf & "            }"
    html = html & vbCrLf & "        }"
    html = html & vbCrLf & "        "
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "</script>"
    html = html & vbCrLf & "<style>"
    html = html & vbCrLf & "    .dynamic-table-style{"
    html = html & vbCrLf & "        --new-row-background: #E2ECF7;"
    html = html & vbCrLf & "        --new-row-background: #F9F2E5;"
    html = html & vbCrLf & "        --new-row-border: #0164D5;"
    html = html & vbCrLf & "        --new-row-border: #EA9300;"
    html = html & vbCrLf & "        --color: black;"
'    html = html & vbCrLf & "        --background-image : linear-gradient(to bottom, #e3ffff, #e3ffff, #cae4dd, #e3ffff, #e3ffff);"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "        border-spacing: 0px;"
    html = html & vbCrLf & "        border-collapse: separate;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead {"
    html = html & vbCrLf & "        font-weight: bold;"
    html = html & vbCrLf & "        background-image: var(--background-image);"
    html = html & vbCrLf & "        color: var(--color);"
    html = html & vbCrLf & "        background-color: var(--background-color);"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr>td#control-panel{"
    html = html & vbCrLf & "        background:white;"
    html = html & vbCrLf & "        border:none;"
    html = html & vbCrLf & "        color:black;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr>td, .dynamic-table-style>tbody>tr>td {"
    html = html & vbCrLf & "        border-right: 1px solid silver;"
    html = html & vbCrLf & "        border-top: 1px solid silver;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr>td:first-child, .dynamic-table-style>tbody>tr>td:first-child {"
    html = html & vbCrLf & "        border-left: 1px solid silver;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>tbody>tr:first-child>td{"
    html = html & vbCrLf & "        border-top: none;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr:last-child>td, .dynamic-table-style>tbody>tr:last-child>td {"
    html = html & vbCrLf & "        border-bottom: 1px solid silver;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr>td.title {"
    html = html & vbCrLf & "        border-top: none;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr>td.loading {"
    html = html & vbCrLf & "        border-radius: 2px 2px 0 0;"
    html = html & vbCrLf & "        padding: 0px;"
    html = html & vbCrLf & "        border-bottom: none;"
    html = html & vbCrLf & "        height: 3px;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead>tr>td, .dynamic-table-style>thead>tr>th{"
    html = html & vbCrLf & "        vertical-align: middle;"
    html = html & vbCrLf & "        padding: 5px 5px 5px 10px;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>tbody>tr>td {"
    html = html & vbCrLf & "        padding: 5px 5px 5px 10px;"
    html = html & vbCrLf & "        vertical-align: top;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style>thead{"
    html = html & vbCrLf & "        top: 0;"
    html = html & vbCrLf & "        position: sticky;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style td.row-number{"
    html = html & vbCrLf & "        /*left: 0;*/"
    html = html & vbCrLf & "        /*position: sticky;*/"
    html = html & vbCrLf & "        color: var(--color);"
    html = html & vbCrLf & "        background-image: var(--background-image);"
    html = html & vbCrLf & "        font-weight: bold;"
    html = html & vbCrLf & "        z-index: 1;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style tr[data-click-url]{"
    html = html & vbCrLf & "        color: #2196F3;"
    html = html & vbCrLf & "        font-weight: bold;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style tr[data-click-url]:hover{"
    html = html & vbCrLf & "        background-color: lightgoldenrodyellow;"
    html = html & vbCrLf & "        cursor: pointer;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style tr.new-dynamic-row {"
    html = html & vbCrLf & "        background-color: var(--new-row-background);"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style tr.new-dynamic-row>td{"
    html = html & vbCrLf & "        border-top: 1px solid var(--new-row-border);"
    html = html & vbCrLf & "        border-bottom: 1px solid var(--new-row-border);"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style tr.new-dynamic-row>td:first-child{"
    html = html & vbCrLf & "        border-left: 1px solid var(--new-row-border);"
    html = html & vbCrLf & "        border-top-left-radius: 5px;"
    html = html & vbCrLf & "        border-bottom-left-radius: 5px;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style tr.new-dynamic-row>td:last-child{"
    html = html & vbCrLf & "        border-right: 1px solid var(--new-row-border);"
    html = html & vbCrLf & "        border-top-right-radius: 5px;"
    html = html & vbCrLf & "        border-bottom-right-radius: 5px;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style .new-row-notif{"
    html = html & vbCrLf & "        border: 2px solid #9d6300;"
    html = html & vbCrLf & "        border-radius: 5px;"
    html = html & vbCrLf & "        background-color: var(--new-row-border);"
    html = html & vbCrLf & "        color: white;"
    html = html & vbCrLf & "        font-weight: bold;"
    html = html & vbCrLf & "        display: inline-block;"
    html = html & vbCrLf & "        margin-right: 5px;"
    html = html & vbCrLf & "        padding: 2px;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    .dynamic-table-style .loading-animation{"
    html = html & vbCrLf & "        background: linear-gradient(270deg, var(--new-row-border), var(--new-row-background), var(--new-row-border));"
    html = html & vbCrLf & "        /*background-size: 1400% 1400%;*/"
    html = html & vbCrLf & "        -webkit-animation: loading-animation 2s ease infinite;"
    html = html & vbCrLf & "        -moz-animation: loading-animation 2s ease infinite;"
    html = html & vbCrLf & "        animation: loading-animation 2s ease infinite;"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    @-webkit-keyframes loading-animation {"
    html = html & vbCrLf & "        0%{background-position:0% 50%}"
    html = html & vbCrLf & "        50%{background-position:100% 50%}"
    html = html & vbCrLf & "        100%{background-position:0% 50%}"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    @-moz-keyframes loading-animation {"
    html = html & vbCrLf & "        0%{background-position:0% 50%}"
    html = html & vbCrLf & "        50%{background-position:100% 50%}"
    html = html & vbCrLf & "        100%{background-position:0% 50%}"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "    @keyframes loading-animation {"
    html = html & vbCrLf & "        0%{background-position:0% 50%}"
    html = html & vbCrLf & "        50%{background-position:100% 50%}"
    html = html & vbCrLf & "        100%{background-position:0% 50%}"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "</style>"
    html = html & vbCrLf & ""
    html = html & vbCrLf & "<script>"
    html = html & vbCrLf & "    let tmp = document.getElementById(""trPrintControl"");"
    html = html & vbCrLf & "    if(tmp){"
    html = html & vbCrLf & "        tmp.style.display=""none"";"
    html = html & vbCrLf & "    }"
    html = html & vbCrLf & "</script>"
    response.write html
End Sub
Sub Init()
    Dim businessRuleName, loadInterval, params, kv
    
    params = ""
    For Each value In Request.QueryString("Parameter")
        kv = Split(value, "||")
        If UBound(kv) > 0 Then
            If params <> "" Then params = params & "&"
            params = params & kv(0) & "=" & kv(1)
        End If
    Next

    businessRuleName = Trim(Request.QueryString("ProcedureName"))
    loadInterval = Trim(Request.QueryString("LoadInterval"))
    If loadInterval = "" Or Not IsNumeric(timeOut) Then
        loadInterval = 30000 '30 seconds
    End If

    dynamicTableLoader businessRuleName, params, loadInterval
End Sub

Function dynamicTableLoader(businessRuleName, params, loadInterval)
    Dim xmlHttpUrl, id, style, js, pgCol, pgFnt, pgBg, styleParam
    Dim re

    Set re = New RegExp
    re.pattern = "[^a-zA-z]"
    re.Global = True
    id = "DTL_" & re.Replace(businessRuleName, "_")

    xmlHttpUrl = "wpgXmlHttp.asp?"
    'xmlHttpUrl = businessRuleName & "?" 'test

    xmlHttpUrl = xmlHttpUrl & "ProcedureName=" & businessRuleName
    xmlHttpUrl = xmlHttpUrl & "&DynamicTableName=" & id

    If params <> "" Then
        xmlHttpUrl = xmlHttpUrl & "&" & params
    End If
   
    styleParam = GetComboNameFld("PageStyle", "HomePageLayout-" & GetComboNameFld("JobSchedule", jSchd, "NavigationThemeID"), "StyleParam2")
    pgCol = Split(styleParam, "||")
    If UBound(pgCol) >= 0 Then
        pgFnt = pgCol(0)
    Else
        pgFnt = "#1e5b5b"
    End If
    If UBound(pgCol) >= 1 Then
        pgBg = pgCol(1)
    Else
        pgBg = "#E3FFE3"
        pgBg = "#fcfcfc"
    End If

    style = "<style>"
    style = style & vbCrLf & " .dynamic-table-style{"
    style = style & vbCrLf & "   --page-bg-color:" & pgBg & ";"
    style = style & vbCrLf & "   --page-fnt-color:" & pgFnt & ";"
    'style = style & vbCrLf &"   --background-image:linear-gradient(217deg, "& pgBg &", "& pgBg &", #cae4dd, "& pgBg &", "& pgBg &");"
    'style = style & vbCrLf &"   --background-image:linear-gradient(180deg, white 0%, var(--page-bg-color) 15%, var(--page-bg-color) 85%, white 100%);"
'    style = style & vbCrLf &"   --background-image:linear-gradient(180deg, var(--page-bg-color) 0%, white 2%, var(--page-bg-color) 24%, var(--page-bg-color) 48%, var(--page-bg-color) 78%, var(--page-bg-color) 98%, var(--page-bg-color) 100%);"
    'style = style & vbCrLf &"   --background-image: linear-gradient(180deg, "& pgFnt &"00, "& pgFnt &"00 30%, "& pgFnt &"00 70%, "& pgFnt &"99 100%); "
    style = style & vbCrLf & "   --background-color:" & pgBg & ";"
    style = style & vbCrLf & "   --color:" & pgFnt & ";"
    style = style & vbCrLf & "}"
    style = style & vbCrLf & " .dynamic-table-style>thead>tr:last-child>td, .dynamic-table-style>tbody>tr:last-child>td {"
'    style = style & vbCrLf & "  border-bottom: 1px solid " & pgFnt & ";"
    style = style & vbCrLf & "}"
    style = style & vbCrLf & "</style>"
    response.write style

    js = "<script>"
    js = js & vbCrLf & "  let " & id & " = new DynamicTableLoader(); "
    js = js & vbCrLf & "  " & id & ".loadDynamicTable('" & id & "', null, '" & xmlHttpUrl & "', " & loadInterval & "); "
    js = js & vbCrLf & "</script>"
    response.write js
End Function

'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
