response.write "     <script>"
response.write "      function sendData(event) {"
response.write "        event.preventDefault();"
response.write "        try {"
response.write "          const sponsorSelect = document.getElementById('sponsors');"
response.write "          const selectedSponsor = sponsorSelect.selectedOptions[0] ? {"
response.write "            id: sponsorSelect.value,"
response.write "            value: sponsorSelect.selectedOptions[0].text"
response.write "          } : null;"
response.write "          const billMonthSelect = document.getElementById('billMonth');"
response.write "          const selectedBillMonth = billMonthSelect.selectedOptions[0] ? {"
response.write "            id: billMonthSelect.value,"
response.write "            value: billMonthSelect.selectedOptions[0].text"
response.write "          } : null;"
response.write "          const amount = document.getElementById('amount').value;"
response.write "          if (!selectedSponsor || !selectedBillMonth || !amount) {"
response.write "            alert('Please select a sponsor, a bill month, and enter an amount.');"
response.write "            return;"
response.write "          }"
response.write "          // Build URL like the guide"
response.write "          let url = 'wpgXMLHTTP.asp?procedurename=InsertSponsorPayment';"
response.write "          url += '&sponsorID=' + selectedSponsor.value;"
response.write "          url += '&billMonthID=' + selectedBillMonth.value;"
response.write "          url += '&amount=' + amount;"
response.write "          console.log('AJAX URL:', url);"
response.write "          // Make the AJAX call"
response.write "          fetch(url)"
response.write "            .then(response => {"
response.write "              if (!response.ok) {"
response.write "                throw new Error('Network response was not ok');"
response.write "              }"
response.write "              return response.json();"
response.write "            })"
response.write "            .then(data => {"
response.write "              console.log('Server response:', data);"
response.write "              if (data.success) {"
response.write "                alert('Data saved successfully!');"
response.write "                window.location.reload();  // Reload like in the guide"
response.write "              } else {"
response.write "                alert('Save failed: ' + (data.message || 'Unknown error'));"
response.write "              }"
response.write "            })"
response.write "            .catch(error => {"
response.write "              console.error('AJAX Error:', error);"
response.write "              alert('Failed to save data: ' + error.message);"
response.write "            });"
response.write "        } catch (error) {"
response.write "          console.error('sendData failed:', error);"
response.write "          alert('An unexpected error occurred.');"
response.write "        }"
response.write "      }"
response.write "    </script>"