"NavigationLinkID"	"NavigationLinkName"	"ParentNavLinkID"	"MenuElementTypeID"	"PosInLink"	"MenuProp"	"LinkDetail"	"LinkUrl"	"NavigationLinkCatID"	"NavigationLinkTypeID"	"UserAccessibleID"	"LinkOpenStyle"	"OtherInfo"	"TitleDesc"	"KeyPrefix"
"DPT014-N011T-01-B-15"	"Outgoing"	"DPT014-N012T-01-B-89"	"40"	"1"	"Vert||Left||Over||RePosition||3C"	"Outgoing"	"&"	"N003"	"Country"	"USA001"	"IN||NAV||800||600||Close"	"-"	"-"	\N
"DPT014-N011T-01-B-24"	"Incoming"	"DPT014-N012T-01-B-89"	"40"	"2"	"Vert||Left||Over||RePosition||3C"	"Incoming"	"&"	"N003"	"CurrencyType"	"USA001"	"IN||NAV||800||600||Close"	"-"	"-"	\N
"DPT014-N012T-01-B-107"	"Drug Stock Levels"	"DPT014-N012T-01-B-89"	"40"	"3"	"Vert||Left||Over||RePosition||3C"	"Drug Stock Levels"	"-"	"N003"	"PermuteTable"	"USA001"	"IN||NAV||800||600||Close"	"-"	"-"	\N
"DPT014-N012T-01-B-90"	"General Info"	"DPT014-N012T-01-B-89"	"40"	"1"	"Vert||Left||Over||RePosition||3C"	"General Info"	"&"	"N003"	"PageStyleTbl"	"USA001"	"IN||NAV||800||600||Close"	"-"	"-"	\N
"DPT014-N012T-01-B-97"	"Request Authorization"	"DPT014-N012T-01-B-89"	"40"	"2"	"Vert||Left||Over||RePosition||3C"	"Request Authorization"	"&"	"N003"	"DataMigrateApply"	"USA001"	"IN||NAV||800||600||Close"	"-"	"-"	\N

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15', 'Outgoing', 'DPT014-N012T-01-B-89', '40', 1, 'Vert||Left||Over||RePosition||3C', 'Outgoing', '&', 'N003', 'Country', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24', 'Incoming', 'DPT014-N012T-01-B-89', '40', 2, 'Vert||Left||Over||RePosition||3C', 'Incoming', '&', 'N003', 'CurrencyType', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-107', 'Drug Stock Levels', 'DPT014-N012T-01-B-89', '40', 3, 'Vert||Left||Over||RePosition||3C', 'Drug Stock Levels', '-', 'N003', 'PermuteTable', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-90', 'General Info', 'DPT014-N012T-01-B-89', '40', 1, 'Vert||Left||Over||RePosition||3C', 'General Info', '&', 'N003', 'PageStyleTbl', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-97', 'Request Authorization', 'DPT014-N012T-01-B-89', '40', 2, 'Vert||Left||Over||RePosition||3C', 'Request Authorization', '&', 'N003', 'DataMigrateApply', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);


DPT014-N011T-01-B-15-1

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-2', 'Requests By Store', 'DPT014-N011T-01-B-15', '40', 2, 'Vert||Left||Over||RePosition||3C', 'Requests By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugRequest2ByDrugRequestStore_WorkingMonth', 'N003', 'CellComponent', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-3', 'Requests By Month', 'DPT014-N011T-01-B-15', '40', 3, 'Vert||Left||Over||RePosition||3C', 'Requests By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugRequest2ByWorkingMonth_DrugRequestStore', 'N003', 'BankAccountType', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-4', 'Issued By Store', 'DPT014-N011T-01-B-15', '40', 4, 'Vert||Left||Over||RePosition||3C', 'Issued By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugIssueByDrugRequestStore_WorkingMonth', 'N003', 'BulkEditAlloc', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-5', 'Issued By Month', 'DPT014-N011T-01-B-15', '40', 5, 'Vert||Left||Over||RePosition||3C', 'Issued By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugIssueByWorkingMonth_DrugRequestStore', 'N003', 'CodeStatus', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-6', 'Accept Drugs', 'DPT014-N011T-01-B-15', '40', 6, 'Vert||Left||Over||RePosition||3C', 'Accept Drugs', 'wpgDrugAccept.POSFORFILEEXT?PageMode=AddNew', 'N003', 'UserContextLink', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-7', 'Accepted By Store', 'DPT014-N011T-01-B-15', '40', 7, 'Vert||Left||Over||RePosition||3C', 'Accepted By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugAcceptByDrugRequestStore_WorkingMonth', 'N003', 'BrowseReport', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-15-8', 'Accepted By Month', 'DPT014-N011T-01-B-15', '40', 8, 'Vert||Left||Over||RePosition||3C', 'Accepted By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugAcceptByWorkingMonth_DrugRequestStore', 'N003', 'BrowseViewAlloc', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);



'DPT014-N011T-01-B-24

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-1', 'Requests By Store', 'DPT014-N011T-01-B-24', '40', 1, 'Vert||Left||Over||RePosition||3C', 'Requests By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugRequest2ByDrugStore_WorkingMonth', 'N001', 'AdminBrowse', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-2', 'Requests By Month', 'DPT014-N011T-01-B-24', '40', 2, 'Vert||Left||Over||RePosition||3C', 'Requests By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugRequest2ByWorkingMonth_DrugStore', 'N001', 'BrowseRpt', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-3', 'Issue Drugs', 'DPT014-N011T-01-B-24', '40', 3, 'Vert||Left||Over||RePosition||3C', 'Issue Drugs', 'wpgDrugIssue.POSFORFILEEXT?PageMode=AddNew', 'N003', 'UserAccessible', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-4', 'Issued By Store', 'DPT014-N011T-01-B-24', '40', 4, 'Vert||Left||Over||RePosition||3C', 'Issued By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugIssueByDrugStore_WorkingMonth', 'N001', 'AdminBrowse', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-5', 'Issued By Month', 'DPT014-N011T-01-B-24', '40', 5, 'Vert||Left||Over||RePosition||3C', 'Issued By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugIssueByWorkingMonth_DrugStore', 'N003', 'Account', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-6', 'Accepted By Store', 'DPT014-N011T-01-B-24', '40', 6, 'Vert||Left||Over||RePosition||3C', 'Accepted By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugAcceptByDrugStore_WorkingMonth', 'N003', 'BulkPrintDependTbl', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N011T-01-B-24-7', 'Accepted By Month', 'DPT014-N011T-01-B-24', '40', 7, 'Vert||Left||Over||RePosition||3C', 'Accepted By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=DrugAcceptByWorkingMonth_DrugStore', 'N003', 'BankCharges', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);



DPT014-N012T-01-B-1900

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-1', 'Make Request', 'DPT014-N012T-01-B-1900', '40', 1, 'Vert||Left||Over||RePosition||3C', 'Make Request', 'wpgItemRequest2.POSFORFILEEXT?PageMode=AddNew', 'N003', 'AssignedTo', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-2', 'Requests By Store', 'DPT014-N012T-01-B-1900', '40', 2, 'Vert||Left||Over||RePosition||3C', 'Requests By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemRequest2ByItemRequestStore_WorkingMonth', 'N003', 'CellComponent', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-3', 'Requests By Month', 'DPT014-N012T-01-B-1900', '40', 3, 'Vert||Left||Over||RePosition||3C', 'Requests By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemRequest2ByWorkingMonth_ItemRequestStore', 'N003', 'BankAccountType', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-4', 'Issued By Store', 'DPT014-N012T-01-B-1900', '40', 4, 'Vert||Left||Over||RePosition||3C', 'Issued By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemIssueByItemRequestStore_WorkingMonth', 'N003', 'BulkEditAlloc', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-5', 'Issued By Month', 'DPT014-N012T-01-B-1900', '40', 5, 'Vert||Left||Over||RePosition||3C', 'Issued By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemIssueByWorkingMonth_ItemRequestStore', 'N003', 'CodeStatus', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-6', 'Accept Items', 'DPT014-N012T-01-B-1900', '40', 6, 'Vert||Left||Over||RePosition||3C', 'Accept Items', 'wpgItemAccept.POSFORFILEEXT?PageMode=AddNew', 'N003', 'UserContextLink', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-7', 'Accepted By Store', 'DPT014-N012T-01-B-1900', '40', 7, 'Vert||Left||Over||RePosition||3C', 'Accepted By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemAcceptByItemRequestStore_WorkingMonth', 'N003', 'BrowseReport', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1900-8', 'Accepted By Month', 'DPT014-N012T-01-B-1900', '40', 8, 'Vert||Left||Over||RePosition||3C', 'Accepted By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemAcceptByWorkingMonth_ItemRequestStore', 'N003', 'BrowseViewAlloc', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);




INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-1', 'Requests By Store', 'DPT014-N012T-01-B-1910', '40', 1, 'Vert||Left||Over||RePosition||3C', 'Requests By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemRequest2ByItemStore_WorkingMonth', 'N001', 'AdminBrowse', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);

INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-2', 'Requests By Month', 'DPT014-N012T-01-B-1910', '40', 2, 'Vert||Left||Over||RePosition||3C', 'Requests By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemRequest2ByWorkingMonth_ItemStore', 'N001', 'BrowseRpt', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-3', 'Issue Items', 'DPT014-N012T-01-B-1910', '40', 3, 'Vert||Left||Over||RePosition||3C', 'Issue Items', 'wpgItemIssue.POSFORFILEEXT?PageMode=AddNew', 'N003', 'UserAccessible', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-4', 'Issued By Store', 'DPT014-N012T-01-B-1910', '40', 4, 'Vert||Left||Over||RePosition||3C', 'Issued By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemIssueByItemStore_WorkingMonth', 'N001', 'AdminBrowse', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-5', 'Issued By Month', 'DPT014-N012T-01-B-1910', '40', 5, 'Vert||Left||Over||RePosition||3C', 'Issued By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemIssueByWorkingMonth_ItemStore', 'N003', 'Account', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-6', 'Accepted By Store', 'DPT014-N012T-01-B-1910', '40', 6, 'Vert||Left||Over||RePosition||3C', 'Accepted By Store', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemAcceptByItemStore_WorkingMonth', 'N003', 'BulkPrintDependTbl', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);
INSERT INTO "NavigationLink" ("NavigationLinkID", "NavigationLinkName", "ParentNavLinkID", "MenuElementTypeID", "PosInLink", "MenuProp", "LinkDetail", "LinkUrl", "NavigationLinkCatID", "NavigationLinkTypeID", "UserAccessibleID", "LinkOpenStyle", "OtherInfo", "TitleDesc", "KeyPrefix") VALUES ('DPT014-N012T-01-B-1910-7', 'Accepted By Month', 'DPT014-N012T-01-B-1910', '40', 7, 'Vert||Left||Over||RePosition||3C', 'Accepted By Month', 'WPGNavigateFrame.asp?FrameType=Browse&BROWSEVIEWNAME=ItemAcceptByWorkingMonth_ItemStore', 'N003', 'BankCharges', 'USA001', 'IN||NAV||800||600||Close', '-', '-', NULL);





