sql = "WITH VisitCostCTE AS ("
sql = sql & " SELECT "
sql = sql & "     FORMAT(Visitation.VisitDate, 'yyyy') AS VisitYear, "
sql = sql & "     FORMAT(Visitation.VisitDate, 'yyyy') + '_Q' + DATENAME(QUARTER, Visitation.VisitDate) AS VisitQuarter, "
sql = sql & "     SUM(Visitation.VisitCost) AS VisitationCost, "
sql = sql & "     LAG(SUM(Visitation.VisitCost)) "
sql = sql & "         OVER(PARTITION BY FORMAT(Visitation.VisitDate, 'yyyy') "
sql = sql & "         ORDER BY FORMAT(Visitation.VisitDate, 'yyyy'), DATENAME(QUARTER, Visitation.VisitDate)) AS [PrevCost], "
sql = sql & "     SUM(Visitation.VisitCost) - LAG(SUM(Visitation.VisitCost)) "
sql = sql & "         OVER(PARTITION BY FORMAT(Visitation.VisitDate, 'yyyy') "
sql = sql & "         ORDER BY FORMAT(Visitation.VisitDate, 'yyyy'), DATENAME(QUARTER, Visitation.VisitDate)) AS [Diff] "
sql = sql & " FROM Visitation "
sql = sql & " WHERE "
sql = sql & "     Visitation.VisitDate BETWEEN '2018-01-01' AND '2022-12-31' "
sql = sql & " GROUP BY "
sql = sql & "     FORMAT(Visitation.VisitDate, 'yyyy'), "
sql = sql & "     DATENAME(QUARTER, Visitation.VisitDate) "
sql = sql & "), "
sql = sql & "GroupCTE AS ("
sql = sql & " SELECT "
sql = sql & "     VisitYear, "
sql = sql & "     VisitQuarter, "
sql = sql & "     VisitationCost, "
sql = sql & "     PrevCost, "
sql = sql & "     Diff, "
sql = sql & "     (Diff * 100.00)/VisitationCost AS [PercentageChange], "
sql = sql & "     VisitationCost * 100.00 / SUM(VisitationCost) OVER() AS ContPercentage "
sql = sql & " FROM VisitCostCTE "
sql = sql & ") "
sql = sql & "SELECT "
sql = sql & "     VisitYear, "
sql = sql & "     VisitQuarter, "
sql = sql & "     FORMAT(VisitationCost, 'N2') AS VisitationCostF, "
sql = sql & "     VisitationCost, "
sql = sql & "     FORMAT(PrevCost, 'N2') AS PrevCost, "
sql = sql & "     FORMAT(Diff, 'N2') AS Diff, "
sql = sql & "     FORMAT(PercentageChange, 'N2') AS PercentageChange, "
sql = sql & "     FORMAT(ContPercentage, 'N2') AS ContPercentage "
sql = sql & "FROM GroupCTE "
sql = sql & "ORDER BY "
sql = sql & "     VisitYear, "
sql = sql & "     CASE "
sql = sql & "         WHEN RIGHT(VisitQuarter, 2) = 'Q1' THEN 1 "
sql = sql & "         WHEN RIGHT(VisitQuarter, 2) = 'Q2' THEN 2 "
sql = sql & "         WHEN RIGHT(VisitQuarter, 2) = 'Q3' THEN 3 "
sql = sql & "         WHEN RIGHT(VisitQuarter, 2) = 'Q4' THEN 4 "
sql = sql & "     END"
