sql = "SELECT DISTINCT "
sql = sql & "EMRRequestID, "
sql = sql & "EMRRequestItems.visitationID, "
sql = sql & "PatientName AS Patient, "
sql = sql & "GenderName AS Gender, "
sql = sql & "DATEDIFF(YEAR, Patient.Birthdate, GETDATE()) AS Age, "
sql = sql & "Patient.Occupation, "
sql = sql & "MaritalStatus.MaritalStatusName AS [Marital Status], "
sql = sql & "CAST(Patient.ResidenceAddress AS NVARCHAR(50)) AS [Residence Address], "
sql = sql & "Country.CountryName AS Country, "
sql = sql & "Sponsor.SponsorName AS [Insurance Type], "
sql = sql & "CONVERT(VARCHAR(20), Admission.AdmissionDate, 106) AS [Admission Date], "
sql = sql & "Ward.WardName AS Ward, "
sql = sql & "CONVERT(VARCHAR(20), Admission.DischargeDate, 106) AS [Discharge Date], "
sql = sql & "MedicalOutcome.MedicalOutcomeName AS Outcome, "
sql = sql & "MedicalStaff.MedicalStaffName AS Doctor "
sql = sql & "FROM EMRRequestItems "
sql = sql & "LEFT JOIN Patient ON Patient.PatientID = EMRRequestItems.PatientID "
sql = sql & "LEFT JOIN Gender ON Gender.GenderID = EMRRequestItems.GenderID "
sql = sql & "LEFT JOIN MaritalStatus ON MaritalStatus.MaritalStatusID = Patient.MaritalStatusID "
sql = sql & "LEFT JOIN Country ON Country.CountryID = Patient.CountryID "
sql = sql & "LEFT JOIN InsuredPatient ON EMRRequestItems.InsuredPatientID = InsuredPatient.InsuredPatientID "
sql = sql & "LEFT JOIN Sponsor ON InsuredPatient.SponsorID = Sponsor.SponsorID "
sql = sql & "LEFT JOIN Admission ON Admission.VisitationID = EMRRequestItems.VisitationID "
sql = sql & "LEFT JOIN Visitation ON Visitation.VisitationID = EMRRequestItems.VisitationID "
sql = sql & "LEFT JOIN MedicalOutcome ON MedicalOutcome.MedicalOutcomeID = Visitation.MedicalOutcomeID "
sql = sql & "LEFT JOIN MedicalStaff ON MedicalStaff.MedicalStaffID = Admission.MedicalStaffID "
sql = sql & "LEFT JOIN Ward ON Ward.WardID = Admission.WardID "
sql = sql & "WHERE EMRDataID = 'TH080';"
