response.write "<style>"
response.write "    /* Styling the container */"
response.write "    div {"
response.write "        padding: 10px;"
response.write "        border: 1px solid #ccc;"
response.write "        background-color: #f9f9f9;"
response.write "        border-radius: 8px;"
response.write "        width: 300px;"
response.write "        margin-bottom: 15px;"
response.write "        margin-top: 30px; /* Added 30px padding on top */"
response.write "    }"

response.write "    /* Label styling */"
response.write "    .font-style {"
response.write "        font-family: Arial, sans-serif;"
response.write "        font-size: 14px;"
response.write "        font-weight: bold;"
response.write "        color: #333;"
response.write "    }"

response.write "    /* Dropdown select styling */"
response.write "    select {"
response.write "        width: 100%;"
response.write "        padding: 8px;"
response.write "        border-radius: 4px;"
response.write "        border: 1px solid #aaa;"
response.write "        font-size: 14px;"
response.write "        background-color: #fff;"
response.write "        cursor: pointer;"
response.write "    }"

response.write "    /* Button styling */"
response.write "    button {"
response.write "        margin-top: 10px;"
response.write "        padding: 8px 15px;"
response.write "        border: none;"
response.write "        background-color: #007BFF;"
response.write "        color: white;"
response.write "        font-size: 14px;"
response.write "        border-radius: 4px;"
response.write "        cursor: pointer;"
response.write "        transition: background 0.3s ease-in-out;"
response.write "    }"

response.write "    /* Button hover effect */"
response.write "    button:hover {"
response.write "        background-color: #0056b3;"
response.write "    }"
response.write "</style>"
