Ringers Lactate Infusion 500ml - check
 PARACETAMOL INFUSION 1G - check
 INJ diazepam10 - check
 CEFTRIAXONE INJECTION 1G - check
 IV DEXTROSE 5% - check
 ATORVASTATIN TABLET 20MG - check
 FUROSEMIDE TABLET 40MG - check
 GALVUS TABLET 50MG - check
 FORXIGA TABLETS 10MG - check
 CLARITHROMYCIN TABLET 500MG - check
 NEXIUM INJECTION 40mg - check
 Ringers Lactate Infusion 500ml
 Ceftriaxone Injection 250mg - check
 INJECTION CITICOLINE - check
 AMLODIPINE TABLET 10MG - check
 CARVEDILOL TABLET 6.25MG - check


 Ringers Lactate Infusion 500ml
  PARACETAMOL INFUSION 1G
  INJ diazepam10
  CEFTRIAXONE INJECTION 1G
  IV DEXTROSE 5%
  ATORVASTATIN TABLET 20MG
  FUROSEMIDE TABLET 40MG
  GALVUS TABLET 50MG
  FORXIGA TABLETS 10MG
  CLARITHROMYCIN TABLET 500MG
  NEXIUM INJECTION 40mg
  Ringers Lactate Infusion 500ml
  Ceftriaxone Injection 250mg
  INJECTION CITICOLINE
  AMLODIPINE TABLET 10MG
  CARVEDILOL TABLET 6.25MG


  citicoline sachet
   Para. Tab. 1g
   CEFUROXIME TABLET 500MG
   Ringers Lactate Infusion 500ml
   PARACETAMOL INFUSION 1G
   iv dextrose 5% & sodium chloride 0.9 500ml
   VITAMIN B COMPLEX INJECTION
   Nifedipine Tablet 20mg
   CEFTRIAXONE INJECTION 1G
   ZYCARD TABLET 8MG
   INJECTION CITICOLINE
   CELECOXIB CASULES 200MG


   HIV Western Blot
    MALARIA ANTIGEN
    URINE ROUTINE EXAM.
    FULL BLOOD COUNT (FBC)
    TYPHOID IgG/1gM
    RANDOM BLOOD SUGAR (RBS)
    FASTING BLOOD SUGAR (FBS)
    FASTING BLOOD SUGAR (FBS)