response.write "<script>"
response.write "        function updateTreatment(){"
response.write "            const treatmentDate = new Date();"
response.write "            const treatmentType = document.getElementById('treatment-type');"
response.write "            const intervention = document.getElementById('intervention');"
response.write "            const treatmentValue = document.getElementById('treatment-value');"
response.write "            "
response.write "            let url = 'wpgXMLHTTP.asp?procedurename=UpdatePhysioTreatment';"
response.write "            if (treatmentDate && treatmentType?.value && intervention?.value && treatmentValue?.value) {"
response.write "                url = url + '&treatment-date=' + treatmentDate.toISOString().split('T')[0];" ' formats date as yyyy-mm-dd
response.write "                url = url + '&treatment-type=' + encodeURIComponent(treatmentType.value);"
response.write "                url = url + '&intervention=' + encodeURIComponent(intervention.value);"
response.write "                url = url + '&treatment-value=' + encodeURIComponent(treatmentValue.value);"
' response.write "                url = url + '&visitid=' + visitID;" ' Uncomment and add the visitID variable if needed
response.write "                fetch(url).then(response => response.json()).then(data => {"
response.write "                    window.location.reload();"
response.write "                });"
response.write "            } else {"
response.write "                alert('Please enter all values');"
response.write "            }"
response.write "        }"
response.write "    </script>"
response.write "  </body>"
response.write "</html>"
