'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>

Dim visitationID
visitationID = Request.querystring("VisitationID")

'tableStyles
populateTable

Sub populateTable()
    Dim count, sql, rst, PatientName, admissionDate, dischargeDate, operation, duty, medOfficer
    count = 1

    Set rst = CreateObject("ADODB.Recordset")

    sql = "SELECT DISTINCT ER.EMRRequestID FROM EMRRequest ER "
    sql = sql & "JOIN EMRResults ERT ON ERT.EMRRequestID = ER.EMRRequestID "
    sql = sql & "WHERE ERT.EMRDataID = 'E000047' AND ER.VisitationID = '" & visitationID & "'"

    With rst
        .open qryPro.FltQry(sql), conn, 3, 4
        
        If .RecordCount > 0 Then

          PatientName = getEMRResult(.fields("EMRRequestID"), "E000047", "E000038", "column2")
          admissionDate = getEMRResult(.fields("EMRRequestID"), "E000047", "E000039", "column2")
          dischargeDate = getEMRResult(.fields("EMRRequestID"), "E000047", "E000039", "column5")
          operation = getEMRResult(.fields("EMRRequestID"), "E000047", "E000040", "column2")
          duty = getEMRResult(.fields("EMRRequestID"), "E000047", "E000040", "column5")
          medOfficer = getEMRResult(.fields("EMRRequestID"), "E000047", "E000041", "column6")

            
response.write "<style>"
response.write "      * {"
response.write "        margin: 0;"
response.write "        padding: 0;"
response.write "        box-sizing: border-box;"
'Response.Write "        all: initial; "
response.write "      }"
response.write ""
response.write "      .mybody {"
response.write "        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
response.write "        background-color: #f4f4f9;"
response.write "        padding: 40px;"
response.write "      }"
response.write ""
response.write "      .container {"
response.write "        width: 1000px;"
response.write "        background-color: #fff;"
response.write "        padding: 30px;"
response.write "        border-radius: 10px;"
response.write "        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);"
response.write "        margin: 0 auto;"
response.write "        border-top: 5px solid #007bff;"
response.write "      }"
response.write ""
response.write "      .myheader {"
response.write "        text-align: center;"
response.write "        margin-bottom: 30px;"
response.write "      }"
response.write ""
response.write "      .logo {"
response.write "        width: 80px;"
response.write "        margin-bottom: 10px;"
response.write "      }"
response.write ""
response.write "      h1 {"
response.write "        font-size: 1.8rem;"
response.write "        margin-bottom: 5px;"
response.write "        color: #333;"
response.write "      }"
response.write ""
response.write "      p {"
response.write "        font-size: 0.95rem;"
response.write "        color: #555;"
response.write "        margin-bottom: 5px;"
response.write "      }"
response.write ""
response.write "      h2 {"
response.write "        text-align: center;"
response.write "        margin-bottom: 30px;"
response.write "        font-size: 1.5rem;"
response.write "        color: #333;"
response.write "      }"
response.write ""
response.write "      .myform {"
response.write "        display: flex;"
response.write "        flex-direction: column;"
response.write "        all: initial;"
response.write "        text-align: left !important; "
response.write "      }"
response.write ""
response.write "      .mylabel {"
response.write "        font-size: 1rem;"
response.write "        color: #333;"
response.write "        margin-bottom: 5px;"
response.write "      }"
response.write ""
response.write "      .myinput[type='text'] {"
response.write "        padding: 10px 5px;"
response.write "        margin-bottom: 30px;"
response.write "        border: none;"
response.write "        border-bottom: 2px solid #007bff;"
response.write "        font-size: 1rem;"
response.write "        color: #333;"
response.write "        background-color: transparent;"
response.write "        outline: none;"
response.write "        transition: border-bottom 0.3s ease;"
response.write "      }"
response.write ""
response.write "      .myinput[type='text']:focus {"
response.write "        border-bottom: 2px solid #0056b3;"
response.write "      }"
response.write ""
response.write "      .signature {"
response.write "        display: flex;"
response.write "        justify-content: space-between;"
response.write "        align-items: center;"
response.write "      }"
response.write ""
response.write "      .signature p {"
response.write "        font-size: 1rem;"
response.write "        color: #333;"
response.write "      }"
response.write ""
response.write "      .signature .myinput[type='text'] {"
response.write "        width: calc(100% - 160px);"
response.write "      }"
response.write ""
response.write "      .signature .myinput[type='date'] {"
response.write "        width: 150px;"
response.write "      }"
response.write "    </style>"
response.write "  </head>"
response.write "  <div class=""mybody"">"
response.write "    <div class=""container"">"
response.write "      <header class=""myheader"">"
response.write "        <img"
response.write "          src=""https://via.placeholder.com/100"""
response.write "          alt=""Clinic Logo"""
response.write "          class=""logo"""
response.write "        />"
response.write "        <h1>Airport Clinic Limited</h1>"
response.write "        <p>Private Mail Bag</p>"
response.write "        <p>Kotoka International Airport, Accra, Ghana</p>"
response.write "        <p>Tel: (+233-302) 764987 / 0505 527641</p>"
response.write "      </header>"
response.write ""
response.write "      <h2>Excuse Duty Form</h2>"
response.write ""
response.write "      <form class=""myform"" style='text-align: left'>"
response.write "        <label for=""name"" class=""mylabel"">Name:</label> <br>"
response.write "        <input"
response.write "          class=""myinput"""
response.write "          type=""text"""
response.write "          id=""name"""
response.write "          name=""name"""
response.write "          value=""ATUOBI Alexander"""
response.write "        />"
response.write "<br>"
response.write "        <label for=""admission"" class=""mylabel"">Date of Admission:</label>"
response.write "        <input"
response.write "          type=""text"""
response.write "          id=""admission"""
response.write "          name=""admission"""
response.write "          value=""05 sep 2024"""
response.write "          class=""myinput"""
response.write "        />"
response.write "<br>"
response.write "        <label for=""discharge"" class=""mylabel"">Date of Discharge:</label>"
response.write "        <input"
response.write "          class=""myinput"""
response.write "          type=""text"""
response.write "          id=""discharge"""
response.write "          name=""discharge"""
response.write "          value=""10 sep 2024"""
response.write "        />"
response.write "<br>"
response.write "        <label for=""operation"" class=""mylabel"">Operation:</label>"
response.write "        <input"
response.write "          class=""myinput"""
response.write "          type=""text"""
response.write "          id=""operation"""
response.write "          name=""operation"""
response.write "          value=""CS"""
response.write "        />"
response.write "<br>"
response.write "        <label for=""excuse"" class=""mylabel"">Excuse Duty:</label>"
response.write "        <input"
response.write "          class=""myinput"""
response.write "          type=""text"""
response.write "          id=""excuse"""
response.write "          name=""excuse"""
response.write "          value=""Patient needs a vacation and a special treat at Zanziba"""
response.write "        />"
response.write "<br>"
response.write "        <div class=""signature"">"
response.write "          <p>Medical Officer:</p>"
response.write "          <input"
response.write "            class=""myinput"""
response.write "            type=""text"""
response.write "            id=""medicalOfficer"""
response.write "            name=""medicalOfficer"""
response.write "            value=""Dr. ATUOBI Alexander"""
response.write "          />"
response.write "          <label for=""date"" class=""mylabel"">Date:</label>"
response.write "          <input"
response.write "            class=""myinput"""
response.write "            type=""text"""
response.write "            id=""date"""
response.write "            name=""date"""
response.write "            value=""11 sep 2024"""
response.write "          />"
response.write "        </div>"
response.write "      </form>"
response.write "    </div>"
response.write "  </div>"

        Else
            response.write "<h3 class='container'>No records found for this visit</h3>"
        End If
        
        .Close
    End With
    
    Set rst = Nothing
End Sub


Function getEMRResult(EMRRequestID, emrDataID, CompID, column)

    Dim sql, rst
    Set rst = Server.CreateObject("ADODB.Recordset")
    getEMRResult = ""

    sql = "SELECT * FROM emrresults WHERE emrrequestid ='" & EMRRequestID & "'"
    sql = sql & " AND emrdataid ='" & emrDataID & "' AND emrcomponentid='" & CompID & "'"
    
    With rst
        .open qryPro.FltQry(sql), conn, 3, 4
        If .RecordCount > 0 Then
            .MoveFirst
            If Not IsNull(.fields(column)) Then
                getEMRResult = Trim(.fields(column))
            End If
            If IsNull(.fields(column)) Then
                getEMRResult = "Null"
            End If
        End If
    End With
    Set rst = Nothing

End Function

Sub tableStyles()
    
    response.write "<style>"
    response.write "  * { "
    response.write "      margin: 0; "
    response.write "      padding: 0; "
    response.write "      box-sizing: border-box; "
    response.write "      all: initial; "
    response.write "  } "
  
    response.write "  .mybody { "
    response.write "      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; "
    response.write "      background-color: #f4f4f9; "
    response.write "      padding: 40px; "
    response.write "      all: initial; "
    response.write "  } "
    
    response.write "      .container {"
    response.write "        max-width: 600px;"
    response.write "        background-color: #fff;"
    response.write "        padding: 30px;"
    response.write "        border-radius: 10px;"
    response.write "        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);"
    response.write "        margin: 0 auto;"
    response.write "        border-top: 5px solid #007bff;"
    response.write "      }"
    response.write ""
    response.write "      header {"
    response.write "        text-align: center;"
    response.write "        margin-bottom: 30px;"
    response.write "      }"
    response.write ""
    response.write "      .logo {"
    response.write "        width: 80px;"
    response.write "        margin-bottom: 10px;"
    response.write "      }"
    response.write ""
    response.write "      h1 {"
    response.write "        font-size: 1.8rem;"
    response.write "        margin-bottom: 5px;"
    response.write "        color: #333;"
    response.write "      }"
    response.write ""
    response.write "      p {"
    response.write "        font-size: 0.95rem;"
    response.write "        color: #555;"
    response.write "        margin-bottom: 5px;"
    response.write "      }"
    response.write ""
    response.write "      h2 {"
    response.write "        text-align: center;"
    response.write "        margin-bottom: 30px;"
    response.write "        font-size: 1.5rem;"
    response.write "        color: #333;"
    response.write "      }"
    response.write ""
    response.write "      .myform {"
    response.write "        display: flex;"
    response.write "        flex-direction: column;"
    response.write "      }"
    response.write ""
    response.write "      label {"
    response.write "        font-size: 1rem;"
    response.write "        color: #333;"
    response.write "        margin-bottom: 5px;"
    response.write "      }"
    response.write ""
    response.write "      .myinput[type='text'] {"
    response.write "        padding: 10px 5px;"
    response.write "        margin-bottom: 30px;"
    response.write "        border: none;"
    response.write "        border-bottom: 2px solid #007bff;"
    response.write "        font-size: 1rem;"
    response.write "        color: #333;"
    response.write "        background-color: transparent;"
    response.write "        outline: none;"
    response.write "        transition: border-bottom 0.3s ease;"
    response.write "      }"
    response.write ""
    response.write "      .myinput[type='text']:focus {"
    response.write "        border-bottom: 2px solid #0056b3;"
    response.write "      }"
    response.write ""
    response.write "      .signature {"
    response.write "        display: flex;"
    response.write "        justify-content: space-between;"
    response.write "        align-items: center;"
    response.write "      }"
    response.write ""
    response.write "      .signature p {"
    response.write "        font-size: 1rem;"
    response.write "        color: #333;"
    response.write "      }"
    response.write ""
    response.write "      .signature input[type='text'] {"
    response.write "        width: calc(100% - 160px);"
    response.write "      }"
    response.write ""
    response.write "      .signature input[type='date'] {"
    response.write "        width: 150px;"
    response.write "      }"
    response.write "    </style>"

End Sub

Sub tableStyles01()
  response.write "  <style> "
  response.write "  * { "
  response.write "      margin: 0; "
  response.write "      padding: 0; "
  response.write "      box-sizing: border-box; "
  response.write "  } "
  
  response.write "  .mybody { "
  response.write "      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; "
  response.write "      background-color: #f4f4f9; "
  response.write "      padding: 40px; "
  response.write "  } "
  
  response.write "  .container { "
  response.write "      max-width: 600px; "
  response.write "      background-color: #fff; "
  response.write "      padding: 30px; "
  response.write "      border-radius: 10px; "
  response.write "      box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); "
  response.write "      margin: 0 auto; "
  response.write "      border-top: 5px solid #007bff; "

  response.write "  } "
  
  response.write "  .frm-header { "
  response.write "      text-align: center; "
  response.write "      margin-bottom: 30px; "
  response.write "  } "
  
  response.write "  .logo { "
  response.write "      width: 80px; "
  response.write "      margin-bottom: 10px; "
  response.write "  } "
  response.write "  .frm-header h1 { "
  response.write "      font-size: 1.8rem; "
  response.write "      margin-bottom: 5px; "
  response.write "      color: #333; "
  response.write "  } "
  response.write "  .frm-header p, .signature p { "
  response.write "      font-size: 0.95rem; "
  response.write "      color: #555; "
  response.write "      margin-bottom: 5px; "
  response.write "  } "
  response.write "  .container h2 { "
  response.write "      text-align: center; "
  response.write "      margin-bottom: 30px; "
  response.write "      font-size: 1.5rem; "
  response.write "      color: #333; "
  response.write "  } "
  response.write "  .frm-detail { "
  response.write "      display: flex; "
  response.write "      flex-direction: column; "
  response.write "  } "
  response.write "  .mylabel { "
  response.write "      font-size: 1rem; "
  response.write "      color: #333; "
  response.write "      margin-bottom: 5px; "
  response.write "  } "
  response.write "  .frm-detail .myinput[type='text'] { "
  response.write "      padding: 10px 5px; "
  response.write "      margin-bottom: 30px; "
  response.write "      border: none; "
  response.write "      border-bottom: 2px solid #007bff; "
  response.write "      font-size: 1rem; "
  response.write "      color: #333; "
  response.write "      background-color: transparent; "
  response.write "      outline: none; "
  response.write "      transition: border-bottom 0.3s ease; "
  response.write "  } "
  response.write "  .frm-detail .myinput[type='text']:focus { "
  response.write "      border-bottom: 2px solid #0056b3; "
  response.write "  } "
  response.write "  .signature { "
  response.write "      display: flex; "
  response.write "      justify-content: space-between; "
  response.write "      align-items: center; "
  response.write "  } "
  response.write "  .signature p { "
  response.write "      font-size: 1rem; "
  response.write "      color: #333; "
  response.write "  } "
  response.write "  .signature .myinput[type='text'] { "
  response.write "      width: calc(100% - 160px); "
  response.write "  } "
  response.write "  .signature .myinput[type='date'] { "
  response.write "      width: 150px; "
  response.write "  } "
  response.write "  </style> "
End Sub

'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
