UPDATE "YBMHMS01"."dbo"."BillPeriod" SET "BillPeriodDate"='2025-07-31T00:00:00.000' WHERE  "BillPeriodID"=N'MTH202506-CASH';
SELECT "BillPeriodID", "BillPeriodName", "BillYearID", "BillDayID", "BillMonthID", "BillPeriodTypeID", "BillPeriodStatusID", "BillPeriodDate", "BillPeriodInfo1", "BillPeriodInfo2", "BillPeriodInfo3", "BillPeriodInfo4", "BillPeriodDate1", "BillPeriodDate2", "BillPeriodDate3", "BillPeriodDate4", "BillPeriodValue1", "BillPeriodValue2", "BillPeriodValue3", "BillPeriodValue4", "Description", "KeyPrefix" FROM "YBMHMS01"."dbo"."BillPeriod" WHERE  "BillPeriodID"=N'MTH202506-CASH';

-- IMAH:
NSERT INTO "IMAHMS01"."dbo"."PrintOutAlloc" ("PrintLayoutID", "JobScheduleID", "TableID", "ItemPos", "PrintDetails") VALUES (N'unservedPresc', N'HIM001', N'WorkingDay', 1, N'Yes');
SELECT "PrintLayoutID", "JobScheduleID", "TableID", "ItemPos", "PrintDetails" FROM "IMAHMS01"."dbo"."PrintOutAlloc" WHERE  "JobScheduleID"=N'HIM001' AND "PrintLayoutID"=N'unservedPresc';
SELECT SUM("rows") FROM "sys"."partitions" WHERE "index_id" IN (0, 1) AND "object_id" = object_id('IMAHMS01.dbo.PrintOutAlloc');

Y&B
INSERT INTO "Specialist" ("SpecialistID", "SpecialistName", "SpecialistTypeID", "SpecialistStatusID", "AppointInterval", "NumberOfAppoint", "ContactInfo", "SpecialistDate", "SpecialistVal", "SpecialistInfo", "KeyPrefix") VALUES ('sackey.ruth', 'Ruth Sackey', 'ANT01', 'CD006', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO "Specialist" ("SpecialistID", "SpecialistName", "SpecialistTypeID", "SpecialistStatusID", "AppointInterval", "NumberOfAppoint", "ContactInfo", "SpecialistDate", "SpecialistVal", "SpecialistInfo", "KeyPrefix") VALUES ('botchway.alice', 'Alice Botchway', 'ANT01', 'CD006', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO "SpecialistType" ("SpecialistTypeID", "SpecialistTypeName", "SpecialistGroupID", "SpecialistClassID", "BillGroupCatID", "BillGroupID", "LevelOfAccessID", "ConsultPercent", "TreatPercent", "DiagnosePercent", "SpecialistTypeVal1", "SpecialistTypeVal2", "SpecialistTypeVal3", "SpecialistTypeVal4", "SpecialistTypeInfo1", "SpecialistTypeInfo2", "SpecialistTypeDate1", "SpecialistTypeDate2", "KeyPrefix", "BillInput1", "BillInput2", "BillInput3", "BillInout4") VALUES ('ANT01', 'ANTENATAL', 'CD006', 'S001', 'NONE', 'B03', 'All', 0, 0, 0, 0, 0, 120, 0, '', '', NULL, NULL, '', 0, 0, 0, 0);

INSERT INTO "ConsultCostMatrix" ("VisitTypeID", "SpecialistTypeID", "AgeGroupID", "InsuranceTypeID", "VisitTypeVal", "SpecialistTypeVal", "AgeGroupVal", "InsuranceTypeVal", "VisitCost", "PermuteUpdateID", "PermuteStatusID", "Column1", "Column2", "Column3", "Column4", "Column5", "Column6") VALUES ('V001', 'ANT01', 'A002', 'I100', 150, 150, 150, 150, 150, 'P001', 'P001', '', '', '', '', '', '');
INSERT INTO "ConsultCostMatrix" ("VisitTypeID", "SpecialistTypeID", "AgeGroupID", "InsuranceTypeID", "VisitTypeVal", "SpecialistTypeVal", "AgeGroupVal", "InsuranceTypeVal", "VisitCost", "PermuteUpdateID", "PermuteStatusID", "Column1", "Column2", "Column3", "Column4", "Column5", "Column6") VALUES ('V002', 'ANT01', 'A002', 'I100', 100, 100, 100, 100, 100, 'P001', 'P001', '', '', '', '', '', '');
INSERT INTO "ConsultCostMatrix" ("VisitTypeID", "SpecialistTypeID", "AgeGroupID", "InsuranceTypeID", "VisitTypeVal", "SpecialistTypeVal", "AgeGroupVal", "InsuranceTypeVal", "VisitCost", "PermuteUpdateID", "PermuteStatusID", "Column1", "Column2", "Column3", "Column4", "Column5", "Column6") VALUES ('V003', 'ANT01', 'A002', 'I100', 100, 100, 100, 100, 100, 'P001', 'P001', '', '', '', '', '', '');
INSERT INTO "ConsultCostMatrix" ("VisitTypeID", "SpecialistTypeID", "AgeGroupID", "InsuranceTypeID", "VisitTypeVal", "SpecialistTypeVal", "AgeGroupVal", "InsuranceTypeVal", "VisitCost", "PermuteUpdateID", "PermuteStatusID", "Column1", "Column2", "Column3", "Column4", "Column5", "Column6") VALUES ('V004', 'ANT01', 'A002', 'I100', 100, 100, 100, 100, 100, 'P001', 'P001', '', '', '', '', '', '');
