'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
Response.Write "    <style>"
Response.Write "      .header {"
Response.Write "        display: flex;"
Response.Write "        flex-direction: column;"
Response.Write "        justify-content: center;"
Response.Write "        align-items: center;"
Response.Write "      }"
Response.Write "      .header h2 {"
Response.Write "        margin: 2px 0px;"
Response.Write "        font-size: larger;"
Response.Write "        color: black;"
Response.Write "      }"
Response.Write "      .first-head {"
Response.Write "        display: flex;"
Response.Write "        justify-content: center;"
Response.Write "        align-items: center;"
Response.Write "        font-size: small;"
Response.Write "        padding-bottom: 10px;"
Response.Write "      }"
Response.Write "      .first-head p {"
Response.Write "        margin: 2px 0px;"
Response.Write "      }"
Response.Write "      .first-head img {"
Response.Write "        height: 8vh;"
Response.Write "        width: auto;"
Response.Write "      }"
Response.Write "      .main {"
Response.Write "        position: relative;"
Response.Write "        font-family: sans-serif;"
Response.Write "        padding: 0.5rem;"
Response.Write "      }"
Response.Write "      .main::after {"
Response.Write "        content: '';"
Response.Write "        display: block;"
Response.Write "        position: absolute;"
Response.Write "        top: 0;"
Response.Write "        right: 0;"
Response.Write "        bottom: 0;"
Response.Write "        left: 0;"
Response.Write "        background-image: url(images/banner1.bmp);"
Response.Write "        opacity: 0.06;"
Response.Write "        z-index: -1;"
Response.Write "        background-position: center;"
Response.Write "        background-size: 80%;"
Response.Write "        background-repeat: no-repeat;"
Response.Write "      }"
Response.Write "      .header-style {"
Response.Write "        width: 100%;"
Response.Write "        display: flex;"
Response.Write "        flex-wrap: wrap;"
Response.Write "        justify-content: space-between;"
Response.Write "        font-size: 12px;"
Response.Write "        padding: 8px 0;"
Response.Write "        border-bottom: 1px solid #ccc;"
Response.Write "        margin-bottom: 10px;"
Response.Write "      }"
Response.Write "      .header-style label {"
Response.Write "        margin: 2px 0;"
Response.Write "      }"
Response.Write "      .table {"
Response.Write "        width: 100%;"
Response.Write "        font-family: monospace;"
Response.Write "        border-collapse: collapse;"
Response.Write "      }"
Response.Write "      .table td {"
Response.Write "        padding: 4px;"
Response.Write "      }"
Response.Write "      .myfont {"
Response.Write "        font-size: 12px;"
Response.Write "      }"
Response.Write "      .amount-row td {"
Response.Write "        padding-top: 10px;"
Response.Write "      }"
Response.Write "    </style>"
Response.Write "  "
Response.Write "    <div style=""width: 80mm; margin: auto"">"
Response.Write "      <main class=""main"" style=""width: 75mm; margin: 0 auto"">"
Response.Write "        <div class=""header"">"
Response.Write "          <div class=""first-head"">"
Response.Write "            <img src=""images/banner1.bmp"" />"
Response.Write "          </div>"
Response.Write "          <div class=""first-head"">"
Response.Write "            <div style=""flex-direction: column; padding: 8px 8px"">"
Response.Write "              <h2 style=""text-align: center"">"
Response.Write "                International Maritime Hospital(IMaH)"
Response.Write "              </h2>"
Response.Write "              <p style=""text-align: center"">Tel: +233(0)303-220030</p>"
Response.Write "              <p style=""text-align: center"">"
Response.Write "                Location: Community One, Tema, Accra"
Response.Write "              </p>"
Response.Write "            </div>"
Response.Write "          </div>"
Response.Write "        </div>"
Response.Write ""
Response.Write "        <div class=""header-style"">"
Response.Write "          <label>Item Sale ID: D1234535533</label>"
Response.Write "          <label>Cashier: Lardy Tatania Palazar</label>"
Response.Write "          <label>Time: 8th April, 2024</label>"
Response.Write "        </div>"
Response.Write ""
Response.Write "        <table class=""table"">"
Response.Write "          <tr>"
Response.Write "            <td class=""myfont""><b>ITEM NAME</b></td>"
Response.Write "            <td class=""myfont""><b>QTY</b></td>"
Response.Write "            <td class=""myfont""><b>PRICE</b></td>"
Response.Write "            <td class=""myfont""><b>TOTAL</b></td>"
Response.Write "          </tr>"
Response.Write "          <tr>"
Response.Write "            <td class=""myfont"">Banana</td>"
Response.Write "            <td class=""myfont"">6</td>"
Response.Write "            <td class=""myfont"">5.00</td>"
Response.Write "            <td class=""myfont"">30.00</td>"
Response.Write "          </tr>"
Response.Write "          <tr class=""amount-row"">"
Response.Write "            <td class=""myfont"" colspan=""2""><b>AMOUNT:</b></td>"
Response.Write "            <td class=""myfont"" colspan=""2""><b>GH₵ 30.00</b></td>"
Response.Write "          </tr>"
Response.Write "        </table>"
Response.Write "      </main>"
Response.Write "    </div>"
Response.Write "  "
Response.Write "</html>"

'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>
'None
'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
