
Response.Write "<!DOCTYPE html>"
Response.Write "<html lang=""en"">"
Response.Write "  <head>"
Response.Write "    <meta charset=""UTF-8"" />"
Response.Write "    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />"
Response.Write "    <title>Final Version!!....</title>"
Response.Write "    <style>"
Response.Write "      .main {"
Response.Write "        margin-top: 5px;"
Response.Write "        font-size: 12pt;"
Response.Write "        font-family: Arial, Helvetica, sans-serif;"
Response.Write "        width: 210mm;"
Response.Write "        height: 297mm;"
Response.Write "        margin-left: auto;"
Response.Write "        margin-right: auto;"
Response.Write "      }"
Response.Write ""
Response.Write "      .header {"
Response.Write "        width: 100%;"
Response.Write "        margin: 1.6px 0;"
Response.Write "        display: flex;"
Response.Write "        align-items: center;"
Response.Write "        justify-content: center;"
Response.Write "        gap: 10px;"
Response.Write "        position: relative;"
Response.Write "      }"
Response.Write ""
Response.Write "      .image {"
Response.Write "        position: absolute;"
Response.Write "        left: 60px;"
Response.Write "        margin-top: 20px;"
Response.Write "      }"
Response.Write ""
Response.Write "      .header-text {"
Response.Write "        flex-grow: 1;"
Response.Write "        text-align: center;"
Response.Write "      }"
Response.Write ""
Response.Write "      .header-text h1 {"
Response.Write "        font-size: 1.5rem;"
Response.Write "        margin: 0;"
Response.Write "      }"
Response.Write ""
Response.Write "      .header-text h3 {"
Response.Write "        font-size: 1rem;"
Response.Write "        margin: 0.25rem 0;"
Response.Write "      }"
Response.Write ""
Response.Write "      .contact-details {"
Response.Write "        font-size: 10pt;"
Response.Write "        line-height: 5px;"
Response.Write "        width: auto;"
Response.Write "        max-width: 25rem;"
Response.Write "        margin: 0 0 0 auto;"
Response.Write "      }"
Response.Write ""
Response.Write "      .contact-details p {"
Response.Write "        display: flex;"
Response.Write "        align-items: center;"
Response.Write "      }"
Response.Write ""
Response.Write "      .contact-details p strong {"
Response.Write "        width: 12.5rem;"
Response.Write "        display: inline-block;"
Response.Write "      }"
Response.Write ""
Response.Write "      .contact-details p span {"
Response.Write "        margin-left: 0.3125rem;"
Response.Write "        padding-right: 0.5rem;"
Response.Write "      }"
Response.Write ""
Response.Write "      .address-and-po-details {"
Response.Write "        display: flex;"
Response.Write "        flex-direction: row;"
Response.Write "        gap: 93px;"
Response.Write "        margin-top: 5px;"
Response.Write "        width: 100%;"
Response.Write "      }"
Response.Write ""
Response.Write "      .address {"
Response.Write "        flex: 1;"
Response.Write "        flex-basis: 100px;"
Response.Write "        flex-wrap: wrap;"
Response.Write "        font-weight: bold;"
Response.Write "        line-height: 10px;"
Response.Write "      }"
Response.Write ""
Response.Write "      .po-details {"
Response.Write "        flex: 2;"
Response.Write "        line-height: 0.3125rem;"
Response.Write "        font-size: 0.875rem;"
Response.Write "      }"
Response.Write ""
Response.Write "      .po-details p {"
Response.Write "        display: flex;"
Response.Write "        align-items: center;"
Response.Write "      }"
Response.Write ""
Response.Write "      .po-details p label {"
Response.Write "        width: 12.5rem;"
Response.Write "        display: inline-block;"
Response.Write "        font-weight: bold;"
Response.Write "      }"
Response.Write ""
Response.Write "      .po-details p span {"
Response.Write "        margin-left: 0.3125rem;"
Response.Write "        padding-right: 0.5rem;"
Response.Write "      }"
Response.Write ""
Response.Write "      .table-div {"
Response.Write "        width: 100%;"
Response.Write "        margin-top: 1rem;"
Response.Write "      }"
Response.Write ""
Response.Write "      table {"
Response.Write "        width: 100%;"
Response.Write "        border-collapse: collapse;"
Response.Write "      }"
Response.Write ""
Response.Write "      th,"
Response.Write "      td {"
Response.Write "        border: 1px solid black;"
Response.Write "        padding: 0.3rem;"
Response.Write "        text-align: left;"
Response.Write "      }"
Response.Write ""
Response.Write "      .signatories {"
Response.Write "        margin-top: 3rem;"
Response.Write "        line-height: 1rem;"
Response.Write "      }"
Response.Write ""
Response.Write "      .remarks {"
Response.Write "        margin-top: 1rem;"
Response.Write "        line-height: 1.2rem;"
Response.Write "        font-size: 10pt;"
Response.Write "      }"
Response.Write ""
Response.Write "      .remarks p {"
Response.Write "        display: flex;"
Response.Write "        align-items: flex-start;"
Response.Write "        gap: 1rem;"
Response.Write "      }"
Response.Write ""
Response.Write "      .remarks p label {"
Response.Write "        flex: 0 0 100px;"
Response.Write "        text-align: left;"
Response.Write "        font-weight: bold;"
Response.Write "      }"
Response.Write ""
Response.Write "      .remarks p span {"
Response.Write "        flex: 1;"
Response.Write "        text-align: left;"
Response.Write "      }"
Response.Write ""
Response.Write "      .tdr {"
Response.Write "        text-align: right;"
Response.Write "      }"
Response.Write ""
Response.Write "      * {"
Response.Write "        overflow: visible !important;"
Response.Write "      }"
Response.Write ""
Response.Write "      @media screen and (max-width: 768px) {"
Response.Write "        .main {"
Response.Write "          margin: 0.5rem;"
Response.Write "          width: 100%;"
Response.Write "          height: auto;"
Response.Write "        }"
Response.Write ""
Response.Write "        .header {"
Response.Write "          flex-direction: column;"
Response.Write "          align-items: center;"
Response.Write "          gap: 0.5rem;"
Response.Write "          position: static;"
Response.Write "        }"
Response.Write ""
Response.Write "        .image {"
Response.Write "          position: static;"
Response.Write "          left: 0;"
Response.Write "        }"
Response.Write ""
Response.Write "        .header-text {"
Response.Write "          margin-top: 0.5rem;"
Response.Write "        }"
Response.Write ""
Response.Write "        .contact-details {"
Response.Write "          margin: 0.5rem 0;"
Response.Write "          max-width: 100%;"
Response.Write "        }"
Response.Write ""
Response.Write "        .address-and-po-details {"
Response.Write "          flex-direction: column;"
Response.Write "          gap: 1rem;"
Response.Write "        }"
Response.Write ""
Response.Write "        .address,"
Response.Write "        .po-details {"
Response.Write "          flex: none;"
Response.Write "          width: 100%;"
Response.Write "        }"
Response.Write ""
Response.Write "        .remarks p {"
Response.Write "          flex-direction: column;"
Response.Write "          gap: 0.5rem;"
Response.Write "        }"
Response.Write ""
Response.Write "        .remarks p label,"
Response.Write "        .remarks p span {"
Response.Write "          flex: none;"
Response.Write "          width: 100%;"
Response.Write "          text-align: left;"
Response.Write "        }"
Response.Write "      }"
Response.Write "    </style>"
Response.Write "  </head>"
Response.Write "  <div class=""main"">"
Response.Write "    <div class=""header"">"
Response.Write "      <div class=""image"">"
Response.Write "        <img src=""./images/imah.jpeg"" width=""90"" height=""90"" alt=""Imah Logo"" />"
Response.Write "      </div>"
Response.Write "      <div class=""header-text"">"
Response.Write "        <h1>INTERNATIONAL MARITIME HOSPITAL</h1>"
Response.Write "        <h3>Purchase Order No: IMAH-004915-1</h3>"
Response.Write "      </div>"
Response.Write "    </div>"
Response.Write ""
Response.Write "    <div class=""contact-details"">"
Response.Write "      <p><strong>Telephone</strong> <span>:</span></p>"
Response.Write "      <p><strong>Fax</strong> <span>:</span></p>"
Response.Write "      <p><strong>Tax registration number</strong> <span>:</span></p>"
Response.Write "    </div>"
Response.Write ""
Response.Write "    <div class=""address-and-po-details"">"
Response.Write "      <div class=""address"">"
Response.Write "        <p>To: Vine Medics Ltd/30000661</p>"
Response.Write "        <p style=""padding-left: 28px"">Achimota ABC Junction</p>"
Response.Write "        <p style=""padding-left: 28px"">Accra, Box</p>"
Response.Write "        <p style=""padding-left: 28px"">GHA</p>"
Response.Write "      </div>"
Response.Write "      <div class=""po-details"">"
Response.Write "        <p><label>Page</label> <span>: 1 of 1</span></p>"
Response.Write "        <p><label>Creation date</label> <span>: 2/19/2025</span></p>"
Response.Write "        <p>"
Response.Write "          <label>Print date/time</label>"
Response.Write "          <span>: 2/19/2025 1:18:21 PM</span>"
Response.Write "        </p>"
Response.Write "        <p>"
Response.Write "          <label>Prepayment obligation</label>"
Response.Write "          <span>: No</span>"
Response.Write "        </p>"
Response.Write "        <p><label>Currency</label> <span>: GHS</span></p>"
Response.Write "        <p><label>Delivery date</label> <span>: 2/21/2025</span></p>"
Response.Write "        <p><label>PR Number</label> <span>: </span></p>"
Response.Write "        <p><label>RFQ Number</label> <span>: </span></p>"
Response.Write "        <p><label>Requisitioner</label> <span>: </span></p>"
Response.Write "        <p><label>Created by</label> <span>: Theophilus Adom Bonsu</span></p>"
Response.Write "      </div>"
Response.Write "    </div>"
Response.Write ""
Response.Write "    <div class=""table-div"">"
Response.Write "      <table class=""mytable"">"
Response.Write "        <thead>"
Response.Write "          <tr>"
Response.Write "            <th class=""myth"">Item</th>"
Response.Write "            <th class=""myth"">Description</th>"
Response.Write "            <th class=""myth"">Qty</th>"
Response.Write "            <th class=""myth"">Unit</th>"
Response.Write "            <th class=""myth"">Unit Price</th>"
Response.Write "            <th class=""myth tdr"">Amount</th>"
Response.Write "          </tr>"
Response.Write "        </thead>"
Response.Write "        <tbody>"
Response.Write "          <tr>"
Response.Write "            <td class=""mytd"">25000033</td>"
Response.Write "            <td class=""mytd"">Blood Lancet:</td>"
Response.Write "            <td class=""mytd"" class=""tdr"">50.00</td>"
Response.Write "            <td class=""mytd"">Pck</td>"
Response.Write "            <td class=""mytd tdr"">14.0000</td>"
Response.Write "            <td class=""mytd tdr"">700.00</td>"
Response.Write "          </tr>"
Response.Write "          <tr>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td colspan=""3"" class=""mytd tdr"">"
Response.Write "              <strong>SubTotal</strong>"
Response.Write "            </td>"
Response.Write "            <td class=""mytd tdr""><strong> 700.00</strong></td>"
Response.Write "          </tr>"
Response.Write "          <tr>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td colspan=""3"" class=""mytd tdr"">"
Response.Write "              <strong>Discount</strong>"
Response.Write "            </td>"
Response.Write "            <td class=""mytd tdr""><strong>0.00</strong></td>"
Response.Write "          </tr>"
Response.Write "          <tr>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td colspan=""3"" class=""mytd tdr"">"
Response.Write "              <strong>Msc. Charges</strong>"
Response.Write "            </td>"
Response.Write "            <td class=""mytd tdr""><strong> 0.00</strong></td>"
Response.Write "          </tr>"
Response.Write "          <tr>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td colspan=""3"" class=""mytd tdr"">"
Response.Write "              <strong>Total VAT</strong>"
Response.Write "            </td>"
Response.Write "            <td class=""mytd tdr""><strong>0.00</strong></td>"
Response.Write "          </tr>"
Response.Write "          <tr>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td class=""mytd""></td>"
Response.Write "            <td colspan=""3"" class=""mytd tdr"">"
Response.Write "              <strong>Total Amount</strong>"
Response.Write "            </td>"
Response.Write "            <td class=""mytd tdr""><strong>700.00</strong></td>"
Response.Write "          </tr>"
Response.Write "        </tbody>"
Response.Write "      </table>"
Response.Write "    </div>"
Response.Write ""
Response.Write "    <div class=""signatories"">"
Response.Write "      <p>"
Response.Write "        ............................................................................."
Response.Write "      </p>"
Response.Write "      <p>CEO (International Maritime Hospital)</p>"
Response.Write "      <p><strong>Delivery Terms:</strong> <span></span></p>"
Response.Write "      <p><strong>Delivery Mode: </strong><span></span></p>"
Response.Write "      <p><strong>Payment Terms: </strong><span>Net of 60 days</span></p>"
Response.Write "    </div>"
Response.Write ""
Response.Write "    <div class=""remarks"">"
Response.Write "      <p><u>Remarks</u></p>"
Response.Write "      <p><strong>The Terms and Conditions from IMaH are as follows:</strong></p>"
Response.Write "      <p>"
Response.Write "        <label><u>WARRANTY:</u></label>"
Response.Write "        <span"
Response.Write "          >Goods supplied under this Purchase Order must be covered by warranty"
Response.Write "          and clearly stated on the delivery Documents</span"
Response.Write "        >"
Response.Write "      </p>"
Response.Write "      <p>"
Response.Write "        <label><u>ACCEPTANCE:</u></label>"
Response.Write "        <span"
Response.Write "          >Goods delivered are deemed to be accepted only after the IMaH has"
Response.Write "          gone through its internal Goods acceptance processes.</span"
Response.Write "        >"
Response.Write "      </p>"
Response.Write "      <p>"
Response.Write "        <label><u>CANCELLATION:</u></label>"
Response.Write "        <span"
Response.Write "          >IMAH reserves the right to cancel the Purchase Order at any time"
Response.Write "          prior to delivery and shall not be subject to any charges or fees as a"
Response.Write "          result of the cancellation</span"
Response.Write "        >"
Response.Write "      </p>"
Response.Write "      <p>"
Response.Write "        <label><u>DELIVERY:</u></label>"
Response.Write "        <span"
Response.Write "          >The specific quantity ordered must be delivered in full to the buyers"
Response.Write "          address as stated</span"
Response.Write "        >"
Response.Write "      </p>"
Response.Write "      <p>"
Response.Write "        <label><u>TERMINATION:</u></label>"
Response.Write "        <span"
Response.Write "          >The seller must comply with stated delivery date. IMaH reserves the"
Response.Write "          right to cancel the order without notice when the date elapse</span"
Response.Write "        >"
Response.Write "      </p>"
Response.Write "      <p>"
Response.Write "        <label><u>TAXES:</u></label>"
Response.Write "        <span"
Response.Write "          >Invoices will be subjected to existing Government of Ghana"
Response.Write "          withholding taxes unless seller provides proof of exemption</span"
Response.Write "        >"
Response.Write "      </p>"
Response.Write "    </div>"
Response.Write "  </div>"
Response.Write "</html>"
