'<<--BEGIN_CODE_SEGMENT_PRINTHEADER-->>
Response.write "It Works"
Styles
Printout

Sub Styles()
    Response.write "    <style>"
    Response.write "      .main {"
    Response.write "        margin-top: 5px;"
    Response.write "        font-size: 12pt;"
    Response.write "        font-family: Arial, Helvetica, sans-serif;"
    Response.write "        width: 210mm;"
    Response.write "        height: 297mm;"
    Response.write "        margin-left: auto;"
    Response.write "        margin-right: auto;"
    Response.write "        text-align: left; /* Ensure no inherited centering */"
    Response.write "      }"
    Response.write ""
    Response.write "      .header {"
    Response.write "        width: 100%;"
    Response.write "        margin: 1.6px 0;"
    Response.write "        display: flex;"
    Response.write "        align-items: center;"
    Response.write "        justify-content: center;"
    Response.write "        gap: 10px;"
    Response.write "        position: relative;"
    Response.write "      }"
    Response.write ""
    Response.write "      .image {"
    Response.write "        position: absolute;"
    Response.write "        left: 60px;"
    Response.write "        margin-top: 20px;"
    Response.write "        border: 1px solid red;" ' Removed stray single quote
    Response.write "      }"
    Response.write ""
    Response.write "      .header-text {"
    Response.write "        flex-grow: 1;"
    Response.write "        text-align: center;"
    Response.write "      }"
    Response.write ""
    Response.write "      .header-text h1 {"
    Response.write "        font-size: 1.5rem;"
    Response.write "        margin: 0;"
    Response.write "      }"
    Response.write ""
    Response.write "      .header-text h3 {"
    Response.write "        font-size: 1rem;"
    Response.write "        margin: 0.25rem 0;"
    Response.write "      }"
    Response.write ""
    Response.write "      .contact-details {"
    Response.write "        font-size: 10pt;"
    Response.write "        line-height: 5px;"
    Response.write "        width: auto;"
    Response.write "        max-width: 25rem;"
    Response.write "        margin: 0 0 0 auto;"
    Response.write "        text-align: left; /* Ensure left alignment */"
    Response.write "      }"
    Response.write ""
    Response.write "      .contact-details p {"
    Response.write "        display: flex;"
    Response.write "        align-items: center;"
    Response.write "      }"
    Response.write ""
    Response.write "      .contact-details p strong {"
    Response.write "        width: 12.5rem;"
    Response.write "        display: inline-block;"
    Response.write "      }"
    Response.write ""
    Response.write "      .contact-details p span {"
    Response.write "        margin-left: 0.3125rem;"
    Response.write "        padding-right: 0.5rem;"
    Response.write "      }"
    Response.write ""
    Response.write "      .address-and-po-details {"
    Response.write "        display: flex;"
    Response.write "        flex-direction: row;"
    Response.write "        gap: 93px;"
    Response.write "        margin-top: 5px;"
    Response.write "        width: 100%;"
    Response.write "      }"
    Response.write ""
    Response.write "      .address {"
    Response.write "        flex: 1;"
    Response.write "        flex-basis: 100px;"
    Response.write "        flex-wrap: wrap;"
    Response.write "        font-weight: bold;"
    Response.write "        line-height: 10px;"
    Response.write "        text-align: left; /* Ensure left alignment */"
    Response.write "      }"
    Response.write ""
    Response.write "      .po-details {"
    Response.write "        flex: 2;"
    Response.write "        line-height: 0.3125rem;"
    Response.write "        font-size: 0.875rem;"
    Response.write "        text-align: left; /* Ensure left alignment */"
    Response.write "      }"
    Response.write ""
    Response.write "      .po-details p {"
    Response.write "        display: flex;"
    Response.write "        align-items: center;"
    Response.write "      }"
    Response.write ""
    Response.write "      .po-details p label {"
    Response.write "        width: 12.5rem;"
    Response.write "        display: inline-block;"
    Response.write "        font-weight: bold;"
    Response.write "      }"
    Response.write ""
    Response.write "      .po-details p span {"
    Response.write "        margin-left: 0.3125rem;"
    Response.write "        padding-right: 0.5rem;"
    Response.write "      }"
    Response.write ""
    Response.write "      .table-div {"
    Response.write "        width: 100%;"
    Response.write "        margin-top: 1rem;"
    Response.write "      }"
    Response.write ""
    Response.write "      .mytable {"
    Response.write "        width: 100%;"
    Response.write "        border-collapse: collapse;"
    Response.write "      }"
    Response.write ""
    Response.write "      .myth,"
    Response.write "      .mytd {"
    Response.write "        border: 1px solid black;"
    Response.write "        padding: 0.3rem;"
    Response.write "        text-align: left;"
    Response.write "      }"
    Response.write ""
    Response.write "      .signatories {"
    Response.write "        margin-top: 3rem;"
    Response.write "        line-height: 1rem;"
    Response.write "        text-align: left; /* Ensure left alignment */"
    Response.write "      }"
    Response.write ""
    Response.write "      .remarks {"
    Response.write "        margin-top: 1rem;"
    Response.write "        line-height: 1.2rem;"
    Response.write "        font-size: 10pt;"
    Response.write "      }"
    Response.write ""
    Response.write "      .remarks p {"
    Response.write "        display: flex;"
    Response.write "        align-items: flex-start;"
    Response.write "        gap: 1rem;"
    Response.write "      }"
    Response.write ""
    Response.write "      .remarks p label {"
    Response.write "        flex: 0 0 100px;"
    Response.write "        text-align: left;"
    Response.write "        font-weight: bold;"
    Response.write "      }"
    Response.write ""
    Response.write "      .remarks p span {"
    Response.write "        flex: 1;"
    Response.write "        text-align: left;"
    Response.write "      }"
    Response.write ""
    Response.write "      .tdr {"
    Response.write "        text-align: right;"
    Response.write "      }"
    Response.write ""
    Response.write "      * {"
    Response.write "        overflow: visible !important;"
    Response.write "      }"
    Response.write ""
    Response.write "      @media screen and (max-width: 768px) {"
    Response.write "        .main {"
    Response.write "          margin: 0.5rem;"
    Response.write "          width: 100%;"
    Response.write "          height: auto;"
    Response.write "        }"
    Response.write ""
    Response.write "        .header {"
    Response.write "          flex-direction: column;"
    Response.write "          align-items: center;"
    Response.write "          gap: 0.5rem;"
    Response.write "          position: static;"
    Response.write "        }"
    Response.write ""
    Response.write "        .image {"
    Response.write "          position: static;"
    Response.write "          left: 0;"
    Response.write "        }"
    Response.write ""
    Response.write "        .header-text {"
    Response.write "          margin-top: 0.5rem;"
    Response.write "        }"
    Response.write ""
    Response.write "        .contact-details {"
    Response.write "          margin: 0.5rem 0;"
    Response.write "          max-width: 100%;"
    Response.write "          text-align: left; /* Ensure left alignment on smaller screens */"
    Response.write "        }"
    Response.write ""
    Response.write "        .address-and-po-details {"
    Response.write "          flex-direction: column;"
    Response.write "          gap: 1rem;"
    Response.write "        }"
    Response.write ""
    Response.write "        .address,"
    Response.write "        .po-details {"
    Response.write "          flex: none;"
    Response.write "          width: 100%;"
    Response.write "          text-align: left; /* Ensure left alignment on smaller screens */"
    Response.write "        }"
    Response.write ""
    Response.write "        .signatories {"
    Response.write "          text-align: left; /* Ensure left alignment on smaller screens */"
    Response.write "        }"
    Response.write ""
    Response.write "        .remarks p {"
    Response.write "          flex-direction: column;"
    Response.write "          gap: 0.5rem;"
    Response.write "        }"
    Response.write ""
    Response.write "        .remarks p label,"
    Response.write "        .remarks p span {"
    Response.write "          flex: none;"
    Response.write "          width: 100%;"
    Response.write "          text-align: left;"
    Response.write "        }"
    Response.write "      }"
    Response.write "    </style>"
End Sub

Sub Printout()
    Response.write "  <div class=""main"">"
    Response.write "    <div class=""header"">"
    Response.write "      <div class=""image"">"
    Response.write "        <img src=""images/letterhead5.jpg"" width=""90"" height=""90"" alt=""Imah Logo"" />"
    Response.write "      </div>"
    Response.write "      <div class=""header-text"">"
    Response.write "        <h1>INTERNATIONAL MARITIME HOSPITAL</h1>"
    Response.write "        <h3>Purchase Order No:" & GetRecordField("DrugPurOrderID") & "</h3>"
    Response.write "      </div>"
    Response.write "    </div>"
    Response.write ""
    Response.write "    <div class=""contact-details"">"
    Response.write "      <p><strong>Telephone</strong> <span>:</span></p>"
    Response.write "      <p><strong>Fax</strong> <span>:</span></p>"
    Response.write "      <p><strong>Tax registration number</strong> <span>:</span></p>"
    Response.write "    </div>"
    Response.write ""
    Response.write "    <div class=""address-and-po-details"">"
    Response.write "      <div class=""address"">"
    Response.write "        <p>To: Vine Medics Ltd/30000661</p>"
    Response.write "        <p style=""padding-left: 28px"">Achimota ABC Junction</p>"
    Response.write "        <p style=""padding-left: 28px"">Accra, Box</p>"
    Response.write "        <p style=""padding-left: 28px"">GHA</p>"
    Response.write "      </div>"
    Response.write "      <div class=""po-details"">"
    Response.write "        <p><label>Page</label> <span>: 1 of 1</span></p>"
    Response.write "        <p><label>Creation date</label> <span>: 2/19/2025</span></p>"
    Response.write "        <p>"
    Response.write "          <label>Print date/time</label>"
    Response.write "          <span>: 2/19/2025 1:18:21 PM</span>"
    Response.write "        </p>"
    Response.write "        <p>"
    Response.write "          <label>Prepayment obligation</label>"
    Response.write "          <span>: No</span>"
    Response.write "        </p>"
    Response.write "        <p><label>Currency</label> <span>: GHS</span></p>"
    Response.write "        <p><label>Delivery date</label> <span>: 2/21/2025</span></p>"
    Response.write "        <p><label>PR Number</label> <span>: </span></p>"
    Response.write "        <p><label>RFQ Number</label> <span>: </span></p>"
    Response.write "        <p><label>Requisitioner</label> <span>: </span></p>"
    Response.write "        <p><label>Created by</label> <span>: Theophilus Adom Bonsu</span></p>"
    Response.write "      </div>"
    Response.write "    </div>"
    Response.write ""
    Response.write "    <div class=""table-div"">"
    Response.write "      <table class=""mytable"">"
    Response.write "        <thead>"
    Response.write "          <tr>"
    Response.write "            <th class=""myth"">Item</th>"
    Response.write "            <th class=""myth"">Description</th>"
    Response.write "            <th class=""myth"">Qty</th>"
    Response.write "            <th class=""myth"">Unit</th>"
    Response.write "            <th class=""myth"">Unit Price</th>"
    Response.write "            <th class=""myth tdr"">Amount</th>"
    Response.write "          </tr>"
    Response.write "        </thead>"
    Response.write "        <tbody>"
    Response.write "          <tr>"
    Response.write "            <td class=""mytd"">25000033</td>"
    Response.write "            <td class=""mytd"">Blood Lancet:</td>"
    Response.write "            <td class=""mytd tdr"">50.00</td>" ' Fixed duplicate class attribute
    Response.write "            <td class=""mytd"">Pck</td>"
    Response.write "            <td class=""mytd tdr"">14.0000</td>"
    Response.write "            <td class=""mytd tdr"">700.00</td>"
    Response.write "          </tr>"
    Response.write "          <tr>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td colspan=""3"" class=""mytd tdr"">"
    Response.write "              <strong>SubTotal</strong>"
    Response.write "            </td>"
    Response.write "            <td class=""mytd tdr""><strong> 700.00</strong></td>"
    Response.write "          </tr>"
    Response.write "          <tr>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td colspan=""3"" class=""mytd tdr"">"
    Response.write "              <strong>Discount</strong>"
    Response.write "            </td>"
    Response.write "            <td class=""mytd tdr""><strong>0.00</strong></td>"
    Response.write "          </tr>"
    Response.write "          <tr>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td colspan=""3"" class=""mytd tdr"">"
    Response.write "              <strong>Msc. Charges</strong>"
    Response.write "            </td>"
    Response.write "            <td class=""mytd tdr""><strong> 0.00</strong></td>"
    Response.write "          </tr>"
    Response.write "          <tr>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td colspan=""3"" class=""mytd tdr"">"
    Response.write "              <strong>Total VAT</strong>"
    Response.write "            </td>"
    Response.write "            <td class=""mytd tdr""><strong>0.00</strong></td>"
    Response.write "          </tr>"
    Response.write "          <tr>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td class=""mytd""></td>"
    Response.write "            <td colspan=""3"" class=""mytd tdr"">"
    Response.write "              <strong>Total Amount</strong>"
    Response.write "            </td>"
    Response.write "            <td class=""mytd tdr""><strong>700.00</strong></td>"
    Response.write "          </tr>"
    Response.write "        </tbody>"
    Response.write "      </table>"
    Response.write "    </div>"
    Response.write ""
    Response.write "    <div class=""signatories"">"
    Response.write "      <p>"
    Response.write "        ............................................................................."
    Response.write "      </p>"
    Response.write "      <p>CEO (International Maritime Hospital)</p>"
    Response.write "      <p><strong>Delivery Terms:</strong> <span></span></p>"
    Response.write "      <p><strong>Delivery Mode: </strong><span></span></p>"
    Response.write "      <p><strong>Payment Terms: </strong><span>Net of 60 days</span></p>"
    Response.write "    </div>"
    Response.write ""
    Response.write "    <div class=""remarks"">"
    Response.write "      <p><u>Remarks</u></p>"
    Response.write "      <p><strong>The Terms and Conditions from IMaH are as follows:</strong></p>"
    Response.write "      <p>"
    Response.write "        <label><u>WARRANTY:</u></label>"
    Response.write "        <span"
    Response.write "          >Goods supplied under this Purchase Order must be covered by warranty"
    Response.write "          and clearly stated on the delivery Documents</span"
    Response.write "        >"
    Response.write "      </p>"
    Response.write "      <p>"
    Response.write "        <label><u>ACCEPTANCE:</u></label>"
    Response.write "        <span"
    Response.write "          >Goods delivered are deemed to be accepted only after the IMaH has"
    Response.write "          gone through its internal Goods acceptance processes.</span"
    Response.write "        >"
    Response.write "      </p>"
    Response.write "      <p>"
    Response.write "        <label><u>CANCELLATION:</u></label>"
    Response.write "        <span"
    Response.write "          >IMAH reserves the right to cancel the Purchase Order at any time"
    Response.write "          prior to delivery and shall not be subject to any charges or fees as a"
    Response.write "          result of the cancellation</span>"
    Response.write "      </p>"
    Response.write "      <p>"
    Response.write "        <label><u>DELIVERY:</u></label>"
    Response.write "        <span"
    Response.write "          >The specific quantity ordered must be delivered in full to the buyers"
    Response.write "          address as stated</span>"
    Response.write "      </p>"
    Response.write "      <p>"
    Response.write "        <label><u>TERMINATION:</u></label>"
    Response.write "        <span"
    Response.write "          >The seller must comply with stated delivery date. IMaH reserves the"
    Response.write "          right to cancel the order without notice when the date elapse</span>"
    Response.write "      </p>"
    Response.write "      <p>"
    Response.write "        <label><u>TAXES:</u></label>"
    Response.write "        <span"
    Response.write "          >Invoices will be subjected to existing Government of Ghana"
    Response.write "          withholding taxes unless seller provides proof of exemption</span>"
    Response.write "      </p>"
    Response.write "    </div>"
    Response.write "  </div>"
End Sub



'<<--END_CODE_SEGMENT_PRINTHEADER-->>
'>
'>
'>
'>
'>
'<<--BEGIN_CODE_SEGMENT_PRINTFOOTER-->>

'<<--END_CODE_SEGMENT_PRINTFOOTER-->>
